<?php 
	$user =  $this->user_information ;
?>
<style type="text/css">
ul#info_ul span {
	color:#e35b5a;
	font-weight:bold;
}
.widget-wrap {
	min-height:auto
}
p {
	white-space:nowrap;
}
</style>

<div class="panel">
  <div class="panel-body">
    <div class="row white-box">
      
      <div class="col-sm-3"> 
        <a data-gallery="example-gallery" data-toggle="lightbox" href="<?php echo getUserImage($this->user_information[T_USERS_CONST.'_image'],'900x600');?>" title="Profile Images">
          <img src="<?php echo getUserImage($this->user_information[T_USERS_CONST.'_image'],'206x137');?>" class="img_border" />
        </a><br>
        <small>(Click on photo to view enlarge)</small>
      </div>
      <div class="col-sm-9">
        <div class="form-content" style="padding:20px;">
          <table class="table table-bordered Clear" style="margin:0px !important;">
            <tbody>
              <tr>
                <td class="" width="30%;"><b>Full Name:</b></td>
                <td>
                  <b><?php echo $this->user_information[T_USERS_CONST.'_name']; ?></b>
                </td>
              </tr>              
              <tr>
                <td class="" width="30%;"><b>Email Address:</b></td>
                <td>
                  <b><?php echo $this->user_information[T_USERS_CONST.'_email']==''?'N/A':$this->user_information[T_USERS_CONST.'_email'];?></b>
                </td>
              </tr>
              <tr>
                <td class="" width="30%;"><b>User Name:</b></td>
                <td>
                  <b><?php echo $this->user_information[T_USERS_CONST.'_username']==''?'N/A':$this->user_information[T_USERS_CONST.'_username'];?></b>
                </td>
              </tr>
              <tr>
                <td class="" width="30%;"><b>Location:</b></td>
                <td>
                  <b><?php echo $this->user_information[T_USERS_CONST.'_address']==''?'N/A':$this->user_information[T_USERS_CONST.'_address'];?></b>
                </td>
              </tr>
              <tr>
                <td class="" width="30%;"><b>Gender:</b></td>
                <td>
                	<b><?php $gender_arr = array("0"=>"Male","1"=>"Female",'2'=>"Other"); if(array_key_exists($this->user_information[T_USERS_CONST.'_gender'],$gender_arr)) { echo $gender_arr[$this->user_information[T_USERS_CONST.'_gender']];} ?></b>
                </td>
              </tr>
              <tr>
              	<td class="" width="30%"><b>Date of Birth:</b></td>
              	<td>
              		<b><?= $this->user_information[T_USERS_CONST.'_birthday'] ?></b>
              	</td>
              </tr>
              <tr>
              	<td class="" width="30%"><b>Paypal Email Address:</b></td>
              	<td>
              		<b><?= $this->user_information[T_USERS_CONST.'_paypal_email'] ?></b>
              	</td>
              </tr>
            </tbody>
          </table>
          <hr />
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(window).on('load', function() {
  $(document).on('click', '[data-toggle="lightbox"]', function(event) {
      event.preventDefault();
      $(this).ekkoLightbox();
  });
});
</script>