<style type="text/css">
	.cntlbl{background:#010101;color:#fff;width:20px;height:20px;display:inline-block;text-align:center;border-radius:50%;margin-left:2px;}
	.export-userbtn{background:#000;padding:10px 18px;position:relative;top:1px;color:#fff;border-radius:3px;}
	.export-userbtn:hover{text-decoration:none;color:#fff;}
</style>
<div class="panel">

  <div class="panel-body">

      

      <form method="post" action="<?php echo ADMIN_APPLICATION_URL?>/remove-users" onsubmit="return checkSelects('userForm')" id="userForm">

      <div class="row">

        <div class="col-md-6 mb-15"> 

          <button class="btn btn-danger btn-rounded waves-effect waves-classic DeleteBtn"><span class="btn-label"><i class="fa fa-trash"></i></span>

          <?=$this->layout()->translator->translate("del_sel_txt")?>

          </button>
		  <a href="javascript:void(0)" class="export-userbtn">Export Users</a>	
        </div>

      </div>

      

        

        <table id="sample_1"  class="table table-hover dataTable table-striped w-full table-bordered">

          <thead>

            <tr>

              <th width="5%">S.No.</th>

              <th><div class="text-center">

                  <input id="deletebcchk" name="deletebcchk" type="checkbox" class="group-checkable">

                  <label for="deletebcchk"></label>

                </div></th>

              <th>Full Name</th>

              <th>Email Address</th>

              <th>Member Since</th>

              <th>Status</th>
              <th class="none">Username</th>
              <th class="none">Birthday</th>
			  <th class="none">Gender</th>
              <th class="none">Location</th>
              <th>Action</th>

            </tr>

          </thead>

          <tbody>

          </tbody>

        </table>

      </form>

    </div>

  

</div>

<script type="text/javascript" charset="utf-8">



$(document).ready(function(e) {

	var slength=[1,5,6];

	var surl='<?php echo APPLICATION_URL.'/'.BACKEND?>/getusers';

	<?php if($this->userId!=''){?>

	var surl='<?php echo APPLICATION_URL.'/'.BACKEND?>/getusers/<?php echo $this->userId?>';	

<? 	}?>

	$('#sample_1').DataTable({

		

		"language":{"lengthMenu": "Show _MENU_ records"},

		"bProcessing":true,

		"bServerSide":false,

		"bAutoWidth":false,

		"responsive":true,

		"responsive": {

			 "details": {

				renderer: function(api, rowIdx, columns){

				   var $row_details = $.fn.DataTable.Responsive.defaults.details.renderer(api, rowIdx, columns);

				   var elems = Array.prototype.slice.call($($row_details).find('.js-switch:not(.test)'));

				   elems.forEach(function(html) {

					  var switchery = new Switchery(html,{color:'#03A9F4',size:'small'});

					  if (switchery.markedAsSwitched()) { $('.js-switch').addClass("test");}

					});

				   return $row_details;

				}

			 }

		 },

		"bInfo":false,

		"pagingType":"full_numbers",

		"order":[[0,"desc"]],

		"aoColumnDefs":[

			{"bSortable":false,"aTargets":slength},

			{"bSearchable":false,"aTargets":slength}

		 ],

		"sAjaxSource": surl,

		"iDisplayLength":50,

	    "aLengthMenu":[[50,100,150],[50,100,150]],

		"fnDrawCallback":function(oSettings){

			if($(".deimg").length>0){

				$('.deimg').initial(); 

			}

			var elems=Array.prototype.slice.call(document.querySelectorAll('.js-switch:not(.test)'));

			elems.forEach(function(html) {

			 	 var switchery = new Switchery(html,{color:'#03A9F4',size:'small'});

				 if (switchery.markedAsSwitched()) { $('.js-switch').addClass("test"); }

			});

		},

	

		

		

	});

});
	
$(document).on("click",".export-userbtn",function() {
    exportArr = new Array();
    var formData1 = new FormData($("form#userForm")[0]);
    $(".checkboxes:checked").each(function(){
        exportArr.push($(this).val());
    });
    if(exportArr.length > 0) {
        var ids = exportArr.join(',');
        window.location.replace(baseUrl+'/export-user/'+ids);
    } else {
        window.location.replace(baseUrl+'/export-user');
    }
	setTimeout(function(){ location.reload() }, 2000);
})	

</script> 

