<div class="blog-page blog-detail-page">	
	<div class="comman-section">
		<div class="container">
			<div class="common-heading">
                <h2 class="heading"> Last testament heading goes here  </h2>
                <div class="blog-post">
                    <div class="cricle-logo"> <img src="<?=HTTP_IMG_PATH?>/cricle-logo.png">  </div>
                    <div class="">
                        <div class="">
                            <h2 class="titles"> The Collective Coven</h2>
                            <p class="post-date mb-0"> Dec 13 2019 </p>

                        </div>
                    </div>
                </div>
			</div>
		</div>	
    </div>
    
    <div class="blog-page-middal-section">
        <div class="container">
                    <div class="blog-detail-section">
                        <div class="right-side-section pl-0">
                            
                            <div class="blog-content pt-0">
                                <h2 class="blog-heading"> Heading goes here </h2>
                                <p class="descripton"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
                                <p class="descripton"> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
                                <div class="detail-img1"> <img src="<?=HTTP_IMG_PATH?>/blog-detail.jpg"> </div>
                                <p class="descripton"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
                                <p class="descripton"> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
                                <div class="detail-img2"> <img src="<?=HTTP_IMG_PATH?>/blog-detail1.jpg"> </div>
                            </div>
                            <!-- blog-content -->

                            <div class="blog-views">
                                <div class="left">
                                    <p class="views mb-0"> <span>0</span> views </p>
                                    <p class="comments"><a class="" href="#"> Write a comment </a></p>
                                    <p class="comments share-post"><a class="" href="#"> Share post </a></p>
                                </div>
                                <div class="like-icons">  <img src="<?=HTTP_IMG_PATH?>/heart.svg"> </div>
                            </div>
                            <!-- blog-views -->

                        </div>
                        <!-- right side section -->
                    </div><!-- blog-detail-section -->
        </div>
    </div>
    <!-- blog page middal section -->
</div>