<div class="index-main" >
			<video class="background-video" playsinline="playsinline" autoplay muted loop>
				<source src="<?=HTTP_IMG_PATH?>/fog-background.mp4" type="video/mp4">
			</video>
			<div class="overlay-wcs"></div>
				<div class="home-section">
					<div class="overlay-bg"></div>
					<div class="container">

					<!-- new text -->

					<div class="top-content">
						<h1 class="heading"> <?php if(!empty($HomePageData[1]["home_content"])) { echo $HomePageData[1]["home_content"]; } else { ?>Welcome To the collective coven<?php } ?> </h1>
						<p class="description"> <?php if(!empty($HomePageData[2]["home_content"])) { echo $HomePageData[2]["home_content"]; } else { ?>Come Join us in the Dark in the only Marketplace where Hallowneen enthusiasts, fans of gore, horror and the macabre congregate to conjure up some Magic.<br/> Come Join the Coven!<?php } ?> </p>
					</div>
					<!-- new text -->

					<div class="scroll-box">
						<span> Scroll </span>
						<i class="fas fa-chevron-down"></i>
					</div>
				</div>
			</div>
	</div>

	<div class="second-section">
		<div class="container">
			<div class="category-section d-none">
				<div class="category-part">
					<ul class="product-blk">
						<?php if(!empty($product_categories)) { foreach($product_categories as $product_categories => $product_categories_val) { ?>
							<li class=" margin-bottoms catblk-item" data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000"><div class="part-1"><a href="<?= APPLICATION_URL.'/product-listing?category='.$product_categories_val["category_id"]; ?>"><?= $product_categories_val["category_feild"] ?></a></div></li>	
						<?php } } ?>
					</ul>
				</div>
				<div class="border-gradient"><a href="javascript:void(0)" class="view-btn btn catmore-btn"><?= $configs["site_view_more"] ?></a></div>
			</div>
			<?php if(!empty($favorite_products)) { ?>
				<div class="most-popular prod-list">
					<h1 class="heading" data-aos="zoom-in-down"><?php if(!empty($HomePageData[3]["home_content"])) { echo $HomePageData[3]["home_content"]; } else { ?>Favorite Conjurings<?php } ?></h1>
					<div class="owl-carousel one" data-aos="fade-up" data-aos-duration="4000">
						<?php foreach (array_chunk($favorite_products, 8) as $group) { ?>					
							<div class="item" data-aos="flip-left">
								<div class="form-row">

									<?php  foreach($group as $favorite_products_key => $favorite_products_val) { $product_picarr = array();
									$price_data = $this->layout()->AbstractModel->Super_Get(T_PROQTY,"color_productid =:PID","fetch",array('warray'=>array('PID'=>$favorite_products_val["product_id"])));
									?>
									<div class="col-xl-3 col-6">
									<div class="item">
										<div class="itmanc-tg" data-href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>">
										<div class="card menu-card">
										<?php if($favorite_products_val[T_CLIENT_VAR."client_bestseller"] == '1') { ?>
											<div class="ribbon-pop"><span>Best Seller</span></div>
										<?php } ?>
										<div class="slider-img">
										<?php if(!empty($favorite_products_val["product_photos"])) {
													$product_picarr = explode(",",$favorite_products_val["product_photos"]);
											  } 
										?>
										<div class="card-img-top">
										<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>">
										<?php if(!empty($favorite_products_val["product_defaultpic"])) { ?> 
														<img class="" src="<?=HTTP_PRODUCT_PIC_PATH?>/thumb/<?= $favorite_products_val["product_defaultpic"] ?>" alt="Card image cap">
													<?php } else {
													if(!empty($favorite_products_val["product_photos"])) { ?>
														<img class="" src="<?=HTTP_PRODUCT_PIC_PATH?>/thumb/<?= $product_picarr[0] ?>" alt="Card image cap">
											<?php } } ?></a>					
															<div class="coven-overlay d-none"></div> </div> 
												<?php if($favorite_products_val["shipping_free"] == '1' && $favorite_products_val[T_CLIENT_VAR."client_country"] == $loggedUser->{T_CLIENT_VAR."client_country"} && $favorite_products_val["product_isdigital"] != '1') { ?>
													<div class="freeship-holder"><div class="freeship-txt">Free Shipping</div></div>
												<?php } else { ?>
													<div class="freeship-holder">&nbsp;</div>
												<?php } ?> 
										</div>
										<div class="card-body">
											<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>" class="card-anctg"><h1 class="card-title"><?= $favorite_products_val["product_title"] ?></h1>
											</a>
											<p class="price-txt"> <span class="mrp-price"> </span> <span>$<?php if($favorite_products_val["product_isdigital"] == '1') { echo $favorite_products_val["product_price"]; } else { echo $price_data["color_price"]; } ?></span> </p>
											<div class="btn-block">
												<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>" class="btn view-btn"> View Detail </a>
												<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>#cart" class="btn cart-btn"> Add to cart </a>
											</div>
										</div>
										</div>
										</div>
									</div>
									</div>
									<?php } ?>
								</div>
							</div>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>

			
	<div class="third-section" <?php if(!empty($HomePageData[6]["home_content"])) { ?>style="background-image: url(<?php echo HTTP_SLIDER_IMAGES_PATH.'/'.$HomePageData[6]["home_content"]; ?>);"<?php } ?>>
		<video class="background-video" playsinline="playsinline" autoplay muted loop>
			<source src="<?=HTTP_IMG_PATH?>/fog-background.mp4" type="video/mp4">
		</video>
		<div class="container">
			<div class="row align-items-center">
				<div class="col-xl-6">
					<div class="third-part-contain" data-aos="zoom-in">
						<h1 class="title"><?php if(!empty($HomePageData[4]["home_content"])) { echo $HomePageData[4]["home_content"]; } else { ?><span>Are you an</span><span> Artist & Seller?</span><?php } ?></h1>
						<p class="description"><?php if(!empty($HomePageData[5]["home_content"])) { echo $HomePageData[5]["home_content"]; } else { ?>Come Join us in the Dark where Halloween enthusiasts, fans of gore,horror and the macabre congregate to conjure up some Magic. Come Join the Coven!<?php } ?></p>
						<?php if(empty($loggedUser)) { ?>
						<div class="border-gradient "><a href="<?= APPLICATION_URL.'/register'; ?>" class="view-btn btn"><?= $configs["site_join_now"] ?> </a></div>
						<?php } ?>
					</div>
				</div>
				<div class="col-xl-6">
					
					<div class="video-block">
						<div class="video-frame"></div>
						<iframe id="vidblk" width="420" height="380" src="https://player.vimeo.com/video/454886926?autoplay=1&amp;color&amp;autopause=0&amp;loop=0&amp;muted=0&amp;title=0&amp;portrait=0&amp;byline=0#t="></iframe>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php if(!empty($recent_products)) { ?>
		<div class="second-section four-section" data-aos="fade-up" data-aos-duration="3000">
			<div class="container">
				<div class="most-popular">
					<h2 class="heading" data-aos="zoom-in-down"><?php if(!empty($HomePageData[6]["home_content"])) { echo $HomePageData[6]["home_content"]; } else { ?>New Conjurings<?php } ?></h2>
					<div class="owl-carousel two">
					<?php foreach (array_chunk($recent_products, 8) as $group) { ?>					
							<div class="item" data-aos="flip-left">
								<div class="form-row">

									<?php  foreach($group as $favorite_products_key => $favorite_products_val) { $product_picarr = array();
									$price_data = $this->layout()->AbstractModel->Super_Get(T_PROQTY,"color_productid =:PID","fetch",array('warray'=>array('PID'=>$favorite_products_val["product_id"])));
									?>
									<div class="col-xl-3 col-6">
									<div class="item">
										<div class="itmanc-tg" data-href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>">
										<div class="card menu-card">
										<?php if($favorite_products_val[T_CLIENT_VAR."client_bestseller"] == '1') { ?>
											<div class="ribbon-pop"><span>Best Seller</span></div>
										<?php } ?>
										<div class="slider-img">
										<?php if(!empty($favorite_products_val["product_photos"])) {
													$product_picarr = explode(",",$favorite_products_val["product_photos"]); } 
												?>
										<div class="card-img-top">
										<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>">
										<?php if(!empty($favorite_products_val["product_defaultpic"])) { ?> 
														<img class="" src="<?=HTTP_PRODUCT_PIC_PATH?>/thumb/<?= $favorite_products_val["product_defaultpic"] ?>" alt="Card image cap">
													<?php } else {
													if(!empty($favorite_products_val["product_photos"])) { ?>
														<img class="" src="<?=HTTP_PRODUCT_PIC_PATH?>/thumb/<?= $product_picarr[0] ?>" alt="Card image cap">
											<?php } } ?></a>					
															<div class="coven-overlay d-none"></div> </div> 
											<?php if($favorite_products_val["shipping_free"] == '1' && $favorite_products_val[T_CLIENT_VAR."client_country"] == $loggedUser->{T_CLIENT_VAR."client_country"} && $favorite_products_val["product_isdigital"] != '1') { ?>
												<div class="freeship-holder"><div class="freeship-txt">Free Shipping</div></div>
											<?php } else { ?>
												<div class="freeship-holder">&nbsp;</div>
											<?php } ?> 
										</div>
										<div class="card-body">
											<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>" class="card-anctg"><h1 class="card-title"><?= $favorite_products_val["product_title"] ?></h1></a>
											<p class="price-txt"> <span class="mrp-price"> </span> <span>$<?php if($favorite_products_val["product_isdigital"] == '1') { echo $favorite_products_val["product_price"]; } else { echo $price_data["color_price"]; } ?></span> </p>
											<div class="btn-block">
												<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>" class="btn view-btn"> View Detail </a>
												<a href="<?= APPLICATION_URL.'/product/'.slugify($favorite_products_val["product_title"]).'~'.str_replace("=","",base64_encode($favorite_products_val["product_id"])); ?>#cart" class="btn cart-btn"> Add to cart </a>
											</div>
										</div>
										</div>
										</div>
									</div>
									</div>
									<?php } ?>
								</div>
							</div>
						<?php } ?>          
					</div>
				</div>
			</div>
		</div>
	<?php }  ?>

			
	<div class="five-section third-section" <?php if(!empty($HomePageData[8]["home_content"])) { ?>style="background-image: url(<?php echo HTTP_SLIDER_IMAGES_PATH.'/'.$HomePageData[8]["home_content"]; ?>);"<?php } ?>>
		<video class="background-video" playsinline="playsinline" autoplay muted loop>
			<source src="<?=HTTP_IMG_PATH?>/fog-background.mp4" type="video/mp4">
		</video>
		<div class="container">
			<div class="subcribe-letter" data-aos="fade-up" data-aos-anchor-placement="top-bottom">
				<div class="row">
						<div class="col-xl-6">
								<div class="subcribe-block">
									<h2 class="title"> <?php  if(!empty($HomePageData[7]["home_content"])) { echo $HomePageData[7]["home_content"]; } else { ?>Subscribe to the Coven<?php }  ?></h2>
									<hr/>
									<div class="description"><?php if(!empty($HomePageData[8]["home_content"])) { echo $HomePageData[8]["home_content"]; } else { ?>The Collective Cove is a Unique Online Marketplace for Halloween enthusiasts! The Only Place where you can find a Coven of Artists and Creators that specialize in Spooky, Gothic, and Horror themed Dark Arts!  Come conjure up Some Magic and Join the Coven!<?php } ?></div>
								</div>
						</div>
						<div class="col-xl-6">
							<div class="subcribe-form">
								<div class="search" id="">
									<form class="newsletter-form" id="newsletter_form" name="newsletter_form">
										<div class="form-group">
											<label> Your Name * </label>
											<input type="text" class="form-control required" placeholder="" id="newsletter_name" maxlength="200">
										</div>
										<div class="form-group">
											<label> Email * </label>
											<input type="text" class="form-control required email" placeholder="" id="newsletter_email" maxlength="255">
										</div>

									</form>
								</div>
								<div class="border-gradient"><a href="javascript:void(0)" class="view-btn btn subscribe-btn"><?= $configs["site_subscribe_text"] ?></a></div>
							</div>
						</div>
				</div>
			</div>	
		</div>
	</div>

	<!--  -->
	<?php if(!empty($favorite_stores)) { ?>
	<div class="shop-instagram-block">
			<div class="">
					<h1 class="heading"> Featured shops </h1>
					
					<div class="instagram-slider owl-carousel">
						<?php foreach($favorite_stores as $favorite_stores_key => $favorite_stores_val) { ?>
				    		<div class="wicked-shop">
								<a href="<?= APPLICATION_URL.'/shop/'.str_replace(" ","-",$favorite_stores_val['store_name']); ?>"> 
								<div class="wicked-img">									
								<?php if(!empty($favorite_stores_val["store_banner"]) && file_exists(STORE_BANNER_PATH.'/'.$favorite_stores_val["store_banner"])) { ?>
									<img src="<?=HTTP_STORE_BANNER_PATH?>/<?= $favorite_stores_val["store_banner"]; ?>"> 
								<?php } ?><span> <?= $favorite_stores_val["store_name"] ?> </span> 
								</div>
								</a>
								<div class="wicked-card-body">
									<div class="rating-ul">		
										<?php if(!empty($favorite_stores_val["review_date"])) { ?>
										<div class="star-panel" data-rating="<?= $favorite_stores_val["avg_review"]; ?>"></div>
									  <?php } else { ?>
										<div class="star-panel" data-rating="0"></div>
									  <?php } ?>
									</div>
									<div class="wicked-logo">
									<?php if(!empty($favorite_stores_val["store_logo"]) && file_exists(STORE_LOGO_PATH.'/'.$favorite_stores_val["store_logo"])) { ?>
										<img src="<?=HTTP_STORE_LOGO_PATH?>/thumb/<?= $favorite_stores_val["store_logo"] ?>">
									<?php } else { ?> 
										<img src="<?=HTTP_IMG_PATH?>/moon-img.jpg"> 
									<?php } ?>
									</div>
								</div>
							</div>
					    <?php } ?>
					</div>				
			</div>
	</div>
	<?php } ?>