<style type="text/css">
	.tweet-pictg{max-width:100px;}
</style>
<div id="grad" class="animated fadeIn twiterhandler background">

<div class="container">

  

    <div class="logincontainer TextCenter">

          

        <div class="makediv">

        

        	<h2 class="text-center">Provide Your Email Address to Continue</h2> 

        	<hr />

            <div class="clearfix">&nbsp;</div>

            <img src="<?=HTTP_IMG_PATH?>/twitter.png" alt="image" class="d-block mx-auto tweet-pictg" />

            <div class="clearfix">&nbsp;</div>

			<?php echo $this->renderForm($this->form);?>

        </div>

           <div class="clearfix">&nbsp;</div>

       

    </div>

</div>

</div>

<style>

.margin_top_handler_heading{

	margin-top:40px;

}

.align_center{

	margin:0px auto;

}

.makediv{

	margin: 76px;

}

</style>

