<style type="text/css">.media-heading{font-size:12px !important;}.nwlogo{position:absolute;top:0px;height:65px;}
@media (max-width: 767px) {
.navbar-header{background:#000 !important;}
}
</style>
<?

use Zend\Session\Container;

global $notificationMessages;

$notificationData=$newCountData=array();

$session = new Container(ADMIN_AUTH_NAMESPACE);	

$adminData = $session['adminData'];



$notificationData=$this->layout()->AbstractModel->Super_Get(T_NOTIFICATION,"notification_to='1' and notification_readstatus='0' and notification_type != '0'","fetchAll",array('order'=>'notification_date desc'),array('0'=>array(T_CLIENTS,T_CLIENT_VAR.'client_id=notification_by','left',array(T_CLIENT_VAR.'client_name',T_CLIENT_VAR.'client_image'))));






?>

<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">

    

      <div class="navbar-header">

        <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"

          data-toggle="menubar">

          <span class="sr-only">Toggle navigation</span>

          <span class="hamburger-bar"></span>

        </button>

        <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"

          data-toggle="collapse">

          <i class="icon md-more" aria-hidden="true"></i>

        </button>

        <div class="navbar-brand navbar-brand-center navbarbrand_admin site-gridmenu-toggle" onclick="window.location.href='<?php echo ADMIN_APPLICATION_URL?>'">

          <?php /*?><img class="navbar-brand-logo navbarlogo_admin" src="<?php echo HTTP_PROFILE_IMAGES_PATH.'/logo/'.$this->layout()->SITE_CONFIG['site_logo']; ?>" title="Logo"><?php */?>
         <img class="navbar-brand-logo navbarlogo_admin" src="<?php echo HTTP_IMG_PATH.'/transparent_new.gif'; ?>" title="Logo"> 
		 <span class="navbar-brand-text hidden-xs-down"> <img src="<?=HTTP_IMG_PATH?>/new_logo2.png" class="nwlogo" /></span>
         <?php /*?> <span class="navbar-brand-text hidden-xs-down"> Logo</span><?php */?>

        </div>

        

      </div>

    

      <div class="navbar-container container-fluid fluid_admin">

        <!-- Navbar Collapse -->

        <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">

          <!-- Navbar Toolbar -->

          <ul class="nav navbar-toolbar">

            <li class="nav-item hidden-float" id="toggleMenubar">

              <a class="nav-link" data-toggle="menubar" href="#" role="button">

                <i class="icon hamburger hamburger-arrow-left">

                  <span class="sr-only">Toggle menubar</span>

                  <span class="hamburger-bar"></span>

                </i>

              </a>

            </li>

            

            

            

          </ul>

          <!-- End Navbar Toolbar -->

    

          <!-- Navbar Toolbar Right -->

          <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">

            <li class="nav-item dropdown">

              <a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false"

                data-animation="scale-up" role="button">

                <span class="avatar avatar-online">

                  <img src="<?php echo getUserImage($adminData['yurt90w_client_image'],'60')?>" alt="admin" />

                  <i class="admin_i"><?php /*?>Hi, <?php echo $adminData['yurt90w_client_first_name']?><?php */?></i>

                </span>

              </a>

              

              

              

              

              <div class="dropdown-menu" role="menu">

              <a class="dropdown-item" href="<?php echo $this->url('adminprofile')?>" role="menuitem"><i class="icon md-account" aria-hidden="true"></i> Profile</a>

                <a class="dropdown-item" href="<?php echo $this->url('adminprofile',array("tabtype"=>"3"))?>" role="menuitem"><i class="icon md-lock" aria-hidden="true"></i> Password</a>

                

                

                <div class="dropdown-divider" role="presentation"></div>

                <a class="dropdown-item" href="<?php echo $this->url('adminlogout')?>" role="menuitem"><i class="icon md-power" aria-hidden="true"></i> Logout</a>

              </div>

            </li>

           <li class="nav-item dropdown">

              <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" title="Notifications"

                aria-expanded="false" data-animation="scale-up" role="button">

                <i class="icon md-notifications" aria-hidden="true"></i>

                <span class="badge badge-pill badge-danger up"><?= count($notificationData) ?></span>

              </a>

              <div class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">

                <div class="dropdown-menu-header">

                  <h5>NOTIFICATIONS</h5>

                  <?php /*?><span class="badge badge-round badge-danger">New 5</span><?php */?>

                </div>

    

                <div class="list-group">

                  <div data-role="container">

                    <div data-role="content">
                    	
					  <?php foreach($notificationData as $notificationData_key => $notificationData_val) { 
					  	if($notificationData_val["notification_type"] == '1') { $link =  ADMIN_APPLICATION_URL.'/seller-applications'; } else if($notificationData_val["notification_type"] == '2') { $link =  ADMIN_APPLICATION_URL.'/badge-requests'; } else if($notificationData_val["notification_type"] == '5') { $link =  ADMIN_APPLICATION_URL.'/chat/'.str_replace("=","",myurl_encode($notificationData_val["notification_by"])); }  else if($notificationData_val["notification_type"] == '6') { $link =  ADMIN_APPLICATION_URL.'/withdrawal-requests'; }
					  ?>
                      <a class="list-group-item dropdown-item" href="<?= $link ?>" role="menuitem">

                        <div class="media">

                          <div class="pr-10">

                            <i class="icon md-receipt bg-red-600 white icon-circle" aria-hidden="true"></i>

                          </div>

                          <div class="media-body">

                            <h6 class="media-heading">
                            	<?php if($notificationData_val["notification_type"] == '1') { ?>
                                	<?= $notificationData_val[T_CLIENT_VAR.'client_name']." has sent the store approval request." ?>
								<?php } else if($notificationData_val["notification_type"] == '2') { ?>
                                	<?= $notificationData_val[T_CLIENT_VAR.'client_name']." has sent the badge request." ?>
								<?php } else if($notificationData_val["notification_type"] == '5') { ?>
  									<?= $notificationData_val[T_CLIENT_VAR.'client_name']." has sent you a new message." ?>                              	
								<?php } else if($notificationData_val["notification_type"] == '6') { ?>
  									<?= $notificationData_val[T_CLIENT_VAR.'client_name']." has sent the withdrawal request." ?>                              	
								<?php } ?>
                            </h6>

                            <time class="media-meta" datetime="2017-06-12T20:50:48+08:00">5 hours ago</time>

                          </div>

                        </div>

                      </a>					  
                      <?php } /*?><a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">

                        <div class="media">

                          <div class="pr-10">

                            <i class="icon md-account bg-green-600 white icon-circle" aria-hidden="true"></i>

                          </div>

                          <div class="media-body">

                            <h6 class="media-heading">Completed the task</h6>

                            <time class="media-meta" datetime="2017-06-11T18:29:20+08:00">2 days ago</time>

                          </div>

                        </div>

                      </a><?php */?>

                      <?php /*?><a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">

                        <div class="media">

                          <div class="pr-10">

                            <i class="icon md-settings bg-red-600 white icon-circle" aria-hidden="true"></i>

                          </div>

                          <div class="media-body">

                            <h6 class="media-heading">Settings updated</h6>

                            <time class="media-meta" datetime="2017-06-11T14:05:00+08:00">2 days ago</time>

                          </div>

                        </div>

                      </a><?php */?>

                      <?php /*?><a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">

                        <div class="media">

                          <div class="pr-10">

                            <i class="icon md-calendar bg-blue-600 white icon-circle" aria-hidden="true"></i>

                          </div>

                          <div class="media-body">

                            <h6 class="media-heading">Event started</h6>

                            <time class="media-meta" datetime="2017-06-10T13:50:18+08:00">3 days ago</time>

                          </div>

                        </div>

                      </a><?php */?>

                      <?php /*?><a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">

                        <div class="media">

                          <div class="pr-10">

                            <i class="icon md-comment bg-orange-600 white icon-circle" aria-hidden="true"></i>

                          </div>

                          <div class="media-body">

                            <h6 class="media-heading">Message received</h6>

                            <time class="media-meta" datetime="2017-06-10T12:34:48+08:00">3 days ago</time>

                          </div>

                        </div>

                      </a><?php */?>

                    </div>

                  </div>

                </div>

                <div class="dropdown-menu-footer">

                  <?php /*?><a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">

                    <i class="icon md-settings" aria-hidden="true"></i>

                  </a>

                  <a class="dropdown-item" href="javascript:void(0)" role="menuitem">

                    All notifications

                  </a><?php */?>

                </div>

              </div>

            </li>

            

            

          </ul>

          <!-- End Navbar Toolbar Right -->

        </div>

        <!-- End Navbar Collapse -->

    

        

      </div>

    </nav>





<script>

function readnots()

		{

			$.ajax({

				url: baseUrl+'/readnotify',

				success: function(data){

					$('.notify').addClass('hide');

				},

			});

		}

</script> 

