<style>

.customTheme  .input-group-addon{    background: #fff;color: #222;}

a.fileinput-exists{background: #ff7676 !important;color:#fff !important;}

.profileSettingMainPage{min-height:500px;}

.wfull-100{width:100%;}

.btn-file > input{transform: unset !important;}

.location-help-block{
  width: 100%;
  margin-top: .286rem;
  font-size: 80%;
  color: #f44336;
}

</style>

<?php $image = getUserImage($adminData[T_CLIENT_VAR.'client_image'],"300"); ?>

<div class="row profileSettingMainPage">

          <div class="col-lg-3">

            <!-- Page Widget -->

            <div class="card card-shadow text-center">

              <div class="card-block">

                <a class="avatar avatar-lg w-100 " href="javascript:void(0)">

                  <img id="shortImg"  src="<?php  echo getUserImage($adminData[T_CLIENT_VAR.'client_image'],'thumb'); ?>" alt="" class="m-0">

                </a>

                <h4 class="profile-user"><?php  echo ucwords($adminData[T_CLIENT_VAR.'client_name']); ?></h4>

                <p class="profile-job"><?=$adminData[T_CLIENT_VAR.'client_email']?></p>

              </div>

            </div>

            <!-- End Page Widget -->

          </div>



          <div class="col-lg-9">

            <!-- Panel -->

            <div class="panel">
              <div class="panel-body nav-tabs-animate nav-tabs-horizontal" data-plugin="tabs">
                <ul class="nav nav-tabs nav-tabs-line" role="tablist">
                	
                     <li class="nav-item active" role="presentation"><a  class="nav-link <?php if($this->pactivetab=="1"){?>active<? }?>" data-toggle="tab" href="#settings" aria-controls="settings" role="tab" >  <span class=""><?=$this->layout()->translator->translate("profile_txt")?></span></a></li>
                                          
                      <li class="nav-item" role="presentation"><a  class="nav-link <?php if($this->pactivetab=="2"){?>active<? }?>" data-toggle="tab" href="#picture" aria-controls="picture" role="tab" >  <span class=""><?=$this->layout()->translator->translate("picture_txt")?></span></a></li>
            
                      <li class="nav-item" role="presentation"><a  class="nav-link <?php if($this->pactivetab=="3"){?>active<? }?>" data-toggle="tab" href="#password" aria-controls="password" role="tab" >  <span class=""><?=$this->layout()->translator->translate("Change Password")?></span></a></li>
            
                      <li class="nav-item" role="presentation"><a  class="nav-link <?php if($this->pactivetab=="4"){?>active<? }?>" data-toggle="tab" href="#changeemail" aria-controls="changeemail" role="tab" >  <span class=""><?=$this->layout()->translator->translate("Change Email")?></span></a></li>
                </ul>
                

                <div class="tab-content">
                      <div class="tab-pane <?php if($this->pactivetab=="1"){?>active<? }?> Overflow animation-slide-left" id="settings">
                         <form class="form-horizontal form-material profile_form" id="profile_form" action="" method="post" enctype="multipart/form-data" novalidate  autocomplete="off"> 
                            <div class="form-body mt-10">
                            
                            <div class="form-group ">
                                <label class="col-md-12 text-dark"><?=$this->layout()->translator->translate("name_txt")?></label>
                                <div class="row ml-0 mr-0">
                                    <div class="col-md-12" ><?=$this->formElement($form->get('client_name'))?></div>
                                </div>                                
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-12">
                                    <label class="text-dark">Address Info</label>
                                    <?=$this->formElement($form->get('client_address'))?>
                                    <?=$this->formElement($form->get('client_address_lat'))?>
                                    <?=$this->formElement($form->get('client_address_long'))?>
                                    
                                </div>
                            </div>
                            <?=$this->formElement($form->get('post_csrf'))?>
                                 <div class="col-sm-12 Overflow">
                                    <button type="button" id="profile_update_btn" class="btn fcbtn btn-outline btn-info btn-1e"><?=$this->layout()->translator->translate("update_txt")?></button>
                                 </div>
                           </div>
                        </form>
                      </div>
                      
                      <div class="tab-pane <?php if($this->pactivetab=="2"){?>active<? }?> animation-slide-left" id="picture">

                            <form class="form-horizontal form-material">

                            <div class="form-body">

                                <div class="form-group">

                                    <label class="col-sm-12 text-dark pt-20">

                                    <?=$this->layout()->translator->translate("update_profile_txt")?></label>

                                    <div class="col-sm-12">

                                      <div class="fileinput fileinput-new input-grou1p d-table wfull-100" data-provides="fileinput" >

                                        <div class="form-control" data-trigger="fileinput"> <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>

                                        <span class="input-group-addon btn btn-default btn-file d-table-cell w-100"> <span class="fileinput-new"><?=$this->layout()->translator->translate("sel_file_txt")?></span> <span class="fileinput-exists"><?=$this->layout()->translator->translate("change_txt")?></span>

                                        <input type="file" onchange="avatarUploader();"  name="client_image" id="client_image" class="file-upload">

                                        </span> 

                                        <div class="d-table-cell"><a onclick="removefile(this)" class="input-group-addon btn btn-default fileinput-exists  w-100" data-dismiss="fileinput" id="removefiletxt"><?=$this->layout()->translator->translate("remove_txt")?></a>

                                        </div>

                                         </div>

                                    </div>

                                </div>

                                <div class="pr-15 pl-15">

                                <div id="pic-progress" class="progress progress-sm" style="display:none;"><div id="pic-bar" class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div></div>

                                </div>

                            </div>

                            

                            <div class="adminProfileBtn d-none col-sm-12"><button id="up_btn" type="button" class="btn fcbtn btn-outline btn-info btn-1e btn btn-default">Upload</button></div>

                           </form>

                      </div>

            

              <div class="tab-pane animation-slide-left <?php if($this->pactivetab=="3"){?>active<? }?> Overflow" id="password">		

                    <div class="form-group">
                            <form class="form-horizontal form-material profile_form2" action="<?=$this->url('adminpassword')?>" method="post" >
                            <div class="form-body pt-20">

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <?=$this->formRow($form1->get('client_old_password'))?>
                                    </div>
                                 </div>
                                 
                                 <div class="form-group">
                                    <div class="col-md-12">
                                        <?=$this->formRow($form1->get('client_password'))?>
                                    </div>
                                 </div>
                                 
                                 <div class="form-group">
                                    <div class="col-md-12">
                                        <?=$this->formRow($form1->get('client_rpassword'))?>
                                    </div>
                                 </div>
                                  <div class="col-sm-12">
                                    <button type="button" id="change_pass_update_btn" class="btn fcbtn btn-outline btn-info btn-1e"><?=$this->layout()->translator->translate("update_txt")?></button>
                                </div>
                            </div>
                        </form>
                       </div>              
              
              </div>
              
              

              <div class="tab-pane animation-slide-left <?php if($this->pactivetab=="4"){?>active<? }?> Overflow" id="changeemail">

              		

                    		

                            <form class="form-horizontal form-material " action="<?=$this->url('admin_profile_change_email')?>" method="post" id="emailForm">

                                <div class="form-body pt-20">

                                    <div class="form-group">

                                    	<label for="client_email_password" class="col-md-12">Email Address</label>

                                        <div class="col-md-12">

                                        	

                                            <?=$this->formElement($form2->get('client_email'))?>

                                        </div>

                                     </div>

                                        <div class="form-group">

                                            

                                            <div class="col-md-12">

                                                <?=$this->formRow($form2->get('client_email_password'))?>

                                            </div>     

                                         </div>                               

                                     

                                     

                                      <div class="col-sm-12">

                                        <button type="button" id="change_email_update_btn" class="btn fcbtn btn-outline btn-info btn-1e"><?=$this->layout()->translator->translate("update_txt")?></button>

                                    </div>

                                </div>

                               </form>

                       </div>

              

              

              </div>

              

         

                

              </div>

            </div>

            <!-- End Panel -->

          </div>

 </div>

   

   



<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?= GOOGLE_MAP_API_KEY ?>&libraries=places&sensor=false"></script>  

<script>
function initialize() {
  var input = document.getElementById('client_address');
  $(input).attr("placeholder","");
   var options = {
       types: ['geocode'],  // or '(cities)' if that's what you want?
       //componentRestrictions: {country: countryCode}
     };
  var autocomplete = new google.maps.places.Autocomplete(input,options);
  if(typeof pagetag=='undefined'){
    $('#client_address').attr("placeholder","Address");
  }
  google.maps.event.addListener(autocomplete, 'place_changed', function () {
      var place = autocomplete.getPlace();
      $('.location-help-block').remove();
      document.getElementById('client_address_lat').value = place.geometry.location.lat();
      document.getElementById('client_address_long').value = place.geometry.location.lng();
  });
}

if(document.getElementById('client_address')){
   google.maps.event.addDomListener(window, 'load', initialize);
}


$(document).on("change","#client_image",function(e){
	$('.adminProfileBtn').removeClass('d-none');
});


$(document).ready(function(e) {
  $('#profile_update_btn').on('click', function(){
    $('#profile_form').validate({
        rules:{
            client_name:{
              required:true,
            },
            client_address:{
              required:true,
            },
        },
        errorPlacement:function(error,element){
            error.insertAfter(element);
        },
      
    });

    if($('#profile_form').valid())
    {
      if($('#client_address_lat').val()=='' || $('#client_address_long').val()==''){
        if($('#client_address').parent().next('.location-help-block').length==0){
          $('.location-help-block').remove();
          $('#client_address').parent().append("<span class='location-help-block'>We are having a hard time locating your address. Please try again.</span>");
        }
        return false;
      }
      // passwordEncrypt();
      $('#profile_form').submit();

    } else {
      // alert('Please check the form and complete it.');
    }

  });

  /* start logged in - change password */
  $('#change_pass_update_btn').on('click', function(){
    $('.profile_form2').validate({
      rules:{
        client_old_password:{required:true,minlength:8},//minlength:8,maxlength:30,
        client_password:{required:true,minlength:8},
        client_rpassword:{required:true,minlength:8,equalTo:'#client_password'}, 
      },
      messages:{
           
      },
    }); 

    if($('.profile_form2').valid())
    {
      $('.location-help-block').remove();
      if($('#client_old_password').val()==$('#client_password').val()){
        if($('#client_password').parent().next('.location-help-block').length==0){          
          $('#client_password').parent().append("<span for='client_password' class='location-help-block'>Current password and new password can not be same.</span>");

        }
        return false;
      }
      passwordEncrypt();
      $('.profile_form2').submit();

    } else {
      // alert('Please check the form and complete it.');
    }

  }); 
  /* end logged in - change password */

  /* start logged in - change email */
  $('#change_email_update_btn').on('click', function(){
    $('#emailForm').validate({
      rules:{
        client_email:{required:true},
        client_email_password:{required:true,minlength:8},
      },
      messages:{
           
      },
    }); 

    if($('#emailForm').valid())
    {
      passwordEncrypt();
      $('#emailForm').submit();

    } else {
      // alert('Please check the form and complete it.');
    }

  }); 
  /* end logged in - change email */



  
});

</script>

    