<?php if(TEST==true){ ?>
<div class="error_elemenet">
    <div class="container">
    <div class="error_body">
        
        <div class="error-sec" style="background-color: rgba(255,255,255,0.5);padding:20px;">
            <h3 class="heading">404! WHOOPS</h3>
            <p class="description">    
            <h1><?php echo 'An error occurred'; ?></h1>
            <h2><?php echo $this->message; ?></h2>

            <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

            <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
            <hr/>
            <h2><?php echo 'Additional information' ?>:</h2>
            <h3><?php echo get_class($this->exception); ?></h3>
            <dl>
                <dt><?php echo 'File' ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                </dd>
                <!-- <dt><?php //echo Message ?>:</dt> -->
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                </dd>
                <dt><?php echo 'Stack trace' ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                </dd>
            </dl>
            <?php
                $e = $this->exception->getPrevious();
                if ($e) :
            ?>
            <hr/>
            <h2><?php echo 'Previous exceptions' ?>:</h2>
            <ul class="unstyled">
                <?php while($e) : ?>
                <li>
                    <h3><?php echo get_class($e); ?></h3>
                    <dl>
                        <dt><?php echo 'File' ?>:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                        </dd>
                        <dt><?php echo 'Message' ?>:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                        </dd>
                        <dt><?php echo 'Stack trace' ?>:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php
                    $e = $e->getPrevious();
                    endwhile;
                ?>
            </ul>
            <?php endif; ?>

            <?php else: ?>

            <h3><?php echo 'No Exception available' ?></h3>

            <p><?php echo $this->exception->getMessage() ?></p>

            <?php endif ?>

            <?php endif ?>
            </p>
        </div>
    </div>
    </div>
</div>            

<?php } else { ?>

<div class="error_elemenet">
    <div class="container">
    <div class="error_body">
        <div class="error-sec">
            <h3 class="heading">404! WHOOPS</h3>
            <p class="description">We are sorry but the Page you are looking for doesn't exist or an other error occured. </p>
            <a href="<?php echo SITE_HTTP_URL?>" class="homelink">Go to HOME PAGE</a>
        </div>
    </div>
    </div>
</div>

<?php } ?>