<!--------------------------Register As a Member------------------------------------->
<?php
$term_data = '';
if(isset($page_content['page_content_'.$_COOKIE['currentLang']])){
  $term_data = $page_content['page_content_'.$_COOKIE['currentLang']];
}
?>

<div class="commen-sec-images">
        <h2 class="heading">Register as a Member</h2>
</div>

<div class="login_page signup-page">
      <div class="container">
        <div class="login register_member ">
          <div class="register_member_1 contact-form comman-form">
            <h2 class="heading">Enter your Information</h2>
            <form id="sm_member_registration_form" action="<?php echo $this->url('front_register_member'); ?>" method="post" class="profile_form" enctype="multipart/form-data" >
              <div class="form-row">
                  <div class="col-xl-6 col-lg-6 col-sm-6"> 
                    <div class="form-group"><?php echo $this->formElement($form->get('client_name'))?> </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6">
                    <div class="form-group"><?php echo $this->formElement($form->get('client_email'))?> </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6">
                    <div class="form-group"><?php echo $this->formElement($form->get('client_company_name'))?></div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6">
                    <div class="form-group">
                      <?php echo $this->formElement($form->get('client_company_address'))?>
                      <?php echo $this->formElement($form->get('client_address_lat'))?>
                      <?php echo $this->formElement($form->get('client_address_long'))?>
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6">
                    <div class="form-group"><?php echo $this->formElement($form->get('client_phone'))?></div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6">
                    <div class="form-group"><?php echo $this->formElement($form->get('client_website_url'))?></div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6"> 
                    <div class="form-group"> <?php echo $this->formElement($form->get('client_password'))?></div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-sm-6"> 
                    <div class="form-group"> <?php echo $this->formElement($form->get('client_rpassword'))?></div>
                  </div>
                    <?php echo $this->formElement($form->get('post_csrf'))?>
              </div>

                  <div class="section-term-data">
                    <div class="chaeck-data">
                            <!-- <div class="check-boxs">
                                  <div class="checks custom-checks">
                                      <label class="checkbox"></span> 
                                          <input type="checkbox" name="" value="">
                                          <span class="checkmark"></span>
                                      </label>
                                  </div>
                            </div> -->
                          <p class="description">Terms and Conditions <span>: <a href="<?php echo $this->url('front_acceptableusepolicy'); ?>" target="_blank">Acceptable Use Policy</a>, <a href="<?php echo $this->url('front_termsofwebsiteuse'); ?>" target="_blank">Terms of Website Use</a></span> and <span><a href="<?php echo $this->url('front_termsandconditionsforclubs'); ?>" target="_blank">Terms and Conditions for Clubs</a>.</span></p>
                    </div>
                  </div>

                  <div class="term-condtion-sec-register">
                    <div class="term-data-sec">
                      <h5 class="titles"><span>Terms and Conditions for Sports Mentor TV</span></h5>
                    </div>
                    <div class="data-sec-part ">
                      <?php echo $term_data; ?>

                      <div class="check-data-part check-some-data">
                          <div class="check-boxs">
                                <div class="checks custom-checks">
                                    <label class="checkbox"></span> 
                                        <!-- <input type="checkbox" name="" value=""> -->
                                        <?php //echo $this->formElement($form->get('client_accepted_terms'))?>
                                        <input type="checkbox" name="client_accepted_terms" id="client_accepted_terms" value="1" required>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                          </div>
                          <div class="">
                            <p class="description">
                              <label for="client_accepted_terms">I have read and accept in conjunction with all other terms and conditions Sports Mentor TV  holds.</label>
                              <span for="client_accepted_terms" id="errorclient_accepted_terms" class="help-block "></span>
                            </p>
                          </div>
                      </div>
                    </div>
                  </div>
                
                  <button type="button" class="btn submit-btns get-started-1" id="startedbtn">Submit</button>

            </form>

          </div>
        </div>
      </div>
</div>

<script>
var isCaptcha = 1;
var isSubmit = 1;

/*$(document).ready(function(){
  $('#startedbtn').on('click', function(){
    $(".profile_form").validate().element("#client_name");
    $(".profile_form").validate().element("#client_email");
    $(".profile_form").validate().element("#client_company_name");
    $(".profile_form").validate().element("#client_company_address");
    $(".profile_form").validate().element("#client_phone");
    $(".profile_form").validate().element("#client_website_url");
    $(".profile_form").validate().element("#client_hourly_rate");
    $(".profile_form").validate().element("#client_password");
    $(".profile_form").validate().element("#client_rpassword");
    $(".profile_form").validate().element("#client_accepted_terms");

    var client_name = $('#client_name').val();
    var client_email = $('#client_email').val();
    var client_company_name = $('#client_company_name').val();
    var client_company_address = $('#client_company_address').val();
    var client_phone = $('#client_phone').val();
    var client_website_url = $('#client_website_url').val();
    var client_hourly_rate = $('#client_hourly_rate').val();
    var client_password = $('#client_password').val();
    var client_rpassword = $('#client_rpassword').val();

    if(client_name!='' && client_email!='' && client_company_name!='' && client_company_address!='' && client_phone!='' && client_website_url!='' && client_hourly_rate!='' && client_password!='' && client_rpassword!=''){
      var is_chk = $('#client_accepted_terms').prop("checked");
      if(is_chk == false){
        alert('Please read and accept terms and conditions.');
      } else {
        $('#i-recaptcha').submit();
      }
    }
  });

});*/
</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwBN9L602wvTjN55p7bQ0NpaXJ6qOHlWc&libraries=places&sensor=false"></script> 

<script>
$(document).ready(function(){

  $("#client_phone").inputmask("+99 999 999 9999", {
      onKeyValidation: function (key, result) {
      
    }
  });

  $('form,input,select,textarea').attr('autocomplete', 'off');  
  
});
</script>

<script src="https://www.google.com/recaptcha/api.js?render=<?php echo $this->site_configs['recaptcha_sitekey']?>"></script>
<script>
var interval = setInterval(function(){
  if(window.grecaptcha){
    grecaptcha.ready(function() {
        grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
          $('#sm_member_registration_form').prepend('<input type="hidden" id="hiddenGRecaptchaResponse" name="g-recaptcha-response" value="' + token + '">');
        });
    });
  clearInterval(interval);
  }
}, 100);


$('#startedbtn').on('click',function(){
  grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
    $('#hiddenGRecaptchaResponse').remove();
    $('#sm_member_registration_form').prepend('<input type="hidden" id="hiddenGRecaptchaResponse" name="g-recaptcha-response" value="' + token + '">');

    var intervalScroll = setInterval(function(){
        $(".data-sec-part").mCustomScrollbar("scrollTo","bottom");
        clearInterval(intervalScroll);
    },100);

    $('#sm_member_registration_form').validate({
        ignore:'',
        rules:{
            client_name:{
                required:true,
            },
            client_email:{
                required:true,
            },
            client_company_name:{
                required:true,
            },
            client_company_address:{
                required:true,
            },
            client_phone:{
                required:true,
            },
            client_website_url:{
                required:true,
            },
            client_password: {
                minlength: 8,
                notDefaultText: true
            },
            client_rpassword: {
                equalTo: '#client_password',
                maxlength: 12
            },
            client_accepted_terms:{
                required:true,
            },
        },
        messages:{
                hiddenGRecaptchaResponse:{
                required:"Please check captcha",
            }
        },
        errorPlacement:function(error,element){
            error.insertAfter(element);
    },
      
    });

    if($('#sm_member_registration_form').valid())
    {
      if($('#client_address_lat').val()=='' || $('#client_address_long').val()==''){
        if($('#client_company_address').parent().next('.location-help-block').length==0){
          $('.location-help-block').remove();
          $('#client_company_address').parent().append("<span class='location-help-block'>We are having a hard time locating your address. Please try again.</span>");
        }
        return false;
      }
      passwordEncrypt();
      $('#sm_member_registration_form').submit();

    } else {
      // alert('Please check the form and complete it.');
    } 

  });

  // $("#sm_member_registration_form").validate().element("#client_name");

});
</script>