<div class="comman-section">
  <div class="container">
    <div class="common-heading">
      <h2 class="heading">Forgot Password</h2>
    </div>
  </div>	
</div>



<div class="login_page forgot-page">
  <div class="container">
    <div class="login">


      <div class="login-signup-form ">

        <div class="right-side comman-form">
           
              <form id="sm_forgot_password_form" action="<?php echo $this->url('front_forgotpassword'); ?>" method="post" class="login_form">
                <h2 class="forgot-heading">Find Your Account</h2>
                
                <p class="forgot-content">Please enter your email address below and we will send you information to change your password.</p>
                <div class="form-group"> <?php echo $this->formElement($form->get('client_email'))?> </div>
                
                <?php echo $this->formElement($form->get('post_csrf'))?>
                <div class="border-gradient">
                  <button type="button" class="btn view-btn send-btn" name="bttnsubmit" id="startedbtn">Submit</button>
                </div>
                <p class="forgot-text">Have an account? <span><a href="<?php echo $this->url('front_login');?>" class=""> Log In </a></span></p>

               
              </form>




          </div>
          <!------------- right side -------------->
      </div>

    </div>
    <!-- login -->
  </div>
</div>


<? /*
<div class="login_page forgot-password">
  <div class="container">
    <div class="login">
      <h4 class="heading">Forgot password</h4>
      <div class="login_section comman-form">
      <div class="login_data">
        <form id="sm_forgot_password_form" action="<?php echo $this->url('front_forgotpassword'); ?>" method="post" class="login_form">
          <h2 class="heading">Find Your Account</h2>
          <p class="forgot-text">Please enter your email address below and we will send you information to change your password.</p>
          <div class="Overflow">
            <div class="form-group"> <?php echo $this->formElement($form->get('client_email'))?> </div>
          </div>
          
          <?php echo $this->formElement($form->get('post_csrf'))?>
          <div class="text-center">
            <button type="button" class="btn send-btn" name="bttnsubmit" id="startedbtn">Submit</button>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
*/ ?>


<script>
var isCaptcha=1;
</script>

<script type="text/javascript">
$(document).ready(function(){
  $('form,input,select,textarea').attr('autocomplete', 'off');  
});
</script>

<script src="https://www.google.com/recaptcha/api.js?render=<?php echo $this->site_configs['recaptcha_sitekey']?>"></script>
<script>
var interval = setInterval(function(){
  if(window.grecaptcha){
    grecaptcha.ready(function() {
        grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
          $('#sm_forgot_password_form').prepend('<input type="hidden" id="hiddenGRecaptchaResponse" name="g-recaptcha-response" value="' + token + '">');
        });
    });
  clearInterval(interval);
  }
}, 100);

$('#startedbtn').on('click',function(){
  grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
    $('#hiddenGRecaptchaResponse').remove();
    $('#sm_forgot_password_form').prepend('<input type="hidden" id="hiddenGRecaptchaResponse" name="g-recaptcha-response" value="' + token + '">');

    $('#sm_forgot_password_form').validate({
        ignore:'',
        rules:{
            client_email:{
                required:true,
            },
        },
        messages:{
                hiddenGRecaptchaResponse:{
                required:"Please check captcha",
            }
        },
        errorPlacement:function(error,element){
            error.insertAfter(element);
        },
      
    });

    if($('#sm_forgot_password_form').valid())
    {
      // passwordEncrypt();
      $('#sm_forgot_password_form').submit();

    } else {
      // alert('Please check the form and complete it.');
    }

  });

  // $("#sm_forgot_password_form").validate().element("#client_name"); 

});
</script>