<div class="comman-section">
  <div class="container">
    <div class="common-heading">
      <h2 class="heading">Reset Password</h2>
    </div>
  </div>	
</div>
<div class="login_page forgot-page">
  <div class="container">
    <div class="login">

      <div class="login-signup-form ">
          <!------------ left side ------------------>
          <div class="right-side comman-form">
           
              <form id="sm_reset_password_form" action="<?php echo $this->url('front_resetpassword', array('key'=>$key)); ?>" method="post" class="profile_form register_form" enctype="multipart/form-data">
          <div class="Overflow">
            <div class="form-group"> <?php echo $this->formElement($resetForm->get('client_password'))?> </div>
            <div class="form-group"> <?php echo $this->formElement($resetForm->get('client_rpassword'))?> </div>         
            <div class="text-center">
              <?php echo $this->formElement($resetForm->get('post_csrf'))?>
              <div class="border-gradient">
              <button type="button" class="btn submit-btns view-btn get-started" name="bttnsubmit" id="startedbtn">Submit</button>
              </div>
            </div>
        </form>




          </div>
          <!------------- right side -------------->
      </div>

    </div>
    <!-- login -->
  </div>
</div>
<script>
var isCaptcha=1;
</script>

<script type="text/javascript">
$(document).ready(function(){
  $('form,input,select,textarea').attr('autocomplete', 'off');  
});
</script>

<script src="https://www.google.com/recaptcha/api.js?render=<?php echo $this->site_configs['recaptcha_sitekey']?>"></script>
<script>
var interval = setInterval(function(){
  if(window.grecaptcha){
    grecaptcha.ready(function() {
        grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
          $('#sm_reset_password_form').prepend('<input type="hidden" id="hiddenGRecaptchaResponse" name="g-recaptcha-response" value="' + token + '">');
        });
    });
  clearInterval(interval);
  }
}, 100);


$('#startedbtn').on('click',function(){
  grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
    $('#hiddenGRecaptchaResponse').remove();
    $('#sm_reset_password_form').prepend('<input type="hidden" id="hiddenGRecaptchaResponse" name="g-recaptcha-response" value="' + token + '">');

    $('#sm_reset_password_form').validate({
        ignore:'',
        rules:{
            client_password: {
                minlength: 8,
                notDefaultText: true
            },
            client_rpassword: {
                equalTo: '#client_password',
                minlength: 8,
            },
        },
        messages:{
                hiddenGRecaptchaResponse:{
                required:"Please check captcha",
            }
        },
        errorPlacement:function(error,element){
            error.insertAfter(element);
        },
    });

    if($('#sm_reset_password_form').valid())
    {
      passwordEncrypt();
      $('#sm_reset_password_form').submit();

    } else {
      // alert('Please check the form and complete it.');
    }

  });

  // $("#sm_reset_password_form").validate().element("#client_name"); 

});
</script>