<?php if(!empty($message_record)) { foreach($message_record as $message_record_key => $message_record_val) { if($message_record_val["chat_by"] != $loggedUser->{T_CLIENT_VAR.'client_id'}) { ?>
                            <div class="left-box msgcommon-panel" data-id="<?= str_replace("=","",base64_encode($message_record_val["chat_id"])); ?>">
                                <div class="avatar">
                                <?php if(!empty($message_record_val[T_CLIENT_VAR.'client_image'])) { ?>
                                	<img src="<?= HTTP_PROFILE_IMAGES_PATH.'/60/'.$message_record_val[T_CLIENT_VAR."client_image"]; ?>">
                                <?php } else { ?>
                                	<img src="<?= HTTP_PROFILE_IMAGES_PATH.'/160/default.png'; ?>" />
								<?php } ?>
                                </div>
                                <div class="text_wrapper">
                                    <div class="message-content">
                                      <div class="text"><?= nl2br($message_record_val["chat_text"]); ?> </div>
                                    </div>
                                    <div class="dates"><?= time_elapsed_str($message_record_val["chat_date"]); ?></div>
                                </div>
                            </div>
                            <?php } else { ?>
                            <div class="right-box msgcommon-panel" data-id="<?= str_replace("=","",base64_encode($message_record_val["chat_id"])); ?>">     
                                <div class="text_wrapper">
                                  <div class="message-content">
                                    <div class="text"><?= nl2br($message_record_val["chat_text"]); ?>  </div>
                                  </div>
                                  <div class="dates"><?= time_elapsed_str($message_record_val["chat_date"]); ?></div>
                                </div>
                                <!-- <div class="avatar"><img src="<?=HTTP_IMG_PATH?>/user-img.jpg"></div> -->
                            </div>
                            <?php } } } ?>