<?php
  $loggedusermail = $this->loggedUser->yurt90w_client_email;
?>
<style>
.rgt_btn{
  background-color: #ab191a;
  padding: 0px;
  width: 197px;
  height: 54px;
  line-height: 54px;
  border-radius: 0px;
  font-size: 18px;
  color: #fff !important;
  border: none;
  margin: 10px auto 0px;
}
.btn-outline-secondary{
  background-color: #ab191a !important;
}
.commen-sec-images{padding-top:20px;}
.menu-itemz > li > a{font-size:22px !important;}
</style>

<div class="commen-sec-images">
    <h2 class="heading">Account Settings</h2>
</div>

<!-------------------------- after login nav bar --------------------------------->

<div class="profile-header d-lg-block d-none">
  <div class="container">
    <nav class="navbar navbar-expand-lg p-0">
    
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav nav-active m-auto menu-itemz">
          <li class="nav-item">
            <a class="nav-link active" href="<?php echo $this->url('front_profile'); ?>"> Account Settings</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="#">Favorites Videos  </a>
          </li>    
          <li class="nav-item">
            <a class="nav-link" href="#"> Recently viewed videos </a>
          </li>    
          <li class="nav-item">
            <a class="nav-link" href="#">Other Videos of Interested    </a>
          </li>    
          <li class="nav-item">
            <a class="nav-link" href="#">Following Members </a>
          </li>    
        </ul>
      </div>
    </nav>
  </div>
</div>

<!-------------------------------------------------------------------------------------------->


<div class="profile_page comman-bg comman-btmspace">
  <div class="container">
   
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link <?php if($active_tabid=='1'){ echo 'active'; } ?>" href="#profile" role="tab" data-toggle="tab">Account Settings </a>
    </li>
    <li class="nav-item">
      <a class="nav-link <?php if($active_tabid=='2'){ echo 'active'; } ?> last-nav" href="#change" role="tab" data-toggle="tab">Change Password</a>
    </li>
  </ul>

     <h1 class="heading headpara-tg" id="tabPageTitle"><?php echo $tabPageTitle; ?></h1>

    <div class="row form-section m-0">
      <div class="left-side-block">
        <div class="tab-content comman-form">
          <div role="tabpanel" class="tab-pane fade <?php if($active_tabid=='1'){ echo 'show active'; } ?>" id="profile">
          <form id="user_profile_form" action="<?php echo $this->url('front_profile'); ?>/1" method="post" class="profile_form" enctype="multipart/form-data">
            
            <div class="form-group">
              <label for="client_name"> Full Name </label>
              <?php echo $this->formElement($form->get('client_name'))?>
            </div>
            
            <div class="form-group">
              <label for="client_email">Email Address </label>
              <?php echo $this->formElement($form->get('client_email'))?>
            </div>
            
            <div class="form-group">
              <label for="client_email">Location </label>
              <?php echo $this->formElement($form->get('client_address'))?>
            </div>
            
            <div class="form-group">
              <label for="client_email">Location </label>
              <?php echo $this->formElement($form->get('client_gender'))?>
            </div>

            <div class="form-group">
              <label for="client_email">Password <small>(Required in case of changing email)</small></label>
              <?php echo $this->formElement($form->get('client_email_password'))?>
            </div>

            <?php echo $this->formElement($form->get('post_csrf'))?>

            <?php echo $this->formElement($form->get('startedbtn'))?>
          </form>
          <!-- <div class="clearfix">&nbsp;</div> -->
        </div>
        <!----------------------------- profile ---------------------------------->

        <div role="tabpanel" class="tab-pane fade <?php if($active_tabid=='2'){ echo 'show active'; } ?>" id="change">
          <form action="<?php echo $this->url('front_profile'); ?>/2" method="post" class="user_password_form" enctype="multipart/form-data">
            
            <div class="form-group">
              <label for="client_old_password">Old Password </label>
              <?php echo $this->formElement($form1->get('client_old_password'))?>
            </div>

            <div class="form-group">
              <label for="client_password">New Password </label>
              <?php echo $this->formElement($form1->get('client_password'))?>
            </div>
            
            <div class="form-group">
              <label for="client_rpassword">Retype New Password</label>
              <?php echo $this->formElement($form1->get('client_rpassword'))?>
            </div>

            <?php echo $this->formElement($form1->get('password_csrf'))?>
            <?php echo $this->formElement($form1->get('btnchpasswordsubmit'))?>
          </form>

        </div>
        <!-------------------------------- change passwrod -------------------------------------->
      </div>
    </div>
    
      <div class="right-side-block">


        <!-- start image -->

        <!-- <div class="change-image fileinput fileinput-new" data-provides="fileinput" style="width:100%;text-align:center;">

          <div class="fileinput-new thumbnail update_logo" style="max-width:200px;max-height:200px;float:none;">
            <img src="<? //=getUserImage($this->loggedUser->yurt90w_client_image,"60")?>" alt="" class="img-circle"/> 
          </div>

          <div class="fileinput-preview fileinput-exists thumbnail" style="max-width:200px;max-height:200px;float:none;"> </div>

          <div style="margin-top:0px;"> 
            <span class=" btn-file btn update_button"> 
              <span class="change-btn btn fileinput-new"> Change </span> 
              <span class="change-btn btn fileinput-exists"> Change </span>

              <?php //echo $this->formElement($form->get('client_image'))?>

            </span> 
            <a href="#" class="change-btn btn btn-xs btn-danger default fileinput-exists update_button" data-dismiss="fileinput" style="vertical-align:top;" id="filedismiss">Remove </a> 
          </div>

        </div> -->


        <div class="change-image updates">
          <form action="<?php echo $this->url('front_updateprofileimage'); ?>" method="post" class="profile_img_form" enctype="multipart/form-data">
            <input type="hidden" name="imageCordinates" id="imageCordinates" value="" autocomplete="off">
            <div class="fileinput fileinput-new" data-provides="fileinput" style="width:200px;margin:0px auto;text-align: center;display: block;">

              <div class="fileinput-new thumbnail update_logo" style="max-width:200px;max-height:200px;"> 
                <?php if(isset($this->loggedUser->yurt90w_client_image) and !empty($this->loggedUser->yurt90w_client_image)){
                  $user_img = getUserImage($this->loggedUser->yurt90w_client_image,"206x137");
                } else {
                  $user_img = APPLICATION_URL.'/avatars/206x137/default.png';
                }
                ?>
                <img src="<?php echo $user_img; ?>" alt="" class="img-circle" width="200" /> 
              </div>

              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width:200px;max-height:200px;"> </div>

              <div style="margin-top:0px;"> 
                <span class="rgt_btn btn-file btn btn-outline-secondary update_button"> 
                  <span class="fileinput-new"> Change Photo </span> 
                  <span class="fileinput-exists"> Change Photo </span>

                 <?php echo $this->formElement($form->get('client_image'))?>

                 <?php echo $this->formElement($form->get('post_csrf'))?>

                <!-- </span> <a href="#" class="rgt_btn btn btn-xs btn-danger default fileinput-exists update_button" data-dismiss="fileinput" style="vertical-align:top" id="filedismiss">Remove Photo </a>  -->
              </div>

            </div>
          </form>

          </div>


        <!-- end image -->


          <!-- <div class="change-image">
            <div class="user-imgs">  <img src="<?=HTTP_IMG_PATH?>/user-img.jpg" alt="front">  </div>
            <a class="change-btn btn"> Change Photo </a>
          </div> -->
      </div>
    </div>


  </div>
</div>

<div class="modal fade" data-backdrop="static" id="changeImg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Select photo area and press save button</h5>
            </div>
            <div class="modal-body">
                <div id="cropimage_block" class="text-center">
                <center>
                    <div class="cropping_area text-center"><img src="" class="img-responsive" id="targetimg" /></div>
                </center>
                    <button type="button" class="upload_btn mt-5 btn submit-btn default_btn" id="SubmitForm">Save</button>
                    <button type="button" class="btn btn-secondary mt-5 cancel_btn" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>






<script type="text/javascript">
var isSubmit=1;

$(document).ready(function(){
    $('form,input,select,textarea').attr('autocomplete', 'off');

    $('#changeImg').on('hidden.bs.modal', function (e) {
      // do something...
      $('#client_image').val('');
    });

    $(document).on("change","#client_image",function(e){
    // $('#client_image').change(function (e) { 
      var files = $(this)[0].files[0];
      var file_size = bytesToMBSize(files.size);
      var Ext = files.name.split('.');
      Ext = Ext.pop();
      var extension_array = ['jpg','jpeg','png','JPG','JPEG','PNG'];

      $('.fileinput .thumbnail').css("display", "inline-block");
      $('.fileinput div.fileinput-exists').css("display", "none");

      if(($.inArray(Ext, extension_array)<0)){ 
        swal({title:"File Extension",text:"Please select valid file",type:"error",timer:3000,showConfirmButton:false });

      } else {
        // alert('called next readURL_modal function');
        if(file_size <= 10){
          readURL_modal(this);
        } else {
          showAppAlert('Error!!','You can upload a photo upto 10 MB in size.','error');
        }
      }
    });

    function readURL_modal(input){
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        $('.cropping_area').html('');
        reader.onload = function (e) {
            var data = '<img src="'+e.target.result+'" class="img-fluid" id="targetimg" />';
            $('.cropping_area').html(data);
            $('#changeImg').modal('show');
            $('#cropimage_block').show();
        }
        reader.readAsDataURL(input.files[0]);
        // $('#client_image').val('');
        $('.cropped_image').hide();
        setTimeout(function () {  
          jCrop(); 
        }, 500);
      }
    }

    function jCrop(){
      var screenImage = $('#cropimage_block').find('#targetimg');
      var theImage = new Image();
      theImage.src = screenImage.attr("src");
      var imageWidth = theImage.width;
      var imageHeight = theImage.height;
      var cropWidth = 206;
      var cropHeight = 137;
      $('#targetimg').Jcrop({
          bgFade: true,
          setSelect: [0,0,cropWidth,cropHeight],
          animateTo : [0,0,cropWidth,cropHeight],
          aspectRatio: 3/2,
          boxWidth: 800,   
          boxHeight: 600, 
          trueSize: [imageWidth,imageHeight],
          allowResize : true,
          minSize: [206,137],
          maxSize: [4500,3000],
          allowSelect : true,
          onSelect: function(c){
            // console.log(c);
            var create_cordinates = '{"cordinates":[{"X":"'+c.x+'"},{"Y":"'+c.y+'"},{"W":"'+c.w+'"},{"H":"'+c.h+'"}]}';
            $('input[name="imageCordinates"]').val(create_cordinates);
          }    
      }); 
    }


    $('#SubmitForm').on('click', function(){
      $('#changeImg').modal('hide');

      $.blockUI({
          css: {
              border: 'none',
              padding: '5px',
              width: '24%',
              left: '39%',
              color: '#ffffff',
              border: '1px solid #424445',
              backgroundColor: '#AB191A',
              'z-index': '999999999999999999999999999',
              opacity: .9,
              color: '#fff',
          },
          message: "<div class='Loader'><div class='Text' style='letter-spacing: 2px;'>Just a moment</div></div>",
      });

      var post_csrf = $('.profile_img_form input[name=post_csrf]').val();
      var imageCordinates = $('input[name="imageCordinates"]').val();
      var files = $('#client_image')[0].files[0];
      var fd = new FormData();
      fd.append('client_image',files);
      fd.append('post_csrf',post_csrf);
      fd.append('cordinates',imageCordinates);
      fd.append('uploadImageType','mainprofile');
      $.ajax({
          url: "<?php echo $this->url('front_updateprofileimage'); ?>",
          type: 'post',
          data: fd,
          dataType: "json",
          contentType: false,
          processData: false,
          success: function(response){
              $.unblockUI();
              if(response.status == 200){
                  if(response.data.image!=''){
                    var src = "<?php echo APPLICATION_URL.'/avatars/206x137/'?>" + response.data.image;
                    $('.fileinput div.fileinput-exists img').attr('src', src);
                    $('.fileinput .thumbnail img').attr('src', src);

                    $('.fileinput .thumbnail').css("display", "inline-block");
                    $('.fileinput div.fileinput-exists').css("display", "none");

                    $('#header_profile_img').attr("src", "<?php echo APPLICATION_URL.'/avatars/200/'?>"+response.data.image);

                    $('.update_button > span.fileinput-new').text('Change Photo');
                    $('.update_button > span.fileinput-exists').text('Change Photo');
                    showAppAlert('Success!!',response.message,'success');
                  }

              } else {
                  $('.update_button > span.fileinput-new').text('Change Photo');
                  $('.update_button > span.fileinput-exists').text('Change Photo');
                  showAppAlert('Error!!',response.message,'error');
              }
          
              /* reset file elements at the end */
              $('#client_image').val('');

          },
      });

    });

    /*$("#client_image").on('change', function(){
        var fd = new FormData();
        var files = $('#client_image')[0].files[0];
        var file_size = bytesToMBSize(files.size);
        // console.log(files.size);
        // console.log(' MB:'+bytesToMBSize(files.size));
        var post_csrf = $('.profile_img_form input[name=post_csrf]').val();
        $('.fileinput .thumbnail').css("display", "inline-block");
        $('.fileinput div.fileinput-exists').css("display", "none");

        $('.update_button > span.fileinput-new').text('Changing Photo...');
        $('.update_button > span.fileinput-exists').text('Changing Photo...');

        if(file_size <= 10){
          fd.append('client_image',files);
          fd.append('post_csrf',post_csrf);
          $.ajax({
              url: "<?php //echo $this->url('front_updateprofileimage'); ?>",
              type: 'post',
              data: fd,
              dataType: "json",
              contentType: false,
              processData: false,
              success: function(response){
                  if(response.status == 200){
                      if(response.data.image!=''){
                        var src = "<?php //echo APPLICATION_URL.'/avatars/thumb/'?>" + response.data.image;
                        $('.fileinput div.fileinput-exists img').attr('src', src);
                        $('.fileinput .thumbnail img').attr('src', src);

                        $('.fileinput .thumbnail').css("display", "inline-block");
                        $('.fileinput div.fileinput-exists').css("display", "none");

                        $('#header_profile_img').attr("src", "<?php //echo APPLICATION_URL.'/avatars/160/'?>"+response.data.image);

                        $('.update_button > span.fileinput-new').text('Change Photo');
                        $('.update_button > span.fileinput-exists').text('Change Photo');
                        showAppAlert('Success!!',response.message,'success');
                      }

                  } else {
                      $('.update_button > span.fileinput-new').text('Change Photo');
                      $('.update_button > span.fileinput-exists').text('Change Photo');
                      showAppAlert('Error!!',response.message,'error');
                  }
              },
          });

        } else {
          $('.update_button > span.fileinput-new').text('Change Photo');
          $('.update_button > span.fileinput-exists').text('Change Photo');
          showAppAlert('Error!!','You can upload a file upto 10 MB.','error');
        }

    });*/


    // change page title as per tab click
    $('.profile_page .nav-link').on('click', function(){
        $('#tabPageTitle').text($(this).text());
    });

    function formValidate(){
      // custom function
        $('#client_email_password').rules("remove");
      
        $('#user_profile_form').validate({
          /*ignore:'',*/
          rules:{
              client_name:{
                  required:true,
              },
              client_email:{
                  required:true,
              },
              client_email_password: {
                  minlength: 8,
                  required:false,
                  notDefaultText: true
              },
          },
          errorPlacement:function(error,element){
              // alert($(element).attr('id'));
              error.insertAfter(element);
          },
      });

    }


    $('#client_email_password').val('');
    $('#client_email_password').parent().hide();
    $("[for=client_email_password]").hide();
    var user_current_email = '<?php echo $loggedusermail; ?>';

    $('#client_email').on('keyup', function(){
        var thisVal = $(this).val();
        $('#client_email_password').val('');
        $('#client_email_password').parent().hide();
        $("[for=client_email_password]").hide();
        if(thisVal != user_current_email){
          $('#client_email_password').parent().show();
          $("[for=client_email_password]").show();
        }
    });

    /* account settings form */
    $(document).on("click","#startedbtn",function(e){
    /*$('#startedbtn').on('click',function(){*/
      var client_email_val = $('#client_email').val();
      formValidate();

      if($('#user_profile_form').valid())
      {
        $('#user_current_email_error').remove();
        if(client_email_val != user_current_email){
          /*$('#client_email_password').parent().append("<span id='user_current_email_error' class='error-msg-block'>Please enter password to change email.</span>");*/
          $('#client_email_password').rules("add", 
          {
              required: true
          });

          if($('#user_profile_form').valid())
          {
            // alert('it is valid');
          } else {
            // alert('it is NOT valid');
            return false;
          }
          
        } else {
          // alert(2);
          // $('#client_email_password').rules("remove");
        }
        passwordEncrypt();
        $('#user_profile_form').submit();

      } else {
        // alert('Please check the form and complete it.');
      }

    });

    /* change password form */
    $('#btnchpasswordsubmit').on('click',function(){
        $('.user_password_form').validate({
            /*ignore:'',*/
            rules:{
                client_old_password: {
                    minlength: 8
                },
                client_password: {
                    minlength: 8,
                    notDefaultText: true
                },
                client_rpassword: {
                    equalTo: '#client_password',
                    minlength: 8,
                },
            },
            errorPlacement:function(error,element){
                // alert($(element).attr('id'));
                error.insertAfter(element);
            },
        });

        if($('.user_password_form').valid())
        {
          passwordEncrypt();
          $('.user_password_form').submit();

        } else {
          // alert('Please check the form and complete it.');
        }

    });
    


}); 
</script>