<?php
  $loggedusermail = $this->loggedUser->yurt90w_client_email;
?>
<style>
.prodsel-btn{margin-top:20px;}
.gotoorder-btn{color:#ff4f5d;margin-top:15px;display:inline-block;}
.prodpic-holdtag img{margin-right:10px;border:1px solid #eee;padding:5px 10px;}
#prodselModal .modal-description{margin-bottom:10px;}
.propic-wallblk{display:inline-block;vertical-align:top;margin-right:10px;}
.propic-inpblk{visibility:visible !important;display:block;margin-left:auto;margin-right:auto;margin-top:5px;}
input[type='radio']{visibility:hidden;}
#seller_logo{visibility:hidden;position:absolute;}
#seller_banner{visibility:hidden;position:absolute;}
#cropimage_block{padding-bottom:30px;}
.upload_btn{padding:6px 20px;background-color:rgb(1, 0, 1);color:#fff !important;font-size:16px;border-radius:5px;text-align:center;text-decoration:none;}
.rgt_btn{background-color:#ab191a;padding:0px;width:197px;height:54px;line-height:54px;border-radius:0px;font-size:18px;color:#fff !important;border:none;margin:10px auto 0px;}
.btn-outline-secondary{
  background-color: #ab191a !important;
}
.commen-sec-images{padding-top:20px;}
#client_image{visibility:hidden;}
.menu-itemz > li > a{font-size:22px !important;}
.table thead th, .table tbody td{padding-left:10px !important;}
table.dataTable thead .sorting:before, table.dataTable thead .sorting_asc:before, table.dataTable thead .sorting_desc:before, table.dataTable thead .sorting_asc_disabled:before, table.dataTable thead .sorting_desc_disabled:before{content:'';}
table.dataTable thead .sorting:after, table.dataTable thead .sorting_asc:after, table.dataTable thead .sorting_desc:after, table.dataTable thead .sorting_asc_disabled:after, table.dataTable thead .sorting_desc_disabled:after{content:'';}
table.dataTable.dtr-inline.collapsed > tbody > tr > td:first-child:before, table.dataTable.dtr-inline.collapsed > tbody > tr > th:first-child:before{content:'';}
.prodsel-btn{margin-bottom:25px;}
.manage-product-box{height:125px;}
.manage-product-box2{min-height:125px;}
.manage-product-box .product-img{width:150px;}
.product-detail-box a{text-decoration:none !important;outline:none !important;}
.customer-products .customer-left-side .product-img img{object-fit:contain;}
<?php if($_SESSION["logstat"] != '2' || empty($_SESSION["logstat"])) { ?>
.other-header{display:none !important;}
#navbarSupportedContent{display:none !important;}
.custom-link{display:none;}
<?php } ?>
.radio-button-box [type="radio"]:checked + label:after, .radio-button-box [type="radio"]:not(:checked) + label:after{width:8px;height:8px;top:4px;left:4px;}
.status-btn.Processing{color:#999900;width:auto;min-width:79px;background-color:#EEE8AA}
.status-btn.Ready_to_ship{color:rgb(199,21,133);width:auto;min-width:79px;background-color:#FFC0CB;}
.status-btn.Shipped{color:rgb(255, 0, 0);width:auto;min-width:79px;background-color:#ffcccb;}
.status-btn.Delivered{color:rgb(0,100,0);width:auto;min-width:79px;background-color:#90ee90;}	
@media (max-width: 767px) {
	.manage-product-box{height:auto;overflow:hidden;}
	.manage-product-box .product-img{width:auto;height:auto;max-width:100px;margin-top:25px;}
	.customer-product-box .row-one p{width:100%;text-align:left !important;padding-left:20px !important;}
}
</style> 

<div class="comman-section">
	<div class="container">
		<div class="common-heading">
			<h2 class="heading">My Orders</h2>
		</div>
	</div>	
</div>




<div class="profile_page seller-order-page">
  <div class="container">
    <div class="profile-section">
      <div class="profile-nav d-none d-xl-block">
              <? /* ?>
              <div class="change-image-user-box">
                  <div class="user-image"> <img src="<?= getUserImage($this->loggedUser->yurt90w_client_image,"200")?>"></div>
                  <input type="hidden" name="imageCordinates" id="imageCordinates" value="" autocomplete="off">
                  <?php if(!empty($this->loggedUser->yurt90w_client_name)) { ?>
                  <p class="user-name"><?= $this->loggedUser->yurt90w_client_name; ?></p>
                  <?php } ?>
                  <div class="border-gradient change-img-btn"> <a href="<?= APPLICATION_URL.'/profile/1'; ?>" class="change-btn view-btn btn">Change Image</a> </div>
              </div>
              <? */ ?>
              <div class="change-image-user-box">
                  <div class="user-image"> <img src="<?= getUserImage($this->loggedUser->yurt90w_client_image,"160")?>" class="cltpro-logo"> <a href="<?= APPLICATION_URL.'/profile/1'; ?>" class="change-picbtn"><img src="<?= HTTP_IMG_PATH.'/camera.svg'; ?>"></a></div>
                    <div class="user-info">
                      <p class="user-name"><?= $this->loggedUser->yurt90w_client_name; ?></p>
                      <a href="<?= APPLICATION_URL.'/logout'; ?>" class="logout"> Logout </a>
                    </div>
              </div>

        <div class="side-nav">
          <?php echo $this->render("application/static/sidesection.phtml",array('store_data'=>$store_data,'sellerorder'=>1)); ?>
        </div>
        <!-- change user image -->
      </div>
      <!--  -->

      <? /* ?>
      <div class="right-side">
            <div class="select-order">
                <label class="">Order Status </label>
                <select class="custom-select orderchk-box">
                  <option selected>All</option>
                  <option value="1">Processing</option>
                  <option value="2">Ready to ship</option>
                  <option value="3">Shipped</option>
                  <option value="4"> Delivered</option>
                </select>
            </div>
        <div class="customer-prodbox">
              <!-- customer-product box -->
              <?php if(!empty($seller_orders)) { 
          foreach($seller_orders as $seller_orders_key => $seller_orders_val) {
          $end_record = end($seller_orders_val);
        ?>
            <div class="customer-product-box">
                <div class="row-one">
                  <p class="order-name">Order Number : <?= $seller_orders_key ?></p>
                  <p class="order-date">Order Date : <?= date("m-d-Y",strtotime($end_record["orderdate"])) ?></p>
                  <div class="select-order mr-0">
                      <label class="">Order Status </label>
                      <select class="custom-select orderstat-chkbox" data-id="<?= $seller_orders_key ?>">
                        <option value="1" <?php if($end_record["order_status"] == '1') { ?>selected="selected"<?php } ?> >Processing</option>
                        <option value="2" <?php if($end_record["order_status"] == '2') { ?>selected="selected"<?php } ?>>Ready to ship</option>
                        <option value="3" <?php if($end_record["order_status"] == '3') { ?>selected="selected"<?php } ?>>Shipped</option>
                        <option value="4" <?php if($end_record["order_status"] == '4') { ?>selected="selected"<?php } ?>>Delivered</option>
                      </select>
                  </div>
                </div>

                <div class="row-two">
                    <div class="left-side-block">
                      <div class="media">
                        <?php if(!empty($end_record[T_CLIENT_VAR.'client_image'])) { ?>
                          <img src="<?=HTTP_PROFILE_IMAGES_PATH.'/60/'.$end_record[T_CLIENT_VAR.'client_image']; ?>"> 
                        <?php } else { ?>
                          <img src="<?=HTTP_PROFILE_IMAGES_PATH.'/60/default.png'; ?>">
            <?php } ?>
                        <div class="media-body">
                            <p class="user-name"><?= $end_record[T_CLIENT_VAR.'client_name']; ?></p>
                            <div class="customer-detail">
                              <div class="row">
                                <p class="col-sm"><?= $end_record[T_CLIENT_VAR.'client_address']; ?></p>
                                <p class="col-sm"><?= $end_record[T_CLIENT_VAR.'client_postcode']; ?> </p>
                                <p class="col-sm"><?= $end_record[T_CLIENT_VAR.'client_city']; ?> </p>
                                <p class="col-sm"><?= $end_record[T_CLIENT_VAR.'client_state']; ?> </p>
                                <p class="col-sm"><?= $end_record[T_CLIENT_VAR.'client_phone']; ?></p>
                              </div>
                            </div>
                        </div>
                      </div>
                    </div>
                  
                </div>
              <?php foreach($seller_orders_val as $customer_orders_valkey => $customer_orders_valt) { 
              ?>
                      <div class="customer-products">
                        <div class="customer-left-side">
                          <div class="product-img"> <?php if(!empty($customer_orders_valt["product_defaultpic"])) { ?>
                  <img src="<?= HTTP_PRODUCT_PIC_PATH.'/240/'.$customer_orders_valt["product_defaultpic"]; ?>" class="orderprod-pictg" /> 
              <?php } else {
                $product_photos = explode(",",$customer_orders_valt["product_photos"]); 
                if(!empty($product_photos[0])) { ?>
                  <img src="<?= HTTP_PRODUCT_PIC_PATH.'/240/'.$product_photos[0]; ?>" class="orderprod-pictg" />
                <?php }
              } ?>  </div>
                    <div class="product-detail">
                      <h3 class="product-title"> <?= $customer_orders_valt["product_title"]; ?> </h3>
                      <p class="p-name"> <span> Price :</span> <span>$<?= $customer_orders_valt["product_price"]; ?> </span> </p>
                      <p class="p-name"> <span> Discount: </span> <span> $<?= $customer_orders_valt["order_discount"]; ?> </span> </p>
                      <p class="p-name"> <span> Quantity :</span> <span> <?= $customer_orders_valt["order_qty"]; ?></span> </p>
                      <p class="p-name"> <span> Amount :</span> <span> $<?= round($customer_orders_valt["order_total"],2); ?> <?php if($customer_orders_valt["order_sellerpaid"] == '2') { ?>Received<?php } else { ?>Pending<?php } ?> (Admin commission deduction $<?= round($customer_orders_valt["order_sitefee"],2); ?>)</span> </p>
                      <?php if(!empty($customer_orders_valt["order_shipping"])) { ?>
                      <p class="p-name">Shipping charge of $<?= $customer_orders_valt["order_shipping"] ?> included</p>
                      <?php } ?>
                    </div>
                  </div>
                </div>
                <?php } ?>
                <!-- customer product -->
            </div>
            <!-- customer-product box -->
          <?php } } else { ?>
            <p>No orders placed for you.</p>
            <?php } ?>
            </div>	
          
      </div>
      <? */ ?>
      <!-- right-side-block -->

      <div class="right-side">
            <div class="select-order order-top">
                <label class="">Order Status </label>
                <select class="custom-select orderchk-box">
                  <option selected>All</option>
                  <option value="1">Processing</option>
                  <option value="2">Ready to ship</option>
                  <option value="3">Shipped</option>
                  <option value="4"> Delivered</option>
                </select>
            </div>
            <div class="order-mainblk">
            <?php if(!empty($seller_orders)) {
          		foreach($seller_orders as $seller_orders_key => $seller_orders_val) { 
				$start_record = reset($seller_orders_val);	
          		$end_record = end($seller_orders_val);
				$url = '@(http)?(s)?(://)?(([a-zA-Z])([-\w]+\.)+([^\s\.]+[^\s]*)+[^,.\s])@';   
				$order_tracking = preg_replace($url, '<a href="$0" target="_blank" title="$0">$0</a>', $start_record["order_tracking"]);	
        	?>
            <div class="order-block">
                  <div class="order-top">
                       	<a href="<?= APPLICATION_URL.'/generate-pdf/'.$start_record["order_serial"]; ?>" class="pull-right invoice-dwlbtn" title="Download"><i class="fa fa-download"></i></a>
                        <div class="order-left">
                            <p class="order-id"> Order #<?= $seller_orders_key ?></p>
                            <p class="order-date"> <?= date("m-d-Y",strtotime($start_record["orderdate"])) ?> </p>
                            <?php if(!empty($order_tracking) && ($start_record["order_status"] == '3' || $start_record["order_status"] == '4')) { ?>
								<?php /*?><p class="tracking-headtg">Tracking details: </p><?php */?>
								<a href="javascript:void(0)" class="tracking-headtg" data-tg="<?= $end_record["order_tracking"]; ?>">Tracking Details</a>
								<p class="d-none track-para"><?= $order_tracking ?></p>
							<?php } ?>
                            <p class="order-date"><b>Customer Name: </b><?= $start_record[T_CLIENT_VAR."client_name"] ?></p>
                            <?php $apt = ''; $city = ''; $state = ''; $country = '';
                                if(!empty($start_record["order_apartment"])) { $apt = $start_record["order_apartment"].', '; }
                                if(!empty($start_record["order_city"])) { $city = ', '.$start_record["order_city"]; } 
                                if(!empty($start_record["order_state"])) { $state = ', '.$start_record["order_state"]; }
                                if(!empty($start_record["order_country"])) { $country = ', '.$start_record["order_country"]; }
                            ?>
                            <p class="order-date"><b>Shipping address:</b> <?= $apt.$start_record["order_address"].$city.$state.$country ?></p>
                            <?php if(!empty($start_record["order_shipname"])) { ?>
                            <p class="order-date"><b><?= $start_record["order_shipname"] ?> (<?php if($start_record["order_shiprate"] == '1') { echo "Standard"; } else { echo "International"; }  ?>)</b></p>
                            <?php } ?>
                        </div>
                        <?php if(count($seller_orders_val) < 2 && $start_record["product_isdigital"] == '1') { ?>
                        <?php } else { ?>
                        <div class="select-order">
                        <label class="">Order Status </label>
                        <select class="custom-select orderstat-chkbox" data-id="<?= $seller_orders_key ?>">
                          <option value="1" <?php if($start_record["order_status"] == '1') { ?>selected="selected"<?php } ?> >Processing</option>
                          <option value="2" <?php if($start_record["order_status"] == '2') { ?>selected="selected"<?php } ?>>Ready to ship</option>
                          <option value="3" <?php if($start_record["order_status"] == '3') { ?>selected="selected"<?php } ?>>Shipped</option>
                          <option value="4" <?php if($start_record["order_status"] == '4') { ?>selected="selected"<?php } ?>>Delivered</option>
                        </select>
                    	</div>
                       	<?php } ?>
                        
                  </div>
                  <!--  -->

                  <div class="table-block">
                    <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr class="table-head">
                            <th scope="col"></th>
                            <th scope="col">Product Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Discount</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Amount</th>
                            <th scope="col">shipping rate</th>
                            <th>Refund</th>
                          </tr>
                        </thead>
                        <!--  -->
                        <tbody>
                         <?php foreach($seller_orders_val as $customer_orders_valkey => $customer_orders_valt) {
							$refund_data = $this->layout()->AbstractModel->Super_Get(T_REFUND,"refund_orderid =:TID","fetch",array('warray'=>array('TID'=>$customer_orders_valt["order_id"])));
              ?>
                          <tr>
                            <td > <div class="user-img"> 
                            <?php if(!empty($customer_orders_valt["product_defaultpic"])) { ?>
							  <img src="<?= HTTP_PRODUCT_PIC_PATH.'/240/'.$customer_orders_valt["product_defaultpic"]; ?>" class="orderprod-pictg" /> 
						  	<?php } else {
							$product_photos = explode(",",$customer_orders_valt["product_photos"]); 
							if(!empty($product_photos[0])) { ?>
							  <img src="<?= HTTP_PRODUCT_PIC_PATH.'/240/'.$product_photos[0]; ?>" class="orderprod-pictg" />
							<?php } } ?>  
                            </div> </td>
                            <td> 
                                <p class="dress-name"> <?= $customer_orders_valt["product_title"] ?> </p>
                                <div class="color-and-size"> 
                                  <?php if(!empty($customer_orders_valt["order_color"])) { ?>
                                  <p class="color"> Color: <span class="color-tg" data-id="<?= $customer_orders_valt["order_color"] ?>"></span> </p> 
                                  <?php } if(!empty($customer_orders_valt["order_size"])) { ?>
                                  <p class="size"> Size <span> <?= $customer_orders_valt["order_size"] ?> </span> </p>
                                  <?php } ?>  
                                </div>
                            </td>
                            <td> $<?= $customer_orders_valt["order_baseprice"] ?> </td>
                            <td> $<?= $customer_orders_valt["order_discount"]; ?> </td>
                            <td> <?php if($customer_orders_valt["product_isdigital"] != '1') { echo $customer_orders_valt["order_qty"]; } else { echo "N/A"; } ?></td>
                            <td> $<?= bcdiv($customer_orders_valt["order_total"],1,2); ?> <span> Paid </span><?= "$".bcdiv($customer_orders_valt["order_sitefee"],1,2); ?> <span>Tx Fee</span></td>
                            <td><?php if($customer_orders_valt["product_isdigital"] != '1') { ?>$<?= $customer_orders_valt["order_shipping"]; } else { echo "N/A"; }  ?> </td>
                          	<td><?php if(empty($refund_data)) { ?><a href="javascript:void(0)" class="refund-tg" data-id="<?= str_replace("=","",base64_encode($customer_orders_valt["order_id"])) ?>">Refund</a><?php } else { if($refund_data["refund_status"] == '1') { echo "$".$refund_data["refund_amount"]."<span>refunded</span>"; } else { echo '<a href="javascript:void(0)" class="status-btn Processing btn">Pending</a>'; } } ?></td>                          	
                          </tr>
						 <?php } ?>
                        </tbody>
                        <!--  -->
                      </table>
                      <!-- table -->
                    </div>
                  </div>
                  <!-- table block -->
            </div>
            <!-- order block -->
            <?php } } ?>
		  </div>   
      </div>
      <!-- right side -->
    </div>
  </div>
</div>
<div class="modal tracking-modal fade" id="trackingModal" tabindex="-1" role="dialog" aria-labelledby="trackingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="trackingModalLabel">Enter tracking details:</h5>
        <button type="button" class="close track-closebtn" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
     		<textarea rows="5" id="tracking_txt" name="tracking_txt" class="form-control tracking_txt" maxlength="655"></textarea>
     		<div class="text-center">
      			<a href="javascript:void(0)" class="confirm-trackbtn">Submit</a>
            	<a href="javascript:void(0)" class="confirm-cancelbtn">Cancel</a>
		  	</div>
      </div>
    </div>
  </div>
</div>
<div class="modal refund-modal fade" id="refundModal" tabindex="-1" role="dialog" aria-labelledby="refundModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="trackingModalLabel">Refund Amount</h5>
        <button type="button" class="close track-closebtn" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
     		<form id="refund_form" name="refund_form">
				<div class="radio-button-box">
					<div class="radio-button">
					  <p class="m-0">
						<input type="radio" id="refund-opt1" name="radio-group" class="rule-chkbox" value="1" checked="">
						<label for="refund-opt1">Full Refund</label>
					  </p>
					  <p class="m-0">
						<input type="radio" id="refund-opt2" name="radio-group" class="rule-chkbox" value="2">
						<label for="refund-opt2">Partial Refund</label>
					  </p>
					</div>
				</div>
				<div class="form-group partial-blk d-none">
					<input type="text" id="partial_amount" name="partial_amount" class="form-control" placeholder="Enter amount to refund" maxlength="8">
				</div>
				<div class="form-group">
					<textarea id="refund_message" name="refund_message" class="required form-control" rows="4" maxlength="400" placeholder="Message"></textarea>
					<input type="hidden" id="refund_order" name="refund_order">
				</div>
				<div class="text-center">
					<a href="javascript:void(0)" class="confirm-refundbtn">Refund</a>
				</div>
		  	</form>
      </div>
    </div>
  </div>
</div>
<div class="modal trackModal fade" id="trackModal" tabindex="-1" role="dialog" aria-labelledby="trackModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title heading" id="trackModalLabel">Tracking Details </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">X</span>
        </button>
      </div>
      <div class="modal-body">
        <!--  -->
          <p class="track-info"></p>	       
        <!--  -->
      </div>
      
    </div>
  </div>
</div> 
<script type="text/javascript">
	function nl2br (str, is_xhtml) {   
		var breakTag = (is_xhtml || typeof is_xhtml === 'undefined') ? '<br />' : '<br>';    
		return (str + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1'+ breakTag +'$2');
	}
	
	$(document).on("click",".refund-tg",function() {
		var tid = $(this).attr("data-id");
		$("#refund_order").val(tid);
		$(".confirm-refundbtn").attr("data-id",tid);
		$("#refundModal").modal("show");
	})
	
	$(document).on("click",".rule-chkbox",function() {
		var checked_val = $(".rule-chkbox:checked").val();
		if(checked_val == '2') {
			$("#partial_amount").addClass("required");
			$(".partial-blk").removeClass("d-none");
		} else {
			$("#partial_amount").removeClass("required");
			$(".partial-blk").addClass("d-none");
		}
	})
	
	$(document).on("click",".confirm-refundbtn",function() {
		var tid = $(this).attr("data-id");
		if($("#refund_form").valid()) {
			$.ajax({
				url: baseUrl + "/refund-amount",
				type: "POST",
				data: $("#refund_form").serialize(),
				success: function (data) {
					if(data == 'success') {
						showAppAlert('Success!!','You have successfully placed the refund request.','success');
						setTimeout(function(){ location.reload(); }, 1000);
					} else if(data == 'refund_issued') {
						showAppAlert('Error!!','Refund has already been issued for this product.','error');
					} else if(data == 'invalid_amount') {
						showAppAlert('Error!!','Partial amount should be less than the paid amount excluding processing fee.','error');
					} else {
						showAppAlert('Error!!','No such order has been placed.','error');
					}
				}
			})
		}	
	})
	
	$(document).on('input','#partial_amount', function() {
		this.value = this.value.match(/^\d+\.?\d{0,2}/);	
	})
	
	$(document).on("click",".track-closebtn",function() {
		var tid = $(this).attr("data-id");
		var chk = $(".orderstat-chkbox[data-id="+tid+"]").val();
		var optVal = chk - 1;
		$(".orderstat-chkbox[data-id="+tid+"]").val(optVal)
		$("#trackingModal").modal("hide");	
	})
	
	$(document).on("click",".confirm-cancelbtn",function() {
		var tid = $(this).attr("data-id");
		var chk = $(".orderstat-chkbox[data-id="+tid+"]").val();
		var optVal = chk - 1;
		$(".orderstat-chkbox[data-id="+tid+"]").val(optVal)
		$("#trackingModal").modal("hide");	
	})
	
	$(document).on("change",".orderchk-box",function() {
		var orderchk = $(this).val();
		$.ajax({
			url: baseUrl + "/seller-chkorder",
			type: "POST",
			data: { orderchk: orderchk },
			success: function (data) {
				$(".order-mainblk").html(data);		
			}
		})
	})
	
	$(document).on("click",".confirm-trackbtn",function() {
		var tid = $(this).attr("data-id");
		var chk = $(".orderstat-chkbox[data-id="+tid+"]").val();
		var tracktxt = $(".tracking_txt").val();
		$.ajax({
				url: baseUrl + "/order-update",
				type: "POST",
				data: { orderchk: chk,order:tid,tracktxt:tracktxt },
				success: function (data) {
					if(data == 'error') {
						showAppAlert('Error!!','No such order has been placed.','error');
					} else if(data == 'invalid_input') {
						showAppAlert('Error!!','No such order has been placed.','error');
					} else {
						showAppAlert('Success!!','You have successfully updated the order status.','success');
						setTimeout(function(){ location.reload(); }, 1000);
					}
				}
			})
	})
	
	$(document).on("change",".orderstat-chkbox",function() {
		var orderchk = $(this).val();
		var order = $(this).attr("data-id");
		if(orderchk == '3') {
			$("#trackingModal").modal("show");
			$(".track-closebtn").attr("data-id",order);
			$(".confirm-trackbtn").attr("data-id",order);
			$(".confirm-cancelbtn").attr("data-id",order);
		} else {
			$.ajax({
				url: baseUrl + "/order-update",
				type: "POST",
				data: { orderchk: orderchk,order:order },
				success: function (data) {
					if(data == 'error') {
						showAppAlert('Error!!','No such order has been placed.','error');
					} else if(data == 'invalid_input') {
						showAppAlert('Error!!','No such order has been placed.','error');
					} else {
						showAppAlert('Success!!','You have successfully updated the order status.','success');
						setTimeout(function(){ location.reload(); }, 1000);
					}
				}
			})
		}
	})
	
	$(document).on("click",".invoice-dwlbtn",function() {
			
	})
	
	$(document).ready(function(e) {
		$('.color-tg').each(function(i, obj) {
			var colortg = $(obj).attr("data-id");
			$(obj).css("background-color",colortg);
		})
	})
	
	$(document).on("click",".tracking-headtg",function() {
		var info =  $(this).next(".track-para").html();
		$(".track-info").html(nl2br(info));
		$("#trackModal").modal("show");
	})
</script>