<div class="row">
	<div class="col-md-4 col-sm-6 ">
	  <div class="count-box">
		<div class="box-1">
			<div class="icon-box"><img src="<?=HTTP_IMG_PATH?>/file.svg">  </div>
			<div class="counting-block">
				<p class="numbers"> <?= $store_views; ?> </p>
				<p class="count-txt"> Total Views </p>
			</div>
		</div>
	   <!--  <div class="color-box">Total Views</div> -->
	  </div>
	  <!--  -->
	</div>
	<!--  -->
	<div class="col-md-4 col-sm-6">
	  <div class="count-box">
		<div class="box-1">
			<div class="icon-box"><img src="<?=HTTP_IMG_PATH?>/check-list.svg">  </div>
			<div class="counting-block">
				<p class="numbers"> <?= $store_orders; ?> </p>
				<p class="count-txt">Orders</p>
			</div>
		</div>

	  </div>
	  <!--  -->
	</div>
	<!--  -->
	<div class="col-md-4 col-sm-6">
	  <div class="count-box">
		<div class="box-1">
			<div class="icon-box"><img src="<?=HTTP_IMG_PATH?>/investment.svg">  </div>
			<div class="counting-block">
				<p class="numbers"> $<?= $store_earning ?> </p>
				<p class="count-txt">Earnings</p>
			</div>
		</div>
	  </div>
	  <!--  -->
	</div>
	<!--  -->
</div>