<?php

use Zend\Session\Container;

use Application\Model\AbstractModel;

use Zend\Db\Sql\Expression;

$CURRENT_CONTROLLER = $this->layout()->CURRENT_CONTROLLER;

$CURRENT_ACTION = $this->layout()->CURRENT_ACTION;

$CURRENT_MODULE = $this->layout()->CURRENT_MODULE;



?>

<header>

   

  

     <div class="homecontainer container">

     

    

  <a class="navbar-brand" href="<?php echo SITE_HTTP_URL?>"><img src="<?=HTTP_IMG_PATH?>/logo.png" class="logo"></a>

 <nav class="navbar navbar-expand-sm menu d-none d-lg-block d-md-block">

	 

     <?php /*?> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

         <span class="navbar-toggler-icon"></span>

      </button><?php */?>

    <ul class="navbar-nav">

    <?php if(!isset($this->loggedUser) || empty($this->loggedUser)){?>

   <li class="nav-item">

      <a class="nav-link" href="<?=$this->url('front_login')?>">Log In<span class="sr-only">(current)</span></a>



     

    </li>

    <li class="nav-item">
      <a class="nav-link" href="<?=$this->url('register-personal-account')?>">User Sign Up</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?=$this->url('register-as-a-member')?>">Member Sign Up</a>
    </li>

    <? }?>

    <li class="nav-item">

       <a class="nav-link" href="javascript:void(0)">Book now</a>

 	</li>

  </ul>

</nav>

<?php if(isset($this->loggedUser) && !empty($this->loggedUser)){

	$client_name=$this->loggedUser->yurt90w_client_name;

	$clNameData=explode(" ",$client_name);

	$clName=$clNameData[0];

	?>   

<!-- <div class="user_account d-none d-lg-block d-md-block">

<ul>

 <li class="nav-item">

     <a class="nav-link" href="#">Hello <?php echo $clName?></a>

    </li>

    <li class="nav-item">

       <img src="<?=getUserImage($this->loggedUser->yurt90w_client_image,"60")?>" class="user_image">

 	</li>

  </ul>



</div> --> 



<div class="user_account d-none d-lg-block d-md-block">

    <div class="dropdown show">

        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hello <?php echo $clName?>

        </a>

        <img src="<?=getUserImage($this->loggedUser->yurt90w_client_image,"60")?>" class="user_image">

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

        	 <a class="dropdown-item" href="<?=$this->url('front_dashboard')?>">Dashboard</a>

            <a class="dropdown-item" href="<?=$this->url('front_profile')?>">Profile</a>

            <a class="dropdown-item" href="<?=$this->url('front_logout')?>">Logout</a>

        </div>

    </div>



</div>









<? }?>









    



 <nav class="navbar d-flex align-items-start sidenav d-md-none d-lg-none" id="mySidenav">

 	

    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

    <?php if(isset($this->loggedUser) && !empty($this->loggedUser)){

	  $client_name=$this->loggedUser->yurt90w_client_name;

	$clNameData=explode(" ",$client_name);

	$clName=$clNameData[0];

	  ?> 

 	<?php /*?><div class="user_account" style="margin: 10px 0 0;width: 100%;text-align: center;">

	<ul>

	<li class="nav-item" style="text-align:center;">

       <img src="<?=getUserImage($this->loggedUser->yurt90w_client_image,"60")?>" class="user_image" style="max-width:60px;">

 	</li>	

    

 	<li class="nav-item">

     <a class="nav-link" href="#">Hello <?php echo $clName?></a>

    </li>

    

  </ul>



</div><?php */?>

 <? }?>

	 <?php if(!isset($this->loggedUser) || empty($this->loggedUser)){?> 

    <ul class="navbar-nav"  >

    <li class="nav-item">

      <a class="nav-link" href="<?=$this->url('front_login')?>">Log In</a>

    </li>

    <li class="nav-item">

     <a class="nav-link" href="<?=$this->url('signup')?>">Sign Up</a>

    </li>

    <li class="nav-item">

       <a class="nav-link" href="javascript:void(0)">Book now</a></li>

       <?php /*?><?=$this->url('booknow')?><?php */?>

  </ul>

  <? }else{?>

  

  	<ul class="navbar-nav"  >

    <li class="nav-item">

      <a class="nav-link" href="<?=$this->url('front_dashboard')?>">Dashboard</a>

    </li>

    <li class="nav-item">

     <a class="nav-link" href="<?=$this->url('front_profile')?>">Profile</a>

    </li>

    <li class="nav-item">

     <a class="nav-link" href="<?=$this->url('front_logout')?>">Logout</a>

    </li>

    <li class="nav-item">

       <a class="nav-link" href="javascript:void(0)">Book now</a>

   </li>

  </ul>

	<? }?>

  

  

  

  

</nav>   





   

    

    <span style="font-size:40px;cursor:pointer" onclick="openNav()" class="d-md-none d-lg-none togglenav">&#9776;</span>

 </div>   

</header>







<script>

function openNav() {

    document.getElementById("mySidenav").style.width = "100%";

}



function closeNav() {

    document.getElementById("mySidenav").style.width = "0";

}



var nav = $('header');	



	$(window).scroll(function () {

		if ($(this).scrollTop() > $(".top_back").height()) {

		//	$('.navbar-collapse.collapse.in').removeClass('in');

			//nav.addClass("header-fixed");

		} else {

		

		}

			nav.removeClass("header-fixed");

	});





</script>