<?php
if(false){
?><!doctype html>
<html><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title><?php echo $this->site_configs['site_title'];?> Admin | <?=$this->pageHeading?></title>
    
    <!--All CSS Files included-->
   <?php echo $this->render('include_css.phtml');?> 
   <?php $current_controller=$this->CURRENT_CONTROLLER;
   $current_action=$this->CURRENT_ACTION;
   ?>
   <script type="text/javascript" src="<?=PLUGIN_PATH?>/global/vendor/jquery/jquery.js"></script>
    <script src="<?=PLUGIN_PATH?>/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>
    
    <script>
		var baseUrl = '<?php echo ADMIN_APPLICATION_URL?>';
        var currentRoute='<?=$this->layout()->currentRoute?>';
	 </script>
    <style>.form-material .form-control.is-invalid {
    background-image: linear-gradient(#f44336,#f44336),linear-gradient(#e0e0e0,#e0e0e0) !important;}textarea{resize:none;}</style>
    
</head>

<body class="page-login-v2 layout-full page-dark">
<div id="wrapper">	
	 <?php if($current_controller=='IndexController' && ($current_action=='login' || $current_action=='forgotpassword' || $current_action=='resetpassword')){?>
       <?php echo $this->render('login.phtml');?>
		<?php
			 
			echo $this->headScript();
			echo $this->GetMessages();
		?>
   
	 <? }else{?>
	<?php echo $this->render('header.phtml');?>  
    <?php echo $this->render('navigation.phtml')?>
     <div id="page-wrapper">
     	<div class="container-fluid">
        	<?php echo $this->render("page-header.phtml");?>
			<?php echo $this->layout()->content;?>
		</div>
		<?php
			 echo $this->render("footer.phtml");
			 echo $this->headScript();
			echo $this->GetMessages();
		?>
    </div>
    <? }?>
</div>
<div id="admin-webapp-modal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content overflow">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body"></div>
    </div>
  </div>
</div>

<script>
      (function(document, window, $){
        'use strict';
    
       
      })(document, window, jQuery);
    </script>
</body>


</html>
<? }?>



<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="bootstrap material admin template">
    <meta name="author" content="">
    
    <title>Login V2 | Remark Material Admin Template</title>
    
    <link rel="apple-touch-icon" href="<?php echo SITE_HTTP_URL?>/assets/base/assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="<?php echo SITE_HTTP_URL?>/assets/base/assets/images/favicon.ico">
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/css/bootstrap-extend.min.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/base/assets/css/site.min.css">
    
    <!-- Plugins -->
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/flag-icon-css/flag-icon.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/vendor/waves/waves.css">
        <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/base/assets/examples/css/pages/login-v2.css">
    
    
    <!-- Fonts -->
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/fonts/material-design/material-design.min.css">
    <link rel="stylesheet" href="<?php echo SITE_HTTP_URL?>/assets/global/fonts/brand-icons/brand-icons.min.css">
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    
    <!--[if lt IE 9]>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
    
    <!--[if lt IE 10]>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/media-match/media.match.min.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    
    <!-- Scripts -->
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>
  </head>
  <body class="animsition page-login-v2 layout-full page-dark">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->


    <!-- Page -->
    <div class="page" data-animsition-in="fade-in" data-animsition-out="fade-out">
      <div class="page-content">
        <div class="page-brand-info">
          <div class="brand">
            <img class="brand-img" src="<?php echo SITE_HTTP_URL?>/assets/base/assets/images/logo@2x.png" alt="...">
            <h2 class="brand-text font-size-40">Remark</h2>
          </div>
          <p class="font-size-20">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>

        <div class="page-login-main">
          <div class="brand hidden-md-up">
            <img class="brand-img" src="<?php echo SITE_HTTP_URL?>/assets/base/assets/images/logo-colored@2x.png" alt="...">
            <h3 class="brand-text font-size-40">Remark</h3>
          </div>
          <h3 class="font-size-24">Sign In</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

          <form method="post" action="login-v2.html" autocomplete="off">
            <div class="form-group form-material floating" data-plugin="formMaterial">
              <input type="email" class="form-control empty" id="inputEmail" name="email">
              <label class="floating-label" for="inputEmail">Email</label>
            </div>
            <div class="form-group form-material floating" data-plugin="formMaterial">
              <input type="password" class="form-control empty" id="inputPassword" name="password">
              <label class="floating-label" for="inputPassword">Password</label>
            </div>
            <div class="form-group clearfix">
              <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
                <input type="checkbox" id="remember" name="checkbox">
                <label for="inputCheckbox">Remember me</label>
              </div>
              <a class="float-right" href="forgot-password.html">Forgot password?</a>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
          </form>

          <p>No account? <a href="register-v2.html">Sign Up</a></p>

          <footer class="page-copyright">
            <p>WEBSITE BY Creation Studio</p>
            <p>© 2018. All RIGHT RESERVED.</p>
            <div class="social">
              <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
            <i class="icon bd-twitter" aria-hidden="true"></i>
          </a>
              <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
            <i class="icon bd-facebook" aria-hidden="true"></i>
          </a>
              <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
            <i class="icon bd-google-plus" aria-hidden="true"></i>
          </a>
            </div>
          </footer>
        </div>

      </div>
    </div>
    <!-- End Page -->


    <!-- Core  -->
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/babel-external-helpers/babel-external-helpers.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/jquery/jquery.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/popper-js/umd/popper.min.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/bootstrap/bootstrap.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/animsition/animsition.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/mousewheel/jquery.mousewheel.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/asscrollbar/jquery-asScrollbar.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/asscrollable/jquery-asScrollable.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/waves/waves.js"></script>
    
    <!-- Plugins -->
     <?php if(false){?>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/switchery/switchery.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/intro-js/intro.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/screenfull/screenfull.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/slidepanel/jquery-slidePanel.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/vendor/jquery-placeholder/jquery.placeholder.js"></script>
    <? }?>
    <!-- Scripts -->
    
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Component.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Plugin.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Base.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Config.js"></script>
   <?php if(false){?>
    <script src="<?php echo SITE_HTTP_URL?>/assets/base/assets/js/Section/Menubar.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/base/assets/js/Section/GridMenu.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/base/assets/js/Section/Sidebar.js"></script>
   <script src="<?php echo SITE_HTTP_URL?>/assets/base/assets/js/Section/PageAside.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/base/assets/js/Plugin/menu.js"></script>
    <? }?>
   
    
    <!-- Page -->
	<script src="<?php echo SITE_HTTP_URL?>/assets/base/assets/js/Site.js"></script>
    <?php if(false){?>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Plugin/asscrollable.js"></script>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Plugin/slidepanel.js"></script>
     <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Plugin/switchery.js"></script>
     
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Plugin/jquery-placeholder.js"></script>
    <? }?>
    <script src="<?php echo SITE_HTTP_URL?>/assets/global/js/Plugin/material.js"></script>
    
    <script>
      (function(document, window, $){
        'use strict';
    
        var Site = window.Site;
        $(document).ready(function(){
          Site.run();
        });
      })(document, window, jQuery);
    </script>
    
  </body>
</html>

