

<div class="index_part">
	<div class="top_back" style="background-image:url(<?php echo HTTP_SLIDER_IMAGES_PATH?>/<?php echo $this->HomePageData[0]['home_content']?>)">
    	<div class="top_back1">
        	<div class="heading">
            	<div class="homecontainer container" style="color:white;text-align:center;">
			
                		 <h2><b><?php echo $this->HomePageData[1]['home_content']?></b></h2>
                
                </div>            
            </div>
    	</div>
    </div><!---------------- top back is close ------------------------------------->
 <div class="container" style="margin-top:50px;margin-bottom:50px;">   <?php echo $this->HomePageData[2]['home_content']?></div>
   
    
 
    
    
    	   
    
    
    
    
</div>



