<div class="panel">
    	<div class="panel-body">

           <table class="table table-hover dataTable table-striped w-full table-bordered"  id="sample_1">
          <thead>
            <tr>
              <th width="6%"><?=$this->layout()->translator->translate("sno_txt")?></th>
              <th><?=$this->layout()->translator->translate("table_title_txt")?></th>
              <th><?=$this->layout()->translator->translate("subject_txt")?></th>
              <th width="18%"><?=$this->layout()->translator->translate("last_mod_txt")?></th>
              <th width="10%">Action</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
     </div>
 </div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(e) {
	
	$('#sample_1').DataTable({
		"language":{"lengthMenu": "Show _MENU_ records"},
		"bProcessing":true,
		"bServerSide":true,
		"bAutoWidth":false,
		"responsive":true,
		"bInfo":false,
		"pagingType":"first_last_numbers",
		"order":[[3,"desc"]],
		"aoColumnDefs":[
			{"bSortable":false,"aTargets":[0,3,4]},
			{"bSearchable":false,"aTargets":[1,2]}
		 ],
		 
		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/getemailtemplate" ,
		"iDisplayLength":50,
	    "aLengthMenu":[[10,50,100],[10,50,100]],
		
		
		"fnDrawCallback":function( oSettings ){}
	});
	
});
</script>