<div class="panel">

  <div class="panel-body">

          <table class="table table-hover dataTable table-striped w-full table-bordered"  id="sample_1">

          <thead>

            <tr>

              <th width="5%"><?=$this->layout()->translator->translate("sno_txt")?></th>

              <th width="30%"><?=$this->layout()->translator->translate("Heading")?></th>
              
              <th width="14%"><?=$this->layout()->translator->translate("Image/Video")?></th>

              <th width="8%"><?=$this->layout()->translator->translate("action_txt")?></th>

            </tr>

          </thead>

          <tbody  class="SortContentMain">

          </tbody>

        </table>

    </div>

  </div>



<script type="text/javascript" charset="utf-8">

$(document).ready(function(e) {



	$('#sample_1').DataTable({

		"language":{"lengthMenu": "Show _MENU_ records"},

		"bProcessing":true,

		"bServerSide":true,

		"bAutoWidth":false,

		"responsive":true,

		"bInfo":false,

		"pagingType":"first_last_numbers",

		"order":[[0,"desc"]],

		"aoColumnDefs":[

			{"bSortable":false,"aTargets":[2,3]},

			{"bSearchable":false,"aTargets":[2,3]}

		 ],

		  

		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/get-howitworks",

		"iDisplayLength":50,

	    "aLengthMenu":[[10,50,100],[10,50,100]],

		

		"fnDrawCallback":function( oSettings ){}

	});

	

});

</script>  

