<div class="panel">
  <div class="panel-body">
    <form method="post" action="<?php echo ADMIN_APPLICATION_URL?>/removesubcategorylist" id="userForm" onsubmit="return checkSelects('userForm')" >
    <div class="row">
        <div class="col-md-6 mb-15"> <a href="<?php echo ADMIN_APPLICATION_URL?>/managesubcategory" class="btn btn-primary waves-effect waves-classic"><i class="fa fa-plus"></i> Add Sub Category </a>&nbsp;&nbsp;
          <button class="btn btn-danger btn-rounded waves-effect waves-classic DeleteBtn"><span class="btn-label"><i class="fa fa-trash"></i></span>
          <?=$this->layout()->translator->translate("del_sel_txt")?>
          </button>
        </div>
      </div>
          <table class="table table-hover dataTable table-striped w-full table-bordered"  id="sample_1">
          <thead>
            <tr>
              <th width="5%"><?=$this->layout()->translator->translate("sno_txt")?></th>
              <th width="1%"><div class="checkbox"><input id="deletebcchk" name="deletebcchk" type="checkbox" class="group-checkable"><label for="deletebcchk"></label></div></th>
              <th width="30%"><?=$this->layout()->translator->translate("Category Title")?></th>
              <th width="14%"><?=$this->layout()->translator->translate("Sub Category Title")?></th>
              <th width="8%"><?=$this->layout()->translator->translate("action_txt")?></th>
            </tr>
          </thead>
          <tbody  class="SortContentMain">
          </tbody>
        </table>
        </form>
    </div>
  </div>
<script type="text/javascript" charset="utf-8">
$(document).ready(function(e) {
	$('#sample_1').DataTable({
		"language":{"lengthMenu": "Show _MENU_ records"},

		"bProcessing":true,

		"bServerSide":true,

		"bAutoWidth":false,

		"responsive":true,

		"bInfo":false,

		"pagingType":"first_last_numbers",

		"order":[[1,"desc"]],

		"aoColumnDefs":[

			{"bSortable":false,"aTargets":[0,1,4]},

			{"bSearchable":false,"aTargets":[1]}

		 ],

		  

		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/getsubcategorylist",

		"iDisplayLength":50,

	    "aLengthMenu":[[10,50,100],[10,50,100]],

		"fnDrawCallback":function( oSettings ){}

	});

	

});
</script>  