<div class="panel">

    	<div class="panel-body">

           <table class="table table-hover dataTable table-striped w-full table-bordered"  id="sample_1">

          <thead>

            <tr>

              <th width="6%"><?=$this->layout()->translator->translate("sno_txt")?></th>

              <th>Email Address</th>

              <th width="15%">Subscribed On</th>

            

            </tr>

          </thead>

          <tbody>

          </tbody>

        </table>

     </div>

</div>



<script type="text/javascript" charset="utf-8">

<?php 

$subscriberpath=APPLICATION_URL.'/'.BACKEND.'/getsubscribers';

if($this->subscriber_id!=''){

	$subscriberpath=APPLICATION_URL.'/'.BACKEND.'/getsubscribers/'.$this->subscriber_id;

}?>

$(document).ready(function(e) {

	$('#sample_1').DataTable({

		"language":{"lengthMenu": "Show _MENU_ templates"},

		"bProcessing":true,

		"bServerSide":true,

		"bAutoWidth":false,

		"responsive":true,

		"bInfo":false,

		"pagingType":"first_last_numbers",

		"order":[[2,"desc"]],

		"aoColumnDefs":[

			{"bSortable":false,"aTargets":[0,1]},

			{"bSearchable":false,"aTargets":[1,2]}

		 ],

		 

		"sAjaxSource": "<?php echo $subscriberpath?>" ,

		"iDisplayLength":50,

	    "aLengthMenu":[[10,50,100],[10,50,100]],

		dom: 'Bfrtip',

		buttons: [

			{

				extend: 'copy',

				text: "Copy",

				exportOptions: {

					

				},

			},

			{

				extend: 'csv',

				text: "CSV",

				exportOptions: {

					

				},

			},

		],

		"fnDrawCallback":function( oSettings ){}

	});

	

	

});

</script>





 

