<style type="text/css">
	.jq-star{cursor:default;}
</style>
<div class="panel">
  <div class="panel-body">
   <form method="post" action="<?php echo ADMIN_APPLICATION_URL?>/remove-rating" id="userForm" onsubmit="return checkSelects('userForm')" >
    <div class="row">
    	<div class="col-md-6 mb-15"> 
          <button class="btn btn-danger btn-rounded waves-effect waves-classic DeleteBtn"><span class="btn-label"><i class="fa fa-trash"></i></span>
          <?=$this->layout()->translator->translate("del_sel_txt")?>
          </button>
        </div>
      </div>
          <table class="table table-hover dataTable table-striped w-full table-bordered"  id="sample_1">
          <thead>
            <tr>
              <th width="5%"><?=$this->layout()->translator->translate("sno_txt")?></th>
              <th width="2%"><div class="checkbox"><input id="deletebcchk" name="deletebcchk" type="checkbox" class="group-checkable"><label for="deletebcchk"></label></div></th>
              <th width="12%"><?=$this->layout()->translator->translate("Review By")?></th>
              <th width="28%"><?=$this->layout()->translator->translate("Product Name")?></th>              
              <th width="14%"><?=$this->layout()->translator->translate("Seller Name")?></th>
              <th width="14%"><?=$this->layout()->translator->translate("Rating")?></th>
              <th width="14%" class="none"><?=$this->layout()->translator->translate("Review Text")?></th>
              <th width="14%" class="none"><?=$this->layout()->translator->translate("Uploaded Images:")?></th>
              <th width="14%"><?=$this->layout()->translator->translate("Date")?></th>
            </tr>
          </thead>
          <tbody  class="SortContentMain">
          </tbody>
        </table>
     </form>   
    </div>
  </div>
<script type="text/javascript" charset="utf-8">
$(document).ready(function(e) {
	$('#sample_1').DataTable({
		"language":{"lengthMenu": "Show _MENU_ records"},
		"bProcessing":true,
		"bServerSide":true,
		"bAutoWidth":false,
		"responsive":true,
		"bInfo":false,
		"pagingType":"first_last_numbers",
		"order":[[3,"desc"]],
		"aoColumnDefs":[
			{"bSortable":false,"aTargets":[0,5]},/*
			{"bSearchable":false,"aTargets":[5]}*/
		 ],
		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/get-reviews",
		"iDisplayLength":50,
	    "aLengthMenu":[[10,50,100],[10,50,100]],
		"fnDrawCallback":function( oSettings ){
			 $(".star-panel").starRating({
				minRating: 0.5,
				readOnly: true,
				ratedColor: '#f4a925',
  				activeColor: '#f4a925',
				emptyColor: '#bebebe',
				hoverColor: '#f4a925',
  				strokeWidth:0,
  				starSize: 23,
				useGradient: false,
				callback: function(currentRating, $el){
					$(".review_rate").val(currentRating);
    			}
			});
		}
	});
});	
</script>  

