<div class="panel">
  <div class="panel-body">
    <div class="clear20"></div>
    <form method="post" action="<?php echo ADMIN_APPLICATION_URL?>/remove-video-category" id="videocategoryForm" onsubmit="return checkSelects('videocategoryForm')" >
      <div class="row">
        <div class="col-md-6 mb-15"> <a href="<?php echo ADMIN_APPLICATION_URL?>/manage-video-category" class="btn btn-primary waves-effect waves-classic"><i class="fa fa-plus"></i> Add Video Category</a>&nbsp;&nbsp;
          <button class="btn btn-danger btn-rounded waves-effect waves-classic DeleteBtn"><span class="btn-label"><i class="fa fa-trash"></i></span>
          <?=$this->layout()->translator->translate("del_sel_txt")?>
          </button>
        </div>
      </div>

      <table class="table table-hover dataTable table-striped w-full table-bordered"  id="sample_1">
        <thead>
          <tr>
            <th width="5%"><?=$this->layout()->translator->translate("sno_txt")?></th>
            <th><div class="checkbox">
                <input id="deletebcchk" name="deletebcchk" type="checkbox" class="group-checkable">
                <label for="deletebcchk"></label>
              </div></th>
            <th width="40%">Title</th>
            <th width="40%">Created Date</th>
            <th width="8%"><?=$this->layout()->translator->translate("action_txt")?></th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </form>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(e) {
	$('#sample_1').DataTable({
		"language":{"lengthMenu": "Show _MENU_ records"},
		"bProcessing":true,
		"bServerSide":true,
		"bAutoWidth":false,
		"responsive":true,
		"bInfo":false,
		"pagingType":"first_last_numbers",
		//"order":[[4,"desc"]],
		"aoColumnDefs":[
			{"bSortable":false,"aTargets":[0,1,3,4]},
			{"bSearchable":false,"aTargets":[1,2,3,4]}
		 ],
	 
		"sAjaxSource": "<?php echo ADMIN_APPLICATION_URL; ?>/get-video-category-list-records" ,
		"iDisplayLength":50,
	    "aLengthMenu":[[10,50,100],[10,50,100]],

		"fnDrawCallback":function( oSettings ){}
	});

});
</script>