<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Account Settings</h4>
        <div class="border-gradient seller-btn"><a class="btn view-btn"> Become a Seller </a></div>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side comman-form">
            <form>
                  <div class="form-group">
                    <label >Old Password</label>
                    <input type="password" class="form-control" >
                  </div>
                  <div class="form-group">
                    <label >New Password</label>
                    <input type="password" class="form-control" >
                  </div>
                  <div class="form-group">
                    <label >Confirm New Password</label>
                    <input type="password" class="form-control" >
                  </div>
                
                
                <div class="border-gradient"><button type="button" class="btn view-btn send-btn" id="startedbtn">Submit</button></div>
            </form>


          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
