<div class="comman-section">
	<div class="container">
		<div class="common-heading">
			<h2 class="heading">CheckOut</h2>
		</div>
	</div>	
</div>


<div class="checkout-page">
  <div class="container">
      <form>
        <div class="shipping-detail">
          <h2 class="shipping-title"> Shipping Details </h2>
          <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                  <label >Your Name </label>
                  <input type="text" class="form-control" placeholder="" value="Your Name ">
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                  <label >Address</label>
                  <input type="text" class="form-control" placeholder="" value="Address">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                  <label >Postcode</label>
                  <input type="text" class="form-control" placeholder="" value="Postcode">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                  <label >City</label>
                  <input type="password" class="form-control" placeholder="" value="City"> 
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                  <label >State</label>
                  <input type="password" class="form-control" placeholder="" value="State">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                  <label >Phone Number</label>
                  <input type="password" class="form-control" placeholder="" value="000000">
                </div>
            </div>

            <div class="col-12"><button type="button" name="startedbtn" class="btn submit-btn" id="startedbtn" value=""><span>Submit</span></button></div>

          </div>
          <!-- row -->
        </div>
        <!-- shipping detail page -->
          <div class="amount-block">
              <div class="spider-img"></div>
              <div class="row">
                  <div class="col-xl-3 col-sm-4">
                      <div class="amount-box"> 
                        <p class="amount">$30.35</p>
                        <p class="amount-txt">Shipping Rate</p>
                      </div>
                  </div>
                  <!--  -->
                  <div class="col-xl-3 col-sm-4">
                      <div class="amount-box"> 
                        <p class="amount">$256.35</p>
                        <p class="amount-txt">Total Amount</p>
                      </div>
                  </div>
                  <!--  -->
              </div>
          </div>
          <!-- amount block -->

          <div class="payment-detail">
              <h2 class="shipping-title"> Your Payment Details </h2>

              <div class="radio-button-box">
                    <div class="radio-button">
                      <p class="m-0">
                        <input type="radio" id="test1" name="radio-group" class="rule-chkbox" value="1" checked="">
                        <label for="test1"> <span class="card-icon"><img src="<?=HTTP_IMG_PATH?>/card-img.png"> </span> </label>
                      </p>
                      <p class="m-0">
                        <input type="radio" id="test2" name="radio-group" class="rule-chkbox" value="2">
                        <label for="test2"> <span class="paypal-icon"> <img src="<?=HTTP_IMG_PATH?>/paypal.png"> </span> </label>
                      </p>
                    </div>
                </div>

              <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                      <label >Name on Card</label>
                      <input type="text" class="form-control" placeholder="Name on Card" value="">
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="form-group">
                      <label >Postcode</label>
                      <input type="text" class="form-control" placeholder="Card Number" value="">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                      <label >Expiration Date</label>
                      <div class="row">
                          <div class="col-sm-6">
                            <select class="form-control custom-select mb-3 mb-sm-0">
                              <option selected>01</option>
                              <option>...</option>
                            </select>
                          </div>
                          <div class="col-sm-6">
                            <select class="form-control custom-select">
                              <option selected>2020</option>
                              <option>...</option>
                            </select>
                          </div>
                      </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                      <label >CVV</label>
                      <input type="password" class="form-control" placeholder="CVV" value="">
                    </div>
                </div>
                <div class="col-12"><button type="button" name="startedbtn" class="btn submit-btn checkout-btn" id="startedbtn" value=""><span>Checkout</span></button></div>
              </div>
          </div>
          <!--  -->
      </form>
      <!-- form -->
  </div>
</div>
