<div class="profile_page dashboard-page">
  <div class="profile-section">
    <div class="profile-nav d-none d-xl-block">
      <div class="change-image-user-box">
          <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
          <p class="user-name">Jamie Lynn</p>
          <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
      </div>

      <div class="side-nav">
        <ul class="side-nav-ul">
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Account Settings </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Manage Coupons </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
        </ul>
      </div>
      <!-- change user image -->
    </div>
    <!--  -->

    <div class="right-side-block">

      <div class="heading-box">
        <h4 class="heading">Manage Shop</h4>
        <div class="border-gradient seller-btn return-btn"><a class="btn view-btn"> Return to Marketplace </a></div>
      </div>
      <!-- heading box -->

      <div class="right-side comman-form">

            <!--  -->

            <div class="strange-box">
               <p class="welcome-txt">Welcome Evie Strange </p>
               <a href="#" class="web-link">  <img src="<?=HTTP_IMG_PATH?>/url.svg">  <span>https://www.thecollectivecoven/seller-profile/NzU</span> </a>
            </div>

            <div class="stats-box">
              <form class="form-inline">
                <label class="" >Stats overview for</label>
                <select class="custom-select" >
                  <option selected>Choose...</option>
                  <option value="1">One</option>
                  <option value="2">Two</option>
                  <option value="3">Three</option>
                </select>
              </form>
            </div>

            <div class="row">
              <div class="col-md-4 col-sm-6 ">
                <div class="count-box">
                  <div class="box-1">
                      <div class="icon-box"><img src="<?=HTTP_IMG_PATH?>/interface1.svg">  </div>
                      <div class="counting-block">
                          <h3 class="title"> TOTAL VIEWS </h3>
                          <p class="numbers"> 16 </p>
                      </div>
                  </div>
                  <div class="color-box"></div>
                </div>
                <!--  -->
              </div>
              <!--  -->
              <div class="col-md-4 col-sm-6">
                <div class="count-box">
                  <div class="box-1">
                      <div class="icon-box"><img src="<?=HTTP_IMG_PATH?>/open.svg">  </div>
                      <div class="counting-block">
                          <h3 class="title"> orders  </h3>
                          <p class="numbers"> 10 </p>
                      </div>
                  </div>
                  <div class="color-box color-box2"></div>
                </div>
                <!--  -->
              </div>
              <!--  -->
              <div class="col-md-4 col-sm-6">
                <div class="count-box">
                  <div class="box-1">
                      <div class="icon-box"><img src="<?=HTTP_IMG_PATH?>/business-and-finance.svg">  </div>
                      <div class="counting-block">
                          <h3 class="title"> earning </h3>
                          <p class="numbers"> $250 </p>
                      </div>
                  </div>
                  <div class="color-box color-box3"></div>
                </div>
                <!--  -->
              </div>
              <!--  -->

            </div>

            <!--  -->

            <!-- apply your HTML -->
            <form>
              <div class="form-group">
                    <label >Store Name</label>
                    <input type="text" class="form-control" value="Store Name" >
                  </div>
                  <div class="form-group">
                    <label >Company Legal Name</label>
                    <input type="text" class="form-control" value="Company Legal Name">
                  </div>
                  <div class="form-group">
                    <label >Contact Person</label>
                    <input type="text" class="form-control" value="Contact Person">
                  </div>
                  <div class="form-group">
                    <label >Location</label>
                    <input type="text" class="form-control" value="Location" >
                  </div>

                  <div class="logo-upload-box">
                    <p class="logo-title"> Logo </p>
                    <div class="logo-img"> <img src="<?=HTTP_IMG_PATH?>/photo.svg">  </div>
                    <div class="upload-btn btn"> Upload </div>
                    <div class="upload-btn remove-btn btn"> Remove </div>
                  </div>


                  <div class="logo-upload-box">
                    <p class="logo-title"> Banner Image </p>
                    <div class="logo-img"> <img src="<?=HTTP_IMG_PATH?>/photo.svg">  </div>
                    <div class="upload-btn btn"> Upload </div>
                    <div class="upload-btn remove-btn btn"> Remove </div>
                  </div>

                  <div class="border-gradient"><button type="button" class="btn view-btn send-btn" id="startedbtn"> Get Verified </button></div>

                  <div class="verified-box">
                    <h2 class="titles"> Get Verified </h2>

                    <div class="form-group">
                      <label >Location</label>
                      <div class="custom-file">
                        <input type="file" class="custom-file-input form-control" id="customFileLang" lang="es">
                        <label class="custom-file-label" for="customFileLang">Upload Document </label>
                      </div>
                    </div>

                    <div class="form-group">
                      <label >Location</label>
                      <div class="custom-file">
                        <input type="file" class="custom-file-input form-control" id="customFileLang" lang="es">
                        <label class="custom-file-label" for="customFileLang">Upload Document </label>
                      </div>
                    </div>


                    <div class="form-group">
                      <label >Location</label>
                      <div class="custom-file">
                        <input type="file" class="custom-file-input form-control" id="customFileLang" lang="es">
                        <label class="custom-file-label" for="customFileLang">Upload Document </label>
                      </div>
                    </div>




              </div>
              <div class="border-gradient submit-btn"><button type="button" class="btn view-btn " id="startedbtn"> Submit </button></div>
              <p class="approval-text">Admin will review the details submitted by you and after approval you can upload your products.</p>
            </form>
            <!-- apply your HTML -->

          </div>

    </div>

    <!-- right-side-block -->

  </div>
</div>



