<div class="login_page profile_page manage-product-page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Manage Product</h4>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Coupons </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side">
              <div class="manage-product-box manage-product-box2">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>

                    <div class="status-icon-box">
                      <div class="product-pricing-box">
                        <p class=""> <span> Price : </span> <span> $250 </span> </p>
                        <p class=""> <span> Available Quantity : </span> <span> 200 </span> </p>
                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="manage-product-box manage-product-box2">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="status-icon-box">
                      <div class="product-pricing-box">
                        <p class=""> <span> Price : </span> <span> $250 </span> </p>
                        <p class=""> <span> Available Quantity : </span> <span> 200 </span> </p>
                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="manage-product-box manage-product-box2">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="status-icon-box">
                      <div class="product-pricing-box">
                        <p class=""> <span> Price : </span> <span> $250 </span> </p>
                        <p class=""> <span> Available Quantity : </span> <span> 200 </span> </p>
                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="manage-product-box manage-product-box2">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="status-icon-box">
                      <div class="product-pricing-box">
                        <p class=""> <span> Price : </span> <span> $250 </span> </p>
                        <p class=""> <span> Available Quantity : </span> <span> 200 </span> </p>
                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>

