<div class="login_page profile_page manage-product-page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Manage Product</h4>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Coupons </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side">
              <div class="manage-product-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="product-pricing-box">
                      <p class=""> <span> Price : </span> <span> $250 </span> </p>
                      <p class=""> <span> Available Quantity : </span> <span> 200 </span> </p>
                    </div>
                    <div class="status-icon-box">
                      <div class="status-box">
                          <p class="status-text"> <span> Status : </span> <span class="watting-text">  Waiting for admin approval</span> </p>

                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="manage-product-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="product-pricing-box">
                      <p class=""> <span> Price : </span> <span> $250 </span> </p>
                      <p class=""> <span> Available Quantity : </span> <span> 200 </span> </p>
                    </div>
                    <div class="status-icon-box">
                      <div class="status-box">
                          <p class="status-text"> <span> Status : </span> <span class="watting-text">Approved</span> </p>

                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="manage-product-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="product-pricing-box">
                      <p class=""> <span> Price : </span> <span> $250 </span> </p>
                      <p class=""> <span> Available Quantity : </span> <span> 200  </span> </p>
                    </div>
                    <div class="status-icon-box">
                      <div class="status-box d-flex">
                          <p class="status-text"> <span> Status : </span> <span class="watting-text"> Decline</span> </p>
                          <a href="#" class="btn decline-btn" data-toggle="modal" data-target="#declineModal"> Reason of Decline </a>
                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="manage-product-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="product-detail-box">
                    <h2 class="product-heading"> Product Title </h2>
                    <p class="product-category">Category name here</p>
                    <div class="product-pricing-box">
                      <p class=""> <span> Price : </span> <span> $250 </span> </p>
                      <p class=""> <span> Available Quantity : </span>  <span> 200 </span> </p>
                    </div>
                    <div class="status-icon-box">
                      <div class="status-box">
                          <p class="status-text"> <span> Status : </span> <span class="watting-text">  Waiting for admin approval</span> </p>

                      </div>
                      <div class="icons-box d-flex">
                          <div class="icons edit"> <img src="<?=HTTP_IMG_PATH?>/edit.svg"> </div>
                          <div class="icons delete"> <img src="<?=HTTP_IMG_PATH?>/delete.svg"> </div>
                      </div>
                      <!-- icons box -->
                    </div>
                  </div>
              </div>
              <!-- manage-product box -->
          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>





<!-- modal -->


<div class="modal fade" id="declineModal" tabindex="-1" role="dialog" aria-labelledby="declineModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title heading" id="declineModalLabel">Reason of Decline <img src="<?=HTTP_IMG_PATH?>/bat.png"> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">X</span>
        </button>
      </div>
      <div class="modal-body">
          <p class="modal-description"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
          <p class="modal-description"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
      </div>
      
    </div>
  </div>
</div>