<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading"> Message </h4>
        <div class="border-gradient seller-btn back-btn"><a class="btn view-btn"> Back </a></div>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side message-page">
            <!--  -->

            <div class="chat-box" id="message6">
                        <div class="message-window">
                            <div class="left-box">
                                <div class="avatar"><img src="<?=HTTP_IMG_PATH?>/user-img.jpg"></div>
                                <div class="text_wrapper">
                                    <div class="message-content">
                                      <div class="text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </div>
                                    </div>
                                    <div class="dates">10:00 AM</div>
                                </div>
                            </div>
                            
                            <div class="right-box">     
                                <div class="text_wrapper">
                                  <div class="message-content">
                                    <div class="text">Lorem Ipsum is simply dummy text of the printing and typesetting industry.   </div>
                                  </div>
                                  <div class="dates">10:30 AM</div>
                                </div>
                                <!-- <div class="avatar"><img src="<?=HTTP_IMG_PATH?>/user-img.jpg"></div> -->
                            </div>
                        </div>

                        <div class="message-type-window">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="exampleInputAmount" placeholder="Type a message">
                                    <div class="input-group-addon"><img src="<?=HTTP_IMG_PATH?>/send.svg"></div>
                                </div>
                            </form>
                        </div>
                    </div>



            <!--  -->
          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
