

<div class="product-detail-page">
	<div class="container">
		<div class="first-block">
			<div class="row m-0">
				<div class="first-left-panel">
					<div class="slider-data parent-container">
						<!----------------slider---------------------->
						<div id="MainDiv" data-effect="mfp-zoom-in">
							<a href="<?=HTTP_IMG_PATH?>/product-img1.jpg"><img src="<?=HTTP_IMG_PATH?>/product-img1.jpg" alt="About Us" id="MainImage" width="100%" height="100%"/></a>
						</div>
						<div class="main-slider">
							<div id="slider">
								<ul class="slides " >
									<li class="slide active" data-effect="mfp-zoom-in">
										<a href="<?=HTTP_IMG_PATH?>/product-img1.jpg"><img src="<?=HTTP_IMG_PATH?>/product-img1.jpg" alt="Image 1" /></a>
									</li>
									<li class="slide" data-effect="mfp-zoom-in">
										<a href="<?=HTTP_IMG_PATH?>/slider1.jpg"><img src="<?=HTTP_IMG_PATH?>/slider1.jpg" alt="Image 2" /></a>
									</li>
									<li class="slide" data-effect="mfp-zoom-in">
										<a href="<?=HTTP_IMG_PATH?>/blog-detail.jpg"><img src="<?=HTTP_IMG_PATH?>/blog-detail.jpg" alt="Image 3"/></a>
									</li>
									<li class="slide" data-effect="mfp-zoom-in">
										<a href="<?=HTTP_IMG_PATH?>/blog-img3.jpg"><img src="<?=HTTP_IMG_PATH?>/blog-img3.jpg" alt="Image 4"/></a>
									</li>
									<li class="slide" data-effect="mfp-zoom-in">
										<a href="<?=HTTP_IMG_PATH?>/img-3.jpg"><img src="<?=HTTP_IMG_PATH?>/img-3.jpg" alt="Image 5"/></a>
									</li>      
									<li class="slide" data-effect="mfp-zoom-in">
										<a href="<?=HTTP_IMG_PATH?>/zombie.jpg"><img src="<?=HTTP_IMG_PATH?>/zombie.jpg" alt="Image 6"/></a>
									</li> 
								</ul>
									
							</div>
							<div id="child" class="d-block">
								<img id="Next" src="<?=HTTP_IMG_PATH?>/bat-2.png"  class="img-responsive NextButton"/>
								<img id="Previous" src="<?=HTTP_IMG_PATH?>/bat-2.png"  class="img-responsive PreButton"/>
							</div>
						</div>
						<!------------------------------------------->
					</div>
				</div>
				<!-- col -->
				<div class="first-right-panel">
						<div class="product-detail">
							<div class="left-block">
								<div class="product-detail-box">
									<h2 class="product-heading"> Product Title </h2>
									<p class="product-category">Category name here</p>
									<div class="star-list">
										<ul class="star-ul-list">
											<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
											<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
											<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
											<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
											<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										</ul>
									</div>
									<div class="product-pricing-box">
										<p class=""> <span> Price : </span> <span> $250 </span> </p>
										<p class=""> <span> Available Quantity : </span>  <span> 200 </span> </p>
									</div>
									<div class="button-box d-flex">
										<div class="comman-btns add-wish-btn ml-0"><a href="#" class="btn "> Add to Wish List  </a></div>
										<div class="comman-btns mr-0 border-gradient"><a href="#" class="btn add-cart-btn view-btn" data-toggle="modal" data-target="#addcartModal"> Add to Cart </a></div>
									</div>
									<div class="price-suggestion">
										<p>Click <a href="javascript:void(0)">here</a> to know the best offers.</p>
									</div>
									<div class="icons-box d-flex">
										<a class="icons" href="#"> <span>Share</span> <img src="<?=HTTP_IMG_PATH?>/share.svg"> </a>
										<a class="icons" href="#"> <span>Report</span> <img src="<?=HTTP_IMG_PATH?>/red-flag.svg"> </a>
									</div>
								</div>
								<!-- product detial box -->
							</div>
							<!-- left block -->

							<div class="right-block">
								<div class="seller-info">
									<h5 class="seller-title"> Seller Info: </h5>

									<div class="seller-info-box">
										<div class="seller-img"> <img src="<?=HTTP_IMG_PATH?>/user-img1.jpg"> </div>
										<div class="">
											<p class="seller-name"> Chris Evans</p>
											<p class="seller-company"> Company Name </p>

											<div class="border-gradient "><a href="#" class="btn seller-profile-btn"> Seller Profile </a> </div>

										</div>
										<!--  -->
									</div>

								</div>
							</div>
							<!-- right block -->
						</div>
						<div class="description-box-one">
							<p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
								<br>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
								Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
							</p>
						</div>
				</div>
				<!-- col -->

			</div>
		</div>
		<!-- first block -->
		<div class="review-and-rating-box ">
			<h2 class="heading">Review and Rating</h2>
			<div class="rating-data">
				<div class="first-section">
					<div class="rating-panel">
						<div class="common-rating-box">
							<div class="media media-section">
								<div class="review-img"><img src="<?=HTTP_IMG_PATH?>/user-img1.jpg"> </div>
								<div class="media-body">
									<h5 class="title">Name here</h5>
									<ul class="star-ul-list">
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
									</ul>
								</div>
							</div>
							<a href="#" class="report"><span>Report</span> <img src="<?=HTTP_IMG_PATH?>/red-flag.svg"></a>
						</div>
						<p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
					</div>
				</div>
				<div class="first-section">
					<div class="rating-panel">
						<div class="common-rating-box">
							<div class="media media-section">
								<div class="review-img"><img src="<?=HTTP_IMG_PATH?>/user-img-3.jpg"> </div>
								<div class="media-body">
									<h5 class="title">Name here</h5>
									<ul class="star-ul-list">
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star-bg.svg"> </li>
									</ul>
								</div>
							</div>
							<a href="#" class="report"><span>Report</span> <img src="<?=HTTP_IMG_PATH?>/red-flag.svg"></a>
						</div>
						<p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
					</div>
				</div>
				<div class="first-section">
					<div class="rating-panel">
						<div class="common-rating-box">
							<div class="media media-section">
								<div class="review-img"><img src="<?=HTTP_IMG_PATH?>/user-img2.jpg"> </div>
								<div class="media-body">
									<h5 class="title">Name here</h5>
									<ul class="star-ul-list">
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
									</ul>
								</div>
							</div>
							<a href="#" class="report"><span>Report</span> <img src="<?=HTTP_IMG_PATH?>/red-flag.svg"></a>
						</div>
						<p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
					</div>
				</div>
				<div class="first-section">
					<div class="rating-panel">
						<div class="common-rating-box">
							<div class="media media-section">
								<div class="review-img"><img src="<?=HTTP_IMG_PATH?>/user-img3.jpg"> </div>
								<div class="media-body">
									<h5 class="title">Name here</h5>
									<ul class="star-ul-list">
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
										<li class=""> <img src="<?=HTTP_IMG_PATH?>/star-bg.svg"> </li>
									</ul>
								</div>
							</div>
							<a href="#" class="report"><span>Report</span> <img src="<?=HTTP_IMG_PATH?>/red-flag.svg"></a>
						</div>
						<p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
					</div>
				</div>
			</div>
			<div class="comman-btns  border-gradient"><a href="#" class="btn add-cart-btn view-btn"> Load More </a></div>
		</div>
		<!-- review-and-rating-box -->

		<div class="Familiar-conjuring">
			<h2 class="heading">Familiar Conjurings<img src="<?=HTTP_IMG_PATH?>/bat.png"></h2>
			<div class="owl-carousel two">
				<?php for($k=0; $k<2; $k++){ ?>
				<div class="item">
					<div class="card menu-card">
						<div class="slider-img"><img class="card-img-top" src="<?=HTTP_IMG_PATH?>/slider.jpg" alt="Card image cap"></div>
						<div class="card-body">
							<h4 class="card-title">Product name here <span>$57.87</span></h4>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="card menu-card">
					<div class="slider-img"><img class="card-img-top" src="<?=HTTP_IMG_PATH?>/img-3.jpg" alt="Card image cap"></div>
						<div class="card-body">
							<h4 class="card-title">Product name here <span>$57.87</span></h4>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="card menu-card">
					<div class="slider-img"><img class="card-img-top" src="<?=HTTP_IMG_PATH?>/slider2.jpg" alt="Card image cap"></div>
						<div class="card-body">
							<h4 class="card-title">Product name here <span>$57.87</span></h4>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="card menu-card">
					<div class="slider-img"><img class="card-img-top" src="<?=HTTP_IMG_PATH?>/slider3.jpg" alt="Card image cap"></div>
						<div class="card-body">
							<h4 class="card-title">Product name here <span>$57.87</span></h4>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="card menu-card">
					<div class="slider-img"><img class="card-img-top" src="<?=HTTP_IMG_PATH?>/product-img1.jpg" alt="Card image cap"></div>
						<div class="card-body">
							<h4 class="card-title">Product name here <span>$57.87</span></h4>
						</div>
					</div>
				</div>
				<? } ?>
			</div>

		</div>
	
		<!------------------>
	</div>
</div>
<!-- product detail page -->



<!-- modal -->


<div class="modal add-to-cart-modal fade" id="addcartModal" tabindex="-1" role="dialog" aria-labelledby="addcartModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addcartModalLabel">Cart</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
		<div class="media">
			<img class="product-img" src="<?=HTTP_IMG_PATH?>/product-img1.jpg" alt="image">
			<div class="media-body">
					<div class="">
						<h2 class="product-name"> Product Title</h2>
						<p class="category-name">Category name here</p>
						<div class="qty-box"> 
							<div class="quant-box">
								<label>QTY</label>
								<div class="input-group">	
									<span class="input-group-btn">
									<button type="button" class="btn btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
										<i class="fas fa-minus"></i>
									</button>
									</span>
									<input type="text" name="quant[1]" class="input-number" value="1" min="1" max="10">
									<span class="input-group-btn">
									<button type="button" class="btn btn-number" data-type="plus" data-field="quant[1]">
										<i class="fas fa-plus"></i>
									</button>
									</span>
								</div>

							</div>
							<p class="amount">$250</p>
						</div>
						<div class="coupon">
							<form>
								<div class="form-group">
									<label class="">Coupon Code</label>
									<input type="" class="form-control">
								</div>
								<button type="submit" class="btn apply-btn">Apply</button>
							</form>
						</div>
					</div>
			</div>
		</div>
		<!-- media -->
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="cancle-btn btn">Cancle</button>
        <button type="button" class="btn  add-cart-btn view-btn">Add to Cart</button>
      </div>
    </div>
  </div>
</div>













<script type="text/javascript" src="http://192.168.0.98/Thecollectivecoven/assets/plugins/customscroolbar/mcustomscroolbar.js"></script>
<script>
$('.description-box-one').mCustomScrollbar({theme:"dark-3"});
</script>

<script>
$(document).ready(function(){
	
	$('.owl-carousel.two').owlCarousel({
		loop:true,
		margin:10,
		nav:true,
		navText: ["<div class='prev' ><img src='<?=HTTP_IMG_PATH?>/bat-2.png' class='img-back'></div>",
				"<div class='prev next' ><img src='<?=HTTP_IMG_PATH?>/bat-2.png' class='img-back'></div>"],
		responsive:{
			0:{
				items:1
			},
			600:{
				items:2
			},
			1000:{
				items:2
			},
			1300:{
				items:5
			}
		}
	});

	
});	


</script>

<!--  -->
<script>


$('.btn-number').click(function(e){
    e.preventDefault();
    
    fieldName = $(this).attr('data-field');
    type      = $(this).attr('data-type');
    var input = $("input[name='"+fieldName+"']");
    var currentVal = parseInt(input.val());
    if (!isNaN(currentVal)) {
        if(type == 'minus') {
            
            if(currentVal > input.attr('min')) {
                input.val(currentVal - 1).change();
            } 
            if(parseInt(input.val()) == input.attr('min')) {
                $(this).attr('disabled', true);
            }

        } else if(type == 'plus') {

            if(currentVal < input.attr('max')) {
                input.val(currentVal + 1).change();
            }
            if(parseInt(input.val()) == input.attr('max')) {
                $(this).attr('disabled', true);
            }

        }
    } else {
        input.val(0);
    }
});
$('.input-number').focusin(function(){
   $(this).data('oldValue', $(this).val());
});
$('.input-number').change(function() {
    
    minValue =  parseInt($(this).attr('min'));
    maxValue =  parseInt($(this).attr('max'));
    valueCurrent = parseInt($(this).val());
    
    name = $(this).attr('name');
    if(valueCurrent >= minValue) {
        $(".btn-number[data-type='minus'][data-field='"+name+"']").removeAttr('disabled')
    } else {
        alert('Sorry, the minimum value was reached');
        $(this).val($(this).data('oldValue'));
    }
    if(valueCurrent <= maxValue) {
        $(".btn-number[data-type='plus'][data-field='"+name+"']").removeAttr('disabled')
    } else {
        alert('Sorry, the maximum value was reached');
        $(this).val($(this).data('oldValue'));
    }
    
    
});
$(".input-number").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
             // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) || 
             // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
                 // let it happen, don't do anything
                 return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });


</script>

<script>
	
   var tn_array = $(".slides img").map(function () {
        return $(this).attr("src");
    }).get();

    $('#MainImage').attr('src', tn_array[0]); // set first image of the list as the MainImage src
    // $('#Previous').css("visibility", "hidden"); 

    var lengthImages = tn_array.length; // Length of the image list
    var CurrImage = 0; // Keep current Image index
    var widthImg = 200; // Width of a image in the list 
    var BottomLength = 4; // How many images currently shows in the bottom slide
    var IndexDiff;  //This variable is used in the bottom slider click event 
        //as a reference for animate the slider

        $('#Next').click(function () {
    $('#MainImage').fadeOut('slow', function () {
        CurrImage = CurrImage + 1; // Update current image index
        $('#slider .slides').animate({ 'margin-left': '-=' +
        widthImg}, 1000); //animate left margin of the slides list with the value
                //of -widthImg (-200px). So the bottom slider will animate to left side
        $('#MainImage').attr('src', tn_array[CurrImage]); // set next image to Main image
        // if (CurrImage == lengthImages - BottomLength) { //This condition is checking
        //                 //whether the bottom slider has comes to end or not.
        //     $('#Next').css("visibility", "hidden"); // if true then hide
        // }
        // if ($('#Previous').css("visibility") ==
        //         "hidden") { // if Previous button is hidden
        //     $('#Previous').css("visibility",
        //         "visible"); //then set it to visible
        // }
    }).fadeIn(1000);
    });

    $('#Previous').click(function () {
    $('#MainImage').fadeOut('slow', function () {
        CurrImage = CurrImage - 1; // Update the current image index
        $('#slider .slides').animate({ 'margin-left': '+=' + widthImg },
            1000); //animate the bottom slider with += widthImg, it will animate the slider to right
        $('#MainImage').attr('src', tn_array[CurrImage]); // set corresponding image to main image
        // if (CurrImage == 0) { // if current slide is the first image
        //     $('#Previous').css("visibility", "hidden"); // then hide the previous button
        // }
        // if ($('#Next').css("visibility") == "hidden") { // if next button is hidden
        //     $('#Next').css("visibility", "visible"); // then set it to visible
        // }

    }).fadeIn(1000);
});


$('.slides li img').click(function () {
       var Imagesrc = $(this).attr('src'); // get the selected image src
       var ImageIndex = $(this).parent('.slide').index(); // get the selected list item index

       $('#MainImage').fadeOut('slow', function () {
           if (ImageIndex <= lengthImages - BottomLength) { // this condition checks
                   //whether the bottom slider has come to the end or not.
                   //Also this will prevent sliding bottom slider to the left.
               IndexDiff = CurrImage; // Assign Current image index to IndexDiff temporary
               CurrImage = ImageIndex; // Assign selected image index to current image value
               IndexDiff = Math.abs(IndexDiff - CurrImage); // get the difference
               $('#slider .slides').animate({ 'margin-left': '-=' +
                   widthImg * IndexDiff }, 1000); // slide the bottom slider to left by setting
                               //left margin to (widthImg * IndexDiff) pixels.
               $('#MainImage').attr('src', Imagesrc); // set selected image source as main image

            //    if (ImageIndex != 0) { // image index is not equals to zero
            //        if ($('#Previous').css("visibility") == "hidden") { // if previous button is hidden
            //            $('#Previous').css("visibility", "visible"); //set it to visible
            //        }
            //    }
            //    if (ImageIndex == lengthImages - BottomLength) { // check whether the
            //                    // slider has come to end or not
            //        if ($('#Next').css("visibility") == "visible") { // if visible
            //            $('#Next').css("visibility", "hidden"); // hide next button
            //        }
            //    }
           }
           else { // if bottom slider has come to end
               $('#MainImage').attr('src', Imagesrc); // set the image source only.
                           // No need to update the image index
           }
           }).fadeIn(1000);
   });




$(document).ready(function(){
	$('.parent-container').magnificPopup({
		delegate: 'a', // child items selector, by clicking on it popup will open
		type: 'image',
		closeBtnInside: false,
    	closeOnContentClick: false,
		gallery:{
			enabled:true
		},
		zoom: {
			enabled: true, // By default it's false, so don't forget to enable it

			duration: 300, // duration of the effect, in milliseconds
			easing: 'ease-in-out', // CSS transition easing function

			// The "opener" function should return the element from which popup will be zoomed in
			// and to which popup will be scaled down
			// By defailt it looks for an image tag:
			opener: function(openerElement) {
			// openerElement is the element on which popup was initialized, in this case its <a> tag
			// you don't need to add "opener" option if this code matches your needs, it's defailt one.
			return openerElement.is('img') ? openerElement : openerElement.find('img');
			}
		}
	});
});




</script>
