<div class="product-list-page">
	<div class="container">
		<div class="product-select-box">
			<div class="select-boxes">
				<div class="boxes categories">
					<div class="mb-0">
						<select class="custom-select">
							<option selected>Categories</option>
							<option value="1">One</option>
							<option value="2">Two</option>
							<option value="3">Three</option>
						</select>
					</div>

				</div>
				<div class="boxes filter-box">
					<!--  -->

					<a class="filter-btn collapsed" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"> FILTERS  </a>
				


					<!--  -->
				</div>
				<!-- filterbox -->
				<div class="boxes categories shortby">
					<div class="mb-0">
						<select class="custom-select">
							<option selected>Sort by</option>
							<option value="1">One</option>
							<option value="2">Two</option>
							<option value="3">Three</option>
						</select>
					</div>

				</div>
			</div>
			<!-- select boxes -->

			<div class="collapse filter-collapese-box" id="collapseExample">
				<div class="card card-body">
					<div class="filter-forms">
						<form>
							<div class="row m-0">
								<div class="col-lg-6 pl-lg-0">
									<div class="form-group form-row align-items-center">
										<label for="" class="col-xl-5 col-lg-6 col-form-label"> Search by product seller name : </label>
										<div class="col-xl-7 col-lg-6">
										<input type="text" class="form-control" id="">
										</div>
									</div>
								</div>
								
								<div class="col-lg-6 pr-lg-0">
									<div class="form-group form-row align-items-center">
										<label for="" class="col-xl-5 col-lg-6 col-form-label">Search by country or location :</label>
										<div class="col-xl-7 col-lg-6">
										<input type="text" class="form-control">
										</div>
									</div>
								</div>

								<div class="col-lg-6 pl-lg-0">
									<div class="form-group form-row">
										<label for="" class="col-xl-5 col-lg-6 col-form-label">Price range :</label>
										<div class="col-xl-7 col-lg-6">
											<div class="range">
												<input type="text" class="js-range-slider" name="my_range" value=""
													data-type="double"
													data-min="0"
													data-max="1000"
													data-from="200"
													data-to="500"
													data-grid="true"/>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-6 pr-lg-0">
									<div class="filter-form-buttons">
										<button type="submit" class="btn search-btn">Search</button>
										<button type="submit" class="btn reset-btn">Reset</button>
									</div>
								</div>

							</div>
						</form>
					</div>
					<!-- filter form -->
				</div>
			</div>

		</div>
		<!-- product-select-box -->

		<div class="product-list">
			<div class="row">
				<?php for ($x = 0; $x <= 5; $x++) { ?>
				<div class="col-lg-6">
					<div class="manage-product-box">
						<div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
						<div class="product-detail-box">
							<h2 class="product-heading"> Product Title </h2>
							<p class="product-category">Category name here</p>
							<div class="star-list">
								<ul class="star-ul-list">
									<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
									<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
									<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
									<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
									<li class=""> <img src="<?=HTTP_IMG_PATH?>/star.svg"> </li>
								</ul>
							</div>
							<div class="product-pricing-box">
								<p class=""> <span> Price : </span> <span> $250 </span> </p>
								<p class=""> <span> Available Quantity : </span>  <span> 200 </span> </p>
							</div>
							
							<div class="button-box d-flex">
								<div class="comman-btns view-detail-btn ml-0"><a href="#" class="btn "> View Details </a></div>
								<div class="comman-btns mr-0 border-gradient"><a href="#" class="btn add-cart-btn view-btn"> Add to Cart </a></div>
							</div>
							
						</div>
					</div>


				</div>
				<? } ?>
				<!-- first col -->
			</div>
			<!-- row -->

			<nav aria-label="Page navigation example">
				<ul class="pagination">
					<li class="page-item">
					<a class="page-link" href="#" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						<span class="sr-only">Previous</span>
					</a>
					</li>
					<li class="page-item"><a class="page-link active" href="#">1</a></li>
					<li class="page-item"><a class="page-link" href="#">2</a></li>
					<li class="page-item"><a class="page-link" href="#">3</a></li>
					<li class="page-item"><a class="page-link" href="#">4</a></li>
					<li class="page-item"><a class="page-link" href="#">5</a></li>
					<li class="page-item">
					<a class="page-link" href="#" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
						<span class="sr-only">Next</span>
					</a>
					</li>
				</ul>
			</nav>


			<!--  pagination -->
		</div>
	</div>
</div>






<script>


$(document).ready(function(){	
$(".js-range-slider").ionRangeSlider({
        type: "double",
        min: 0,
        max: 1000,
        from: 200,
        to: 500,
        grid: true
    });
});
</script>