<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Account Settings</h4>
        <div class="border-gradient seller-btn"><a class="btn view-btn"> Become a Seller </a></div>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side comman-form">
            <form>
              <div class="form-row">
                  <div class="form-group col-sm-6">
                    <label >First Name</label>
                    <input type="text" class="form-control" value="Jamie" >
                  </div>
                  <div class="form-group col-sm-6">
                    <label >Last Name</label>
                    <input type="text" class="form-control" value="Lynn">
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-group col-sm-6">
                    <label >User Name</label>
                    <input type="text" class="form-control" value="Jamie20">
                  </div>
                  <div class="form-group col-sm-6">
                    <label>Email</label>
                    <input type="email" class="form-control" value="jamie20@gmail.com">
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-group col-sm-6">
                    <label >Location</label>
                    <input type="text" class="form-control" value="Sydney, NSW, Australia ">
                  </div>
                  <div class="form-group col-sm-6">
                    <label > Gender </label>
                    <select class="custom-select form-control">
                      <option selected>Male</option>
                      <option value="1">Female</option>
                      <option value="2">Other</option>
                    </select>
                  </div>
                </div>
                <div class="border-gradient"><button type="button" class="btn view-btn send-btn" id="startedbtn">Submit</button></div>
            </form>


          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
