<div class="profile_page manage-product-page quick-edit-page">
  <div class="profile-section">
    <div class="profile-nav d-none d-xl-block">
      <div class="change-image-user-box">
          <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
          <p class="user-name">Jamie Lynn</p>
          <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
      </div>

      <div class="side-nav">
        <ul class="side-nav-ul">
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Account Settings </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Manage Coupons </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
          <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
        </ul>
      </div>
      <!-- change user image -->
    </div>
    <!--  -->

    <div class="right-side-block">

      <div class="heading-box">
        <h4 class="heading">Manage Product</h4>
        <div class="d-flex manage-btn-box">
        <div class="border-gradient seller-btn back-btn quick-edit-btn save-btn"><a href="<?= APPLICATION_URL.'/add-product'; ?>" class="btn view-btn"> Save </a></div>
        <div class="border-gradient seller-btn back-btn"><a href="<?= APPLICATION_URL.'/add-product'; ?>" class="btn view-btn"> Cancle </a></div>
        </div>
      </div>
      <!-- heading box -->

      <div class="right-side">
              <div class="quick-edit-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="edit-form">
                      <form>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Product Title</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Product Title">
                        </div>
                        <div class="form-group">
                          <label for="exampleFormControlSelect1">Category</label>
                          <select class="form-control custom-select" id="exampleFormControlSelect1">
                            <option> Choose Category </option>
                            <option>2</option>
                          </select>
                        </div>

                        <div class="form-row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="exampleFormControlSelect1">Stock</label>
                              <select class="form-control custom-select" id="exampleFormControlSelect1">
                                <option> 1 </option>
                                <option>2</option>
                              </select>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label>Price</label>
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text input-group-text1" id="basic-addon1">$</span>
                                </div>
                                <input type="text" class="form-control">     
                                <div class="input-group-prepend">
                                  <span class="input-group-text input-group-text2" id="basic-addon1">  USD</span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>


                      </form>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="quick-edit-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="edit-form">
                      <form>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Product Title</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Product Title">
                        </div>
                        <div class="form-group">
                          <label for="exampleFormControlSelect1">Category</label>
                          <select class="form-control custom-select" id="exampleFormControlSelect1">
                            <option> Choose Category </option>
                            <option>2</option>
                          </select>
                        </div>

                        <div class="form-row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="exampleFormControlSelect1">Stock</label>
                              <select class="form-control custom-select" id="exampleFormControlSelect1">
                                <option> 1 </option>
                                <option>2</option>
                              </select>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label>Price</label>
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text input-group-text1" id="basic-addon1">$</span>
                                </div>
                                <input type="text" class="form-control">     
                                <div class="input-group-prepend">
                                  <span class="input-group-text input-group-text2" id="basic-addon1">  USD</span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>


                      </form>
                  </div>
              </div>
              <!-- manage-product box -->
              <div class="quick-edit-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="edit-form">
                      <form>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Product Title</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Product Title">
                        </div>
                        <div class="form-group">
                          <label for="exampleFormControlSelect1">Category</label>
                          <select class="form-control custom-select" id="exampleFormControlSelect1">
                            <option> Choose Category </option>
                            <option>2</option>
                          </select>
                        </div>

                        <div class="form-row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="exampleFormControlSelect1">Stock</label>
                              <select class="form-control custom-select" id="exampleFormControlSelect1">
                                <option> 1 </option>
                                <option>2</option>
                              </select>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label>Price</label>
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text input-group-text1" id="basic-addon1">$</span>
                                </div>
                                <input type="text" class="form-control">     
                                <div class="input-group-prepend">
                                  <span class="input-group-text input-group-text2" id="basic-addon1">  USD</span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>


                      </form>
                  </div>
              </div>
              <!-- manage-product box -->
             
         

      </div>

    <!-- right-side-block -->

  </div>
</div>


<? /* <div class="login_page profile_page quick-edit-page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Manage Product</h4>
        <div class="d-flex manage-btn-box">
        <div class="border-gradient seller-btn back-btn quick-edit-btn"><a href="<?= APPLICATION_URL.'/add-product'; ?>" class="btn view-btn"> Quick Edit </a></div>
        <div class="border-gradient seller-btn back-btn"><a href="<?= APPLICATION_URL.'/add-product'; ?>" class="btn view-btn"> Add New </a></div>
        </div>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Coupons </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side">
              <div class="quick-edit-box">
                  <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/product-img1.jpg">  </div>
                  <div class="edit-form">
                      <form>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Product-title</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Product Title">
                        </div>
                        <div class="form-group">
                          <label for="exampleFormControlSelect1">Example select</label>
                          <select class="form-control custom-select" id="exampleFormControlSelect1">
                            <option>1</option>
                            <option>2</option>
                          </select>
                        </div>


                      </form>
                  </div>
              </div>
              <!-- manage-product box -->

              
          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div> */?>


<script>
$('.manage-products-block').mCustomScrollbar({axis:"x",  theme:"dark-3", advanced:{
 autoExpandHorizontalScroll:true } });

</script>