<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Become a Seller</h4>
        <div class="border-gradient seller-btn back-btn"><a class="btn view-btn"> Back </a></div>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side comman-form">
            <form>
            <div class="form-group">
                    <label >Store Name</label>
                    <input type="text" class="form-control" value="Store Name" >
                  </div>
                  <div class="form-group">
                    <label >Company Legal Name</label>
                    <input type="text" class="form-control" value="Company Legal Name">
                  </div>
                  <div class="form-group">
                    <label >Contact Person</label>
                    <input type="text" class="form-control" value="Contact Person">
                  </div>
                  <div class="form-group">
                    <label >Location</label>
                    <input type="text" class="form-control" value="Location" >
                  </div>

                  <div class="logo-upload-box">
                    <p class="logo-title"> Logo </p>
                    <div class="logo-img"> <img src="<?=HTTP_IMG_PATH?>/photo.svg">  </div>
                    <div class="upload-btn btn"> Upload </div>
                    <div class="upload-btn remove-btn btn"> Remove </div>
                  </div>


                  <div class="logo-upload-box">
                    <p class="logo-title"> Banner Image </p>
                    <div class="logo-img"> <img src="<?=HTTP_IMG_PATH?>/photo.svg">  </div>
                    <div class="upload-btn btn"> Upload </div>
                    <div class="upload-btn remove-btn btn"> Remove </div>
                  </div>

                  <div class="border-gradient"><button type="button" class="btn view-btn send-btn" id="startedbtn"> Get Verified </button></div>

                  <div class="verified-box">
                    <h2 class="titles"> Get Verified </h2>

                    <div class="form-group">
                      <label >Location</label>
                      <div class="custom-file">
                        <input type="file" class="custom-file-input form-control" id="customFileLang" lang="es">
                        <label class="custom-file-label" for="customFileLang">Upload Document </label>
                      </div>
                    </div>

                    <div class="form-group">
                      <label >Location</label>
                      <div class="custom-file">
                        <input type="file" class="custom-file-input form-control" id="customFileLang" lang="es">
                        <label class="custom-file-label" for="customFileLang">Upload Document </label>
                      </div>
                    </div>


                    <div class="form-group">
                      <label >Location</label>
                      <div class="custom-file">
                        <input type="file" class="custom-file-input form-control" id="customFileLang" lang="es">
                        <label class="custom-file-label" for="customFileLang">Upload Document </label>
                      </div>
                    </div>




                  </div>

                  <div class="border-gradient submit-btn"><button type="button" class="btn view-btn " id="startedbtn"> Submit </button></div>
                  <p class="approval-text">Admin will review the details submitted by you and after approval you can upload your products.</p>
            </form>


          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
