<div class="login_page profile_page manage-product-page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">My Order</h4>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Coupons </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side pt-0">

              <div class="select-order">
                  <label class="">Order Status </label>
                  <select class="custom-select">
                    <option selected>All</option>
                    <option value="1">Shipped</option>
                    <option value="2">Ready to ship</option>
                    <option value="3"> Delivered</option>
                    <option value="3">Processing</option>
                  </select>
              </div>

              <div class="customer-product-box">
                  <div class="row-one">
                    <p class="order-name">Order Number : 5190529635062955</p>
                    <p class="order-date">Order Date : 12-01-2020</p>
                    <div class="select-order mr-0">
                        <label class="">Order Status </label>
                        <select class="custom-select">
                          <option selected>All</option>
                          <option value="1">Shipped</option>
                          <option value="2">Ready to ship</option>
                          <option value="3"> Delivered</option>
                          <option value="3">Processing</option>
                        </select>
                    </div>
                  </div>

                  <div class="row-two">
                      <div class="left-side-block">
                        <div class="media">
                          <img src="<?=HTTP_IMG_PATH?>/img-1.jpg"> 
                          <div class="media-body">
                              <p class="user-name">Customer Name</p>
                              <div class="customer-detail">
                                <div class="row">
                                  <p class="col-sm">Address</p>
                                  <p class="col-sm">Postcode </p>
                                  <p class="col-sm">City </p>
                                  <p class="col-sm">State </p>
                                  <p class="col-sm"> Phone Number</p>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                     
                  </div>

                  <div class="customer-products">
                    <div class="customer-left-side">
                      <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/img-1.jpg">  </div>
                      <div class="product-detail">
                        <h3 class="product-title"> Product Title </h3>
                        <p class="p-name"> <span> Price :</span> <span>$250 </span> </p>
                        <p class="p-name"> <span> Discount: </span> <span> $20 </span> </p>
                        <p class="p-name"> <span> Quantity :</span> <span> 2</span> </p>
                        <p class="p-name"> <span> Amount :</span> <span> $500 Received (Admin commission deduction $100)</span> </p>
                      </div>
                    </div>
                   

                  </div>
                  <!-- customer product -->
                  <div class="customer-products">
                    <div class="customer-left-side">
                      <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/img-3.jpg">  </div>
                      <div class="product-detail">
                        <h3 class="product-title"> Product Title </h3>
                        <p class="p-name"> <span> Price :</span> <span>$250 </span> </p>
                        <p class="p-name"> <span> Discount: </span> <span> $20 </span> </p>
                        <p class="p-name"> <span> Quantity :</span> <span> 2</span> </p>
                        <p class="p-name"> <span> Amount :</span> <span> $500 Received (Admin commission deduction $100)</span> </p>
                      </div>
                    </div>
                   

                  </div>
                  <!-- customer product -->
              </div>
              <!-- customer-product box -->

              <div class="customer-product-box">
                  <div class="row-one">
                    <p class="order-name">Order Number : 5190529635062955</p>
                    <p class="order-date">Order Date : 12-01-2020</p>
                    <div class="select-order mr-0">
                        <label class="">Order Status </label>
                        <select class="custom-select">
                          <option selected>All</option>
                          <option value="1">Shipped</option>
                          <option value="2">Ready to ship</option>
                          <option value="3"> Delivered</option>
                          <option value="3">Processing</option>
                        </select>
                    </div>
                  </div>

                  <div class="row-two">
                      <div class="left-side-block">
                        <div class="media">
                          <img src="<?=HTTP_IMG_PATH?>/img-1.jpg"> 
                          <div class="media-body">
                              <p class="user-name">Customer Name</p>
                              <div class="customer-detail">
                                <div class="row">
                                  <p class="col-sm">Address</p>
                                  <p class="col-sm">Postcode </p>
                                  <p class="col-sm">City </p>
                                  <p class="col-sm">State </p>
                                  <p class="col-sm"> Phone Number</p>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                     
                  </div>

                  <div class="customer-products">
                    <div class="customer-left-side">
                      <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/img-1.jpg">  </div>
                      <div class="product-detail">
                        <h3 class="product-title"> Product Title </h3>
                        <p class="p-name"> <span> Price :</span> <span>$250 </span> </p>
                        <p class="p-name"> <span> Discount: </span> <span> $20 </span> </p>
                        <p class="p-name"> <span> Quantity :</span> <span> 2</span> </p>
                        <p class="p-name"> <span> Amount :</span> <span> $480 Received (Admin commission deduction $100)</span> </p>
                      </div>
                    </div>
                   
                  </div>
                  <!-- customer product -->
                  <div class="customer-products">
                    <div class="customer-left-side">
                      <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/img-3.jpg">  </div>
                      <div class="product-detail">
                        <h3 class="product-title"> Product Title </h3>
                        <p class="p-name"> <span> Price :</span> <span>$250 </span> </p>
                        <p class="p-name"> <span> Discount: </span> <span> $20 </span> </p>
                        <p class="p-name"> <span> Quantity :</span> <span> 2</span> </p>
                        <p class="p-name"> <span> Amount :</span> <span> $480 Received (Admin commission deduction $100)</span> </p>
                      </div>
                    </div>
                   

                  </div>
                  <!-- customer product -->
              </div>
              <!-- customer-product box -->

              <div class="customer-product-box">
                  <div class="row-one">
                    <p class="order-name">Order Number : 5190529635065455</p>
                    <p class="order-date">Order Date : 13-01-2020</p>
                    <div class="select-order mr-0">
                        <label class="">Order Status </label>
                        <select class="custom-select">
                          <option selected>All</option>
                          <option value="1">Shipped</option>
                          <option value="2">Ready to ship</option>
                          <option value="3"> Delivered</option>
                          <option value="3">Processing</option>
                        </select>
                    </div>
                  </div>

                  <div class="row-two">
                      <div class="left-side-block">
                        <div class="media">
                          <img src="<?=HTTP_IMG_PATH?>/img-1.jpg"> 
                          <div class="media-body">
                              <p class="user-name">Customer Name</p>
                              <div class="customer-detail">
                                <div class="row">
                                  <p class="col-sm">Address</p>
                                  <p class="col-sm">Postcode </p>
                                  <p class="col-sm">City </p>
                                  <p class="col-sm">State </p>
                                  <p class="col-sm"> 1234567890</p>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                     
                  </div>

                  <div class="customer-products">
                    <div class="customer-left-side">
                      <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/img-1.jpg">  </div>
                      <div class="product-detail">
                        <h3 class="product-title"> Product Title </h3>
                        <p class="p-name"> <span> Price :</span> <span>$250 </span> </p>
                        <p class="p-name"> <span> Discount: </span> <span> $20 </span> </p>
                        <p class="p-name"> <span> Quantity :</span> <span> 2</span> </p>
                        <p class="p-name"> <span> Amount :</span> <span> $480 Received (Admin commission deduction $100)</span> </p>
                      </div>
                    </div>
                   
                  </div>
                  <!-- customer product -->
                  
              </div>
              <!-- customer-product box -->

              <div class="customer-product-box">
                  <div class="row-one">
                    <p class="order-name">Order Number : 5190529635067855</p>
                    <p class="order-date">Order Date : 13-01-2020</p>
                    <div class="select-order mr-0">
                        <label class="">Order Status </label>
                        <select class="custom-select">
                          <option selected>All</option>
                          <option value="1">Shipped</option>
                          <option value="2">Ready to ship</option>
                          <option value="3"> Delivered</option>
                          <option value="3">Processing</option>
                        </select>
                    </div>
                  </div>
                  
                  <div class="row-two">
                      <div class="left-side-block">
                        <div class="media">
                          <img src="<?=HTTP_IMG_PATH?>/img-1.jpg"> 
                          <div class="media-body">
                              <p class="user-name">Customer Name</p>
                              <div class="customer-detail">
                                <div class="row">
                                  <p class="col-sm">Address</p>
                                  <p class="col-sm">Postcode </p>
                                  <p class="col-sm">City </p>
                                  <p class="col-sm">State </p>
                                  <p class="col-sm"> Phone Number</p>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                     
                  </div>
                
                  <!-- customer product -->
                  <div class="customer-products">
                    <div class="customer-left-side">
                      <div class="product-img"> <img src="<?=HTTP_IMG_PATH?>/img-3.jpg">  </div>
                      <div class="product-detail">
                        <h3 class="product-title"> Product Title </h3>
                        <p class="p-name"> <span> Price :</span> <span>$250 </span> </p>
                        <p class="p-name"> <span> Discount: </span> <span> $20 </span> </p>
                        <p class="p-name"> <span> Quantity :</span> <span> 2</span> </p>
                        <p class="p-name"> <span> Amount :</span> <span> $480 Received (Admin commission deduction $100)</span> </p>
                      </div>
                    </div>
                   

                  </div>
                  <!-- customer product -->
              </div>
              <!-- customer-product box -->
            
          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>



