<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Shipping Rate</h4>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Coupons </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side comman-form">
            <form>
                  <div class="form-group input-group">
                    <label>Global Rate</label>
                    <div class="input-group-prepend">
                      <span class="input-group-text" id="basic-addon1">$</span>
                    </div>
                    <input type="text" class="form-control">     
                  </div>

                  <div class="form-row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label for="inputEmail4">Country </label>
                          <select class="custom-select form-control" id="inlineFormCustomSelect">
                            <option selected>Select Country</option>
                            <option value="1">India</option>
                          </select>
                        </div>
                      </div>
                      <!-- col -->
                      <div class="col-sm-6">
                        <div class="form-group input-group">
                          <label>Rate</label>
                          <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">$</span>
                          </div>
                          <input type="text" class="form-control">     
                        </div>
                      </div>
                      <!-- col -->
                  </div>
                  <!-- form row -->

                  <div class="form-row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label for="inputEmail4">Country </label>
                          <select class="custom-select form-control" id="inlineFormCustomSelect">
                            <option selected>Select Country</option>
                            <option value="1">India</option>
                          </select>
                        </div>
                      </div>
                      <!-- col -->
                      <div class="col-sm-6">
                        <div class="form-group input-group">
                          <label>Rate</label>
                          <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">$</span>
                          </div>
                          <input type="text" class="form-control">     
                        </div>
                      </div>
                      <!-- col -->
                  </div>
                  <!-- form row -->

                  <div class="form-row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label for="inputEmail4">Country </label>
                          <select class="custom-select form-control" id="inlineFormCustomSelect">
                            <option selected>Select Country</option>
                            <option value="1">India</option>
                          </select>
                        </div>
                      </div>
                      <!-- col -->
                      <div class="col-sm-6">
                        <div class="form-group input-group">
                          <label>Rate</label>
                          <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">$</span>
                          </div>
                          <input type="text" class="form-control">     
                        </div>
                      </div>
                      <!-- col -->
                  </div>
                  <!-- form row -->

                  <div class="form-row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label for="inputEmail4">Country </label>
                          <select class="custom-select form-control" id="inlineFormCustomSelect">
                            <option selected>Select Country</option>
                            <option value="1">India</option>
                          </select>
                        </div>
                      </div>
                      <!-- col -->
                      <div class="col-sm-6">
                        <div class="form-group input-group">
                          <label>Rate</label>
                          <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">$</span>
                          </div>
                          <input type="text" class="form-control">     
                        </div>
                      </div>
                      <!-- col -->
                  </div>
                  <!-- form row -->
                  <a class="btn add-more-btn" href="#"> Add More </a>
                  
                  <div class="border-gradient submit-btn"><button type="button" class="btn view-btn " id="startedbtn"> Submit </button></div>
            </form>


          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
