<style type="text/css">
	.shopping-cart-img{background-color:#fff !important;}
	.shopping-cart-img > img{max-height:220px;width:auto !important;margin-left:auto;margin-right:auto;display:block;max-width:100%;}
	.credit-holders{max-width:78%;margin-left:auto;margin-right:auto;}
	.shopping-cart-page .shopping-cart .delete-icon{display:inline-block;}
	#checkoutModal{z-index:99999;}
	#continueModal{z-index:99999;}
	.sweet-alert{z-index:999999;}
	.pac-container{z-index: 100000000 !important;}
	#continueModal .modal-dialog{margin-top:25px;}
	#checkoutModal .modal-dialog{margin-top:60px;}
	#confirmremoveModal{z-index:99999;}
	#confirmremoveModal .modal-body{padding-top:25px;padding-bottom:25px;text-align:center;}
	#confirmallremoveModal{z-index:99999;}
	#confirmallremoveModal .modal-body{padding-top:25px;padding-bottom:25px;text-align:center;} 
	.modal{overflow-y:auto;}
	.shopping-cart-page .shopping-cart-img img{object-fit:contain;}
	label[for='clientele_chkterms']{padding-left:0px;}
	.shopping-cart-page .table-bottom{display:block;}
	.shopping-cart-page .table-bottom .coupon-btn-box{width:100%;}
	.coupon-btn-box + div{overflow:hidden}
	.coupon-btn-box + div img{float:right;margin-top:10px;max-width:175px;}
	.table-block .table thead th:nth-child(5), .table-block .table tbody td:nth-child(5){min-width:0px}
	.cart-opholder{margin-top:0px;margin-bottom:10px;}
	#shipping_country{height:auto !important;}
	.hub-text a:hover{text-decoration:none;}
	.shift-ortg{margin-top:20px;}
	.login-cartbtn{background:#000;color:#fff;padding:10px 30px;margin-left:5px;}
	.login-cartbtn:hover{color:#fff;text-decoration:none;box-shadow:none !important}
	.qryblk-tg{margin-top:20px;text-align:center;padding-top:30px !important;padding-bottom:25px !important;}
    .loguser-btn{background:#000;color:#fff;padding:10px 30px;border-radius:25px;border:1px solid #000;display:inline-block;margin-bottom:12px;}
    .loguser-btn:hover{background:#fff;color:#000;border:1px solid #000;text-decoration:none;}
    .guestchk-btn{border:1px solid #010001;margin-top:10px;max-width:170px;display:inline-block;width:100%;height:46px;line-height:46px;border-radius:30px;color:#010101;text-decoration:none !important;}
	.guestchk-btn:hover{background:#000;color:#fff;text-decoration:none;}
    .guestchk-btn:focus{outline:none;text-decoration:none;}
	@media (min-width:200px) and (max-width:767px){
		.shopping-cart-page .shopping-cart-right-block .input-group{width:100px;}
		.shopping-cart-page .shopping-cart-right-block .btn-number{width:31px;}
		.blockPage{width:90% !important;left:20px !important;right:20px;}	
	}
	@media (min-width:200px) and (max-width:500px){
		.coupon-btn-box + div{text-align:center;}
		.coupon-btn-box + div img{float:none;}
	}
	@media (min-width:200px) and (max-width:320px){
		.coupon_code{max-width:140px;}
	}
</style>

<div class="comman-section">
	<div class="container">
		<div class="common-heading">
			<h2 class="heading">Shopping Cart</h2>
		</div>
	</div>	
</div>




<div class="shopping-cart-page">
  <div class="container">

    
      <? /* ?>

      <div class="shopping-cart">
      	  <?php if(!empty($cart_data)) { ?>
          <a href="javascript:void(0)" class="delete-icon deleteall-cartbtn"><img src="<?=HTTP_IMG_PATH?>/delete2.svg">  Remove All </a>
          <?php $total_price = 0; foreach($cart_data as $cart_data_key => $cart_data_val) { 
		  	$total_price += $cart_data_val["product_cart_price"];
		      ?>
          <div class="shopping-cart-box">
              <div class="shopping-cart-img">
              	<?php if(!empty($cart_data_val["product_defaultpic"])) { ?>
                	<img src="<?=HTTP_PRODUCT_PIC_PATH?>/<?= $cart_data_val["product_defaultpic"] ?>">
				<?php } else { 
					$product_pics = explode(",",$cart_data_val["product_photos"]);
				?>
                	<img src="<?=HTTP_PRODUCT_PIC_PATH?>/<?= $product_pics[0]; ?>"> 
              	<?php } ?>
              </div>
              <!--  -->
              <div class="shopping-cart-right-block">
                  <p class="product-name"> <?= $cart_data_val["product_title"]; ?> </p>
                  <div class="row">
                      <div class="col-xl-3 col-lg-4 col-sm-6">
                          <p class="detail-text"> <span> <?= $cart_data_val["category_feild"]; ?></span> </p>
                      </div>
                      <div class="col-xl col-lg-4 col-sm-6">
                        <p class="detail-text detail-text3"> <span> Price : </span> <span>$<?= round($cart_data_val["product_price"] * $cart_data_val["product_cart_qty"],2); ?> </span> </p>
                      </div>
                      <div class="col-xl col-lg-4 col-sm-6">
                        <p class="detail-text detail-text3"> <span> Discount :</span> <?php if(!empty($cart_data_val["product_cart_discount"])) { ?><span>$<?= round($cart_data_val["product_cart_discount"],2); ?> </span><?php } ?> </p>
                      </div>
                      <div class="col-xl col-lg-4 col-sm-6">
                        <div class="quant-box">
                          <label>QTY</label>
                          <div class="input-group">	
                            <span class="input-group-btn prev-qbtn" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])) ?>">
                            <button type="button" class="btn btn-number" data-type="minus" data-field="quant[1]">
                              <i class="fas fa-minus"></i>
                            </button>
                            </span>
                            <input type="text" name="quant[1]" class="input-number" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" value="<?= $cart_data_val["product_cart_qty"]; ?>" min="1" max="<?= $cart_data_val["product_qty"]; ?>">
                            <span class="input-group-btn next-qbtn" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>">
                            <button type="button" class="btn btn-number" data-type="plus" data-field="quant[1]">
                              <i class="fas fa-plus"></i>
                            </button>
                            </span>
                          </div>
                        </div>
                      </div>
                      <!--  -->
                      <div class="col-xl col-lg-4 col-sm-6">
                        <p class="detail-text detail-text3"> <span> Final Price :</span> <span> $<?= round($cart_data_val["product_cart_price"],2) ?></span> </p>
                      </div>
                  </div>

                  <!--  -->
                  <div class="row">
                      <div class="col-lg-6">
                          <div class="">
                            <p class="detail-text detail-text2"> <span> Price : </span> <span>$<?= round($cart_data_val["product_price"],2); ?> </span> </p>
                            <p class="detail-text detail-text2"> <span>Quantity : </span> <span><?= $cart_data_val["product_cart_qty"]; ?> </span> </p>
                          </div>
                      </div>

                      <div class="col-lg-6">
                        <div class="coupon">
                          <form method="post" id="coupon_frm" name="coupon_frm">
                          	<?php if(empty($cart_data_val["product_cart_coupon"])) { ?>
                            <div class="form-group">
                              <label class="">Coupon Code</label>
                              <input type="text" id="coupon_code" name="coupon_code" class="coupon_code" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>" class="form-control" placeholder="" value="<?= $cart_data_val["product_cart_coupon"]; ?>">
                            </div>
                            <button type="button" class="btn apply-btn" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>">  Apply</button>
                            <?php } else { ?>
                            <div class="form-group">
                              <label class="">Coupon Code</label>
                              <input type="text" id="coupon_code" name="coupon_code" class="coupon_code" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>" class="form-control" placeholder="" value="<?= $cart_data_val["product_cart_coupon"]; ?>" disabled="disabled">
                            </div>
                            <button type="button" class="btn change-btn" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>">  Change</button>
                            <?php } ?>
                          </form>
                        </div>
                      </div>

                  </div>
                  <a href="javascript:void(0)" data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" class="delete-icon delcart-btn"><img src="<?=HTTP_IMG_PATH?>/delete2.svg"> </a>
              </div>
              <!--  -->
          </div>
          <?php } ?>
          <!-- shopping cart box -->
          <p class="sub-total"> Subtotal : <span class="subtot-intg">$<?= round($total_price,2); ?></span> </p>

          <div class="bottons">
            <div class="continue-shopping-btn"><a href="<?= APPLICATION_URL.'/product-listing'; ?>" class="continue-btn btn" > Continue Shopping </a></div>
            <div class="border-gradient"><a href="javascript:void(0)" class="view-btn btn catmore-btn" >Checkout</a></div>

          </div>
		  <?php } else { ?>
          	<p>No products have been added to the cart.</p>
          <?php } ?>	
      </div>

      <? */ ?>

      <!-- shopping cart -->

      <!-- new shopping page -->

      <div class="">
      <div class="table-block">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr class="table-head">
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Price</th>
                        <th scope="col"></th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Subtotal</th>
                      </tr>
                    </thead>
                    <!--  -->
                    <tbody class="shopping-innercart">
                      <?php if(!empty($cart_data)) { 
						$colors_arr = array(); $sizes_arr = array();
						$break_cond = '';
						foreach($cart_data as $cart_data_key => $cart_data_val) {
							
							if(!empty($cart_data_val["product_cart_color"])) {
								$colorsize_record = $this->layout()->AbstractModel->Super_Get(T_PROQTY,"color_productid = '".$cart_data_val["product_cart_prodid"]."' and color_slug ='".strtolower($cart_data_val["product_cart_color"])."' and color_size = '".$cart_data_val["product_cart_size"]."'","fetchAll");
							}
							$avl_qty = 0;
							if(!empty($colorsize_record)) {
								if($break_cond == '') {
									foreach($colorsize_record as $colorsize_record_key => $colorsize_record_val) {
										$avl_qty = $colorsize_record_val["color_qty"];
									}
								}
							}
							if($avl_qty == 0) {
								$avl_qty = 1;
							}
					  ?>
                      <tr>
                        <td > <div class="cross-btn delcart-btn" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])); ?>" data-type="1"<?php } else { ?>data-id="<?= $cart_data_key ?>" data-type="2"<?php } ?>> X </div> </td>
                        <td> 
                        	<div class="user-img">
                        		<a href="<?= APPLICATION_URL.'/product/'.slugify($cart_data_val["product_title"]).'~'.str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])) ?>">
									<?php if(!empty($cart_data_val["product_defaultpic"])) { ?>
										<img src="<?=HTTP_PRODUCT_PIC_PATH?>/160/<?= $cart_data_val["product_defaultpic"] ?>">
									<?php } else { 
										$product_pics = explode(",",$cart_data_val["product_photos"]);
									?>
										<img src="<?=HTTP_PRODUCT_PIC_PATH?>/160/<?= $product_pics[0]; ?>"> 
									<?php } ?>
								</a>   
                        	</div> 
                        </td>
                        <td> 
                            <a href="<?= APPLICATION_URL.'/product/'.slugify($cart_data_val["product_title"]).'~'.str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])) ?>" style="text-decoration:none;"><p class="dress-name"><?= $cart_data_val["product_title"]; ?> </p></a>
                            <p class="hub-text">Vendor: <a href="<?= APPLICATION_URL.'/shop/'.str_replace(" ","-",$cart_data_val['store_name']) ?>" target="_blank"><span> <?= $cart_data_val["store_name"]; ?> </span></a> </p>
                            <?php if($cart_data_val["product_isdigital"] != '1') { ?>
								<div class="color-and-size"> 
								  <p class="color"> Color:
								  <?php if(!empty($cart_data_val["product_cart_color"])) { ?> 
									<span class="color-tg" data-id="<?= $cart_data_val["product_cart_color"] ?>"></span>
								  <?php } ?> 
								  </p> 
								  <p class="size"> Size 
									<span><?php if(!empty($cart_data_val["product_cart_size"])) { echo $cart_data_val["product_cart_size"]; } ?></span>
								  </p>  
								</div>
								<input type="hidden" class="cart-colortg" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>"<?php } else { ?>data-id="<?= $cart_data_key ?>"<?php } ?> value="<?= $cart_data_val["product_cart_color"] ?>" />
								<input type="hidden" class="cart-sizetg" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>"<?php } else { ?>data-id="<?= $cart_data_key ?>"<?php } ?> value="<?= $cart_data_val["product_cart_size"] ?>" />
                            <?php } else { ?>
                            	<div class="color-and-size">
									<p class="color"> Color: N/A</p>
									<p class="size"> Size : N/A</p>
								</div>
                            <?php } ?>
                            <p class="note-tg">Personal Note: <span><?= nl2br($cart_data_val["product_cart_note"]); ?></span></p>
                        </td>
                        <td> $<?= $cart_data_val["product_cart_price"] / $cart_data_val["product_cart_qty"]; ?> <?php if(!empty($cart_data_val["product_cart_discount"])) { ?><br/><span class="offer-tg">Discount: <?= "$".$cart_data_val["product_cart_discount"]; ?></span><?php } ?> </td>
                        <td> <?php if(!empty($cart_data_val["product_globalrate"])) { echo "$".$cart_data_val["product_globalrate"]; } else { echo ""; } ?> </td>
                        <? $total_price = $cart_data_val["product_cart_price"] + $cart_data_val["product_globalrate"] ?>
                        <td> 
                          <?php if($cart_data_val["product_isdigital"] != '1') { ?>
                          <div class="quant-box">
                            <div class="input-group">	
                              <span class="input-group-btn prev-qbtn" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>" data-type="1"<?php } else { ?>data-id="<?= $cart_data_key ?>" data-type="2"<?php } ?> data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>" data-color="<?= $cart_data_val["product_cart_color"] ?>">
                              <button type="button" class="btn btn-number" data-type="minus" data-field="quant[1]">
                                <i class="fas fa-minus"></i>
                              </button>
                              </span>
                              <input type="text" name="quant[1]" class="input-number" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>" data-type="1"<?php } else { ?>data-id="<?= $cart_data_key ?>" data-type="2"<?php } ?> value="<?= $cart_data_val["product_cart_qty"] ?>" min="1" max="<?= $avl_qty ?>" readonly>
                              <span class="input-group-btn next-qbtn" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>" data-type="1"<?php } else { ?>data-id="<?= $cart_data_key ?>" data-type="2"<?php } ?> data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>" data-color="<?= $cart_data_val["product_cart_color"] ?>">
                              <button type="button" class="btn btn-number" data-type="plus" data-field="quant[1]">
                                <i class="fas fa-plus"></i>
                              </button>
                              </span>
                            </div>
                          </div>
                          <?php } ?> 
                        </td>
                        <td> $<?= $total_price ?> </td>
                      </tr>
                      <tr>
                      <td class="coupon" colspan="7">
                          <form class="form-inline" method="post" id="coupon_frm" name="coupon_frm">
                          	<div class="form-group copon-frmblk">
                              <input type="text" id="coupon_code" class="form-control coupon_code coupon-srtcode" name="coupon_code" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>" data-type="1"<?php } else { ?>data-id="<?= $cart_data_key ?>" data-type="2"<?php } ?> data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>" placeholder="" value="<?php if(!empty($cart_data_val["product_cart_coupon"])) { echo $cart_data_val["product_cart_coupon"]; } ?>">
                            </div>
                            <button type="button" class="btn apply-btn applycpn-btn" <?php if(!empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>data-id="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_id"])) ?>" data-type="1"<?php } else { ?>data-id="<?= $cart_data_key ?>" data-type="2"<?php } ?> data-pid="<?= str_replace("=","",base64_encode($cart_data_val["product_cart_prodid"])); ?>">  Apply Coupon </button>                            
                          </form>
                      </td>
                  	  </tr>
                      <?php } } ?>
                      <?php /*?><tr>
                        <td > <div class="cross-btn"> X </div> </td>
                        <td > <div class="user-img"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg">  </div> </td>
                        <td> 
                            <p class="dress-name"> New Edition Adult Wicked Witch Dress </p>
                            <p class="hub-text">Vendor: <span> The Fashion Hub </span> </p>
                            <div class="color-and-size"> 
                              <p class="color"> Color: <span class="red"></span> </p> 
                              <p class="size"> Size <span> XL </span> </p>  
                            </div>
                        </td>
                        <td> $28.00 </td>
                        <td> $5.00 </td>
                        <td> 
                          <div class="quant-box">
                            <div class="input-group">	
                              <span class="input-group-btn prev-qbtn" data-id="NTQ" data-pid="NA">
                              <button type="button" class="btn btn-number" data-type="minus" data-field="quant[1]">
                                <i class="fas fa-minus"></i>
                              </button>
                              </span>
                              <input type="text" name="quant[1]" class="input-number" data-id="NTQ" value="1" min="1" max="6">
                              <span class="input-group-btn next-qbtn" data-id="NTQ" data-pid="NA">
                              <button type="button" class="btn btn-number" data-type="plus" data-field="quant[1]">
                                <i class="fas fa-plus"></i>
                              </button>
                              </span>
                            </div>
                          </div> 
                        </td>
                        <td> $33.00 </td>
                      </tr><?php */?>
                    </tbody>
                    <!--  -->
                  </table>
                  <!-- table -->
                </div>
                <div class="table-bottom">
                  <div class="coupon-code">
                  </div>
                  <div class="coupon-btn-box">
                        <a href="<?php if(!empty($continue_link)) { echo $continue_link; } else { echo APPLICATION_URL.'/product-listing'; } ?>" class="continue-btn btn"> Continue Shopping </a>
                        <?php if(!empty($cart_data)) { ?>
                       <a href="javascript:void(0)" class="btn ckeckout-btn catmore-btn">Checkout</a>                 
                       <?php } ?>
                  </div>
                  <div><img src="<?= HTTP_IMG_PATH.'/secured-paypal.png'; ?>"></div>                  
                </div>
              </div>
              <!-- table block -->
      </div>
      <!--  -->
      

  </div>
</div>



<!-- Modal -->

<div class="modal cartqry-modal fade" id="cartqryModal" tabindex="-1" role="dialog" aria-labelledby="continueModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body qryblk-tg">
      	  <a href="<?= APPLICATION_URL.'/login' ?>" class="loguser-btn">Login to your account</a><br/>
          or<br/>
          <a href="javascript:void(0)" class="guestchk-btn">Continue as guest</a>
      </div>
    </div>
  </div>
</div>

<div class="modal shopping-modal fade" id="confirmallremoveModal" tabindex="-1" role="dialog" aria-labelledby="continueModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="continueModalLabel">Are you sure you want to remove all the products from cart?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      		<a href="javascript:void(0)" class="confirmall-removebtn">Yes</a>
            <a href="javascript:void(0)" class="confirmall-cancelbtn">No</a>
      </div>
    </div>
  </div>
</div>   

<div class="modal shopping-modal fade" id="confirmremoveModal" tabindex="-1" role="dialog" aria-labelledby="continueModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="continueModalLabel">Are you sure you want to remove the product from cart?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      		<a href="javascript:void(0)" class="confirm-removebtn">Yes</a>
            <a href="javascript:void(0)" class="confirm-cancelbtn">No</a>
      </div>
    </div>
  </div>
</div>      

<div class="modal shopping-modal fade" id="continueModal" tabindex="-1" role="dialog" aria-labelledby="continueModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="continueModalLabel">Shipping Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="modal-form-box">
          <form id="shipping_form" name="shipping_form" method="post">
             <div class="row">
              <div class="col-sm-6">
              	<div class="form-group">	
              	<label>First Name</label>
              	<? $expname = explode(" ",$loggedUser->{T_CLIENT_VAR.'client_name'}); 
				   if(count($expname) > 2) {
						if(!empty($expname[2])) {
							$name = $expname[2];	
						} if(!empty($expname[3])) {
							$name.= " ".$expname[3];
						}
						$popuserData["client_firstname"] = $expname[0];
						$popuserData["client_lastname"] = $expname[1]." ".$name;
					}
				?>
              	<input type="text" id="shipping_firstname" name="shipping_firstname" maxlength="100" class="form-control required" placeholder="" value="<?php if(!empty($expname[0])) { echo $expname[0]; } ?>">
				</div>
			  </div>
           	  <div class="col-sm-6">
           	  	<div class="form-group">
           	  		<label>Last Name</label>
           	  		<input type="text" id="shipping_lastname" name="shipping_lastname" maxlength="100" class="form-control required" placeholder="" value="<?php if(!empty($expname[1])) { echo $expname[1]; } ?>">
				</div>	
           	  </div>
			 </div> 
            <?php if(empty($loggedUser->{T_CLIENT_VAR."client_id"})) { ?>
            	<div class="form-group">
				  <label>Your Email</label>
				  <input type="text" id="shipping_email" name="shipping_email" maxlength="200" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR.'client_email'}) { echo $loggedUser->{T_CLIENT_VAR.'client_email'}; } ?>">
				</div>
            <?php } ?>
            <div class="form-group">
              <label>Address</label>
              <input type="text" id="shipping_address" name="shipping_address" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR.'client_address'}) { echo $loggedUser->{T_CLIENT_VAR.'client_address'}; } ?>" maxlength="655">
            </div>
            <div class="form-group">
              <label>Apartment, suite, etc. (optional)</label>
              <input type="text" id="shipping_apartment" name="shipping_apartment" class="form-control" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR.'client_apartment'}) { echo $loggedUser->{T_CLIENT_VAR.'client_apartment'}; } ?>" maxlength="200">
            </div>
            <div class="row">
				<div class="col-sm-6">
					<div class="form-group">
						<label>City</label>
						<input type="text" id="shipping_city" name="shipping_city" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR.'client_city'}) { echo $loggedUser->{T_CLIENT_VAR.'client_city'}; } ?>" maxlength="100">
					</div>
				</div>
			 </div>
			 <div class="form-group">
			 <div class="row">
			 	<div class="col-sm-4">
			 		<div class="form-group">
			 			<label>Country</label>
			 			<select class="form-control required" id="shipping_country" name="shipping_country" placeholder="">
			 				<?php if(!empty($all_countries)) { foreach($all_countries as $all_countries_key => $all_countries_val) { ?>
			 					<option value="<?= $all_countries_val["country_name_en"] ?>" <?php if(!empty($loggedUser->{T_CLIENT_VAR.'client_country'}) && $loggedUser->{T_CLIENT_VAR.'client_country'} == $all_countries_val["country_name_en"]) { ?>selected<?php } else if($all_countries_val["country_name_en"] == 'United States') { ?>selected<?php } ?>><?= $all_countries_val["country_name_en"] ?></option>
			 				<?php } } ?>	
			 			</select>
			 		</div>
			 	</div> 	
				<div class="col-sm-4">
					<div class="form-group">
					  <label>State</label>
					  <input type="text" id="shipping_state" name="shipping_state" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR.'client_state'}) { echo $loggedUser->{T_CLIENT_VAR.'client_state'}; } ?>" maxlength="250">
					</div>
				</div>
           		<div class="col-sm-4">
                	<div class="form-group">
                  		<label>Zip Code</label>
                  		<input type="text" id="shipping_postcode" name="shipping_postcode" maxlength="10" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR."client_postcode"}) { echo $loggedUser->{T_CLIENT_VAR."client_postcode"}; } ?>">
                	</div>
              	</div>	
            </div>
			</div>	
            <div class="form-row justify-content-between">
              
              <?php /*?><div class="col-sm-6">
                <div class="form-group">
                  <label>City</label>
                  <input type="text" id="shipping_city" name="shipping_city" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR."client_city"}) { echo $loggedUser->{T_CLIENT_VAR."client_city"}; } ?>">
                </div>
              </div>
            </div>
            <div class="form-row justify-content-between">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>State</label>
                  <input type="text" id="shipping_state" name="shipping_state" class="form-control required" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR."client_state"}) { echo $loggedUser->{T_CLIENT_VAR."client_state"}; } ?>">
                </div>
              </div><?php */?>
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Phone Number</label>
                  <input type="text" id="shipping_phone" name="shipping_phone" class="form-control required" maxlength="20" placeholder="" value="<?php if($loggedUser->{T_CLIENT_VAR."client_phone"}) { echo $loggedUser->{T_CLIENT_VAR."client_phone"}; } ?>">
                </div>
              </div>
              <input type="hidden" id="shipping_country" name="shipping_country" value="<?php if(!empty($loggedUser->{T_CLIENT_VAR."client_country"})) { echo $loggedUser->{T_CLIENT_VAR."client_country"}; } ?>">
            </div>

            <div class="border-gradient"> <button type="button" class="btn view-btn next-btn shipnxt-btn">Next</button> </div>

          </form>
        </div>
      </div>
    
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal shopping-modal fade" id="checkoutModal" tabindex="-1" role="dialog" aria-labelledby="checkoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
         <h5 class="modal-title" id="checkoutModalLabel">Your Payment Details</h5> 
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="checkout-amount">
        <div class="overview-zone">
              <div class="row">
               	<div class="col-sm-4 ">
                  <div class="count-box">
                    <div class="box-1">
                        <div class="counting-block">
                            <p class="numbers checkout-price prod-ratetg">  </p>
							<p class="count-txt"> Product Amount <span class="process-time"></span></p>
                        </div>
                    </div>
                   <!--  <div class="color-box">Total Views</div> -->
                  </div>
                  <!--  -->
                </div>
                <div class="col-sm-4 ">
                  <div class="count-box">
                    <div class="box-1">
                        <div class="counting-block">
                            <p class="numbers checkout-price ship-ratetg">  </p>
							<p class="count-txt"> Shipping Amount <span class="process-time"></span></p>
                        </div>
                    </div>
                   <!--  <div class="color-box">Total Views</div> -->
                  </div>
                  <!--  -->
                </div>
                <!--  -->
                <div class="col-sm-4">
                  <div class="count-box">
                    <div class="box-1">
                        <div class="counting-block">
                            <p class="numbers checkout-price total-amttg">  </p>
                            <p class="count-txt "> Total Amount <span>(including shipping & taxes)</span> </p>
                        </div>
                    </div>
                    
                  </div>
                  <!--  -->
                </div>
                <!--  -->
             
              </div>
              </div>


        </div>

        <div class="modal-form-box credit-holders">
          <form id="creditform" name="creditform" class="creditform" method="post">
            <!--  -->
            <div class="redio-btn">
              <?php /*?><div>
                <input type="radio" class="cart-optg" id="test1" value="1" name="radio-group" checked>
                <label for="test1"><span class="card-icon" style="width:150px;position:relative;top:-10px;"><img src="<?=HTTP_IMG_PATH?>/paypal-payments.jpg"> </span></label>
              </div><?php */?>
              <div class="cart-opholder">
              	<a href="<?= APPLICATION_URL.'/make-payment'; ?>"><img src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/buy-logo-medium.png" alt="Buy now with PayPal" style="width:auto;" /></a>
              </div>
              <?php /*?><div>
                <input type="radio" class="cart-optg" id="test2" value="2" name="radio-group">
                <label for="test2"><span class="paypal-icon"> <img src="<?=HTTP_IMG_PATH?>/paypal.png"> </span> </label>
              </div><?php */?>
             
            </div>

            <!--  -->
            <?php /*?><div class="form-group">
              <label>Name on Card</label>
              <input type="text" id="credit_name" name="credit_name" class="form-control required" maxlength="200" placeholder="">
            </div>
            <div class="form-group">
              <label>Card Number</label>
              <input type="text" id="credit_number" name="credit_number" class="form-control required" maxlength="16" placeholder="">
            </div>
            <div class="form-row justify-content-between">
              <div class="col-lg-6">
                <div class="form-group">
                  <label>Expiration Date</label>
                  <div class="form-row">
                     
                      <div class="col-6">
                        <select class="custom-select form-control required" id="credit_month" name="credit_month">
                          <option selected value="01">01</option>
                          <option value="02">02</option>
                          <option value="03">03</option>
                          <option value="04">04</option>
                          <option value="05">05</option>
                          <option value="06">06</option>
                          <option value="07">07</option>
                          <option value="08">08</option>
                          <option value="09">09</option>
                          <option value="10">10</option>
                          <option value="11">11</option>
                          <option value="12">12</option>
                        </select>
                      </div>
                      <div class="col-6">
                        <select class="custom-select form-control required" id="credit_year" name="credit_year">
                          <?php for($i=2020;$i<2060;$i++) { ?>
                          	<option value="<?= $i ?>"><?= $i ?></option>
                          <?php } ?>
                        </select>
                      </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <label>CVV</label>
                  <input type="text" id="credit_cvv" name="credit_cvv" class="form-control required" placeholder="" maxlength="4">
                </div>
              </div>
            </div>
            <label for="clientele_chkterms" class="checkbox"> By placing your order, you agree with The Collective Coven <a href="<?= APPLICATION_URL.'/privacy-policy'; ?>" target="_blank" class="term-linktg">Privacy Policy</a> & <a href="<?= APPLICATION_URL.'/terms-and-conditions'; ?>" target="_blank" class="term-linktg">Terms of Use</a><label></label>

            <div class="form-row justify-content-between"> <button type="button" class="btn view-btn next-btn paycart-btn" data-vid="2">Pay</button> </div><?php */?>

          </form>
        </div>
      </div>
     
    </div>
  </div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places,geometry&amp;key=<?= GOOGLE_MAP_API_KEY ?>&sensor=false"></script>
<script type="text/javascript" src="<?= FRONT_JS.'/creditly.js'; ?>"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
	function cardFormValidate(){
    var cardValid = 0;
      
    // Card number validation
    $('#credit_number').validateCreditCard(function(result) {
        var cardType = (result.card_type == null)?'':result.card_type.name;
        if(cardType == 'Visa'){
            var backPosition = result.valid?'2px -163px, 260px -87px':'2px -163px, 260px -61px';
        }else if(cardType == 'MasterCard'){
            var backPosition = result.valid?'2px -247px, 260px -87px':'2px -247px, 260px -61px';
        }else if(cardType == 'Maestro'){
            var backPosition = result.valid?'2px -289px, 260px -87px':'2px -289px, 260px -61px';
        }else if(cardType == 'Discover'){
            var backPosition = result.valid?'2px -331px, 260px -87px':'2px -331px, 260px -61px';
        }else if(cardType == 'Amex'){
            var backPosition = result.valid?'2px -121px, 260px -87px':'2px -121px, 260px -61px';
        }else{
            var backPosition = result.valid?'2px -121px, 260px -87px':'2px -121px, 260px -61px';
        }
        $('#credit_number').css("background-position", backPosition);
        if(result.valid){
            //$("#card_type").val(cardType);
            cardValid = 1;
        }else{
            //$("#card_type").val('');
            cardValid = 0;
        } 
    });
    // Card details validation
    var cardName = $("#credit_name").val();
    var expMonth = $("#credit_month").val();
    var expYear = $("#credit_year").val();
    var cvv = $("#credit_cvv").val();
    var regName = /^[a-z ,.'-]+$/i;
    var regMonth = /^01|02|03|04|05|06|07|08|09|10|11|12$/;
    var regYear = /^2020|2021|2022|2023|2024|2025|2026|2027|2028|2029|2030|2031$/;
    var regCVV = /^[0-9]{3,3}$/;
    if(cardValid == 0){
		$(".paycart-btn").attr("data-vid","2");
		$("#credit_number").css("border","1px solid red");
    } else if(cardValid == 1) {
		$("#credit_number").css("border","1px solid rgb(216,216,216)");
	}
	if(!regMonth.test(expMonth)){
		$("#credit_month").css("border","1px solid red");
    } else {
		$("#credit_month").css("border","1px solid rgb(216,216,216)");
	}
	if(!regYear.test(expYear)){
		$("#credit_year").css("border","1px solid red");
    } else {
		$("#credit_year").css("border","1px solid rgb(216,216,216)");
	}
	if(!regCVV.test(cvv)){
		$("#credit_cvv").css("border","1px solid red");
    } else {
		$("#credit_cvv").css("border","1px solid rgb(216,216,216)");
	}
	if(!regName.test(cardName)){
		$("#credit_name").css("border","1px solid red");
    }else{
		$("#credit_name").css("border","1px solid rgb(216,216,216)");
    }
	
	if(cardValid == 0){
		$(".paycart-btn").attr("data-vid","2");
    } else if(!regMonth.test(expMonth)){
		$(".paycart-btn").attr("data-vid","2");
    } else if(!regYear.test(expYear)){
		$(".paycart-btn").attr("data-vid","2");
    } else if(!regCVV.test(cvv)){
		$(".paycart-btn").attr("data-vid","2");
    } else if(!regName.test(cardName)){
		$(".paycart-btn").attr("data-vid","2");
    }else{
		$(".paycart-btn").attr("data-vid","1");
    }
	
}

$(document).on("change","#credit_year",function() {
	cardFormValidate();
})

//set your publishable key	
Stripe.setPublishableKey("<?= $site_configs["site_stripe_key"]; ?>");
	
//callback to handle the response from stripe
function stripeResponseHandler(status, response) {
	if (response.error) {
		//enable the submit button
		showAppAlert('Error!!',response.error.message,'error');
		$(this).val('');
	} else {
		//get token id
		var token = response['id'];
		//insert the token into the form
		$("#creditform").append("<input type='hidden' name='token' value='" + token + "' />");
		//submit form to the server
		$("#creditform").submit();
	}
}
	
function stripePay(e) {
	e.preventDefault();
	var month = $("#credit_month").val();
	var year = $("#credit_year").val();
	
	Stripe.createToken({
		number: $('#credit_number').val(),
		cvc: $('#credit_cvv').val(),
		exp_month: month,
		exp_year: year
	}, stripeResponseHandler);
	return false;
}

$(document).on("click",".paycart-btn",function() {
		var vid = $(this).attr("data-vid");
		if($("#creditform").valid()) {
		if(vid == 2) {
			showAppAlert('Error!!','Please check the cart details.','error');
		} else {
			var formData = $('#creditform').serialize();
            $.ajax({
                type:'POST',
                url:baseUrl+'/process-payment',
                dataType: "json",
                data:formData,
                beforeSend: function(){
					$("#checkoutModal").modal("hide");
					$.blockUI({
            			css: {
                			border: 'none',
                			padding: '5px',
                			width: '24%',
                			left: '39%',
                			backgroundColor: '#000000',
                			border: 'solid 1px #424445',
                			opacity: .9,
                			color: '#ffffff',
            		},
            		message: "<div class='Loader'><div class='Text' style='letter-spacing: 2px;'>Please wait while your transaction is processing.</div></div>",
        	});
                },
                success:function(data){
					if(data == 'empty') {
						showAppAlert('Error!!','Your cart is empty.','error');
					} else if(data == 'error') {
						showAppAlert('Error!!','Please fill the form correctly.','error');
					} else if(data == 'qtyempty') {
						$.unblockUI();
						showAppAlert('Error!!','Please fill the form correctly.','error');
					}
					 else {
					var response = JSON.parse(JSON.stringify(data));
						if(response.status == 'S'){
							showAppAlert('Success!!',response.message,'success');
							setTimeout(function(){ window.location.replace(baseUrl+"/order-summary"); }, 2000);
						} else if(response.status == 'U'){
							$.unblockUI();
							showAppAlert('Error!!',response.message,'error');
						} else {
							$("#creditform").find("input[type=text]").val("");
							$.unblockUI();
							showAppAlert('Error!!',response.message,'error');
						}
					}
				}
			})
		}
		}
	})
	
	$(document).on("click",".delcart-btn",function() {
		var tid = $(this).attr("data-id");
		var uid = $(this).attr("data-type");
		$(".confirm-removebtn").attr("data-id",tid);
		$(".confirm-removebtn").attr("data-type",uid);
		$("#confirmremoveModal").modal("show");
	})
	
	$(document).on("click",".confirm-cancelbtn",function() {
		$("#confirmremoveModal").modal("hide");
	})
	
	$(document).on("click",".confirm-removebtn",function() {
		var tid = $(this).attr("data-id");
		var uid = $(this).attr("data-type");
		$("#confirmremoveModal").modal("hide");
		$.ajax({
			url: baseUrl+"/remove-cart",
			type: "POST",
			data: {tid:tid,uid:uid},
			success: function(data){
				location.reload();
			}
		})
	})
	
	 $('#creditform input[type=text],select').on('keyup',function(){
        cardFormValidate();
    });
	
	$(document).on("click",".deleteall-cartbtn",function() {
		$("#confirmallremoveModal").modal("show");
	})
	
	$(document).on("click",".confirmall-cancelbtn",function() {
		$("#confirmallremoveModal").modal("hide");
	})
	
	$(document).on("click",".confirmall-removebtn",function() {
		$.ajax({
			url: baseUrl+"/removeall-cart",
			type: "POST",
			data: {tid:1},
			success: function(data){
				if(data == 'success') {
					location.reload();
				} else {
					showAppAlert('Error!!','You have no products to delete.','error');
				}
			}
		})
	})
	
	$(document).on("click",".cart-optg",function() {
		var opt = $('.cart-optg:checked').val();
		if(opt == 2) {
			window.location.replace(baseUrl+"/make-payment");
		}
	})
	
	$(document).on("click",".change-btn",function() {
		var tid = $(this).attr("data-id");
		var max = parseInt($(".input-number[data-id="+tid+"]").attr('max'));
        var min = parseInt($(".input-number[data-id="+tid+"]").attr('min'));	
		var pid = $(this).attr("data-pid");
		var inptxt = $(".input-number[data-id="+tid+"]").val();
		var inptxt = parseInt(inptxt);
		var coupon_code = '';
		var color = $(".cart-colortg[data-id="+tid+"]").val();
		var size = $(".cart-sizetg[data-id="+tid+"]").val(); 
		if (inptxt > max)
        {
        	var inptxt = max;
        }
        else if (inptxt < min)
        {
			var inptxt = min;
        }
		$.ajax({
			url: baseUrl+"/cart-price",
			type: "POST",
			data: {tid:tid,pid:pid,qty:inptxt,coupon_code:coupon_code,color:color,size:size},
			success: function(data){
				if(data != 'error' && data != 'empty' && data != 'invalid_number' && data != 'qty_restricted') {
					$(".shopping-cart").html(data);
				} else if(data == 'error') {
					showAppAlert('Error!!','No such product found.','error');
				} 
				 else if(data == 'empty') {
					showAppAlert('Error!!','No such product found in the cart.','error');
				} else if(data == 'qty_restricted') {
					showAppAlert('Error!!','Invalid quantity entered.','error');
				} else if(data == 'invalid_number') {
					showAppAlert('Error!!','Invalid quantity entered.','error');
				}  else if(data == 'invalid_qty') {
					showAppAlert('Error!!','Invalid quantity entered.','error');
				}
			}
		})
})
	
	$(document).on("click",".apply-btn",function() {
		var tid = $(this).attr("data-id");
		var uid = $(this).attr("data-type");
		var max = parseInt($(".input-number[data-id="+tid+"]").attr('max'));
        var min = parseInt($(".input-number[data-id="+tid+"]").attr('min'));	
		var pid = $(this).attr("data-pid");
		var inptxt = $(".input-number[data-id="+tid+"]").val();
		var inptxt = parseInt(inptxt);
		var coupon_code = $(".coupon_code[data-id="+tid+"]").val();
		var color = $(".cart-colortg[data-id="+tid+"]").val();
		var size = $(".cart-sizetg[data-id="+tid+"]").val(); 
		if (inptxt > max)
        {
        	var inptxt = max;
        }
        else if (inptxt < min)
        {
			var inptxt = min;
        }
		if(coupon_code != '') {
			$.ajax({
				url: baseUrl+"/cart-price",
				type: "POST",
				data: {tid:tid,pid:pid,qty:inptxt,coupon_code:coupon_code,chkcoupon:1,color:color,size:size,uid:uid},
				success: function(data){
					if(data != 'error' && data != 'empty' && data != 'invalid_number' && data != 'qty_restricted') {
						$(".shopping-innercart").html(data);
						$('.color-tg').each(function(i, obj) {
							var colortg = $(obj).attr("data-id");
							$(obj).css("background-color",colortg);
						})
					} else if(data == 'error') {
						showAppAlert('Error!!','No such product found.','error');
					} 
					 else if(data == 'empty') {
						showAppAlert('Error!!','No such product found in the cart.','error');
					} else if(data == 'qty_restricted') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					} else if(data == 'invalid_number') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					}  else if(data == 'invalid_qty') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					}
				}
		 	})
		} else {
			showAppAlert('Error!!','Please enter coupon code.','error');
		}
	})
	
	$(function () {
	   $(document).on("click",".prev-qbtn",function() {
		    var tid = $(this).attr("data-id");
		   var uid = $(this).attr("data-type"); 
	     var max = parseInt($(".input-number[data-id="+tid+"]").attr('max'));
          var min = parseInt($(".input-number[data-id="+tid+"]").attr('min'));		 
		  var pid = $(this).attr("data-pid");
          var inptxt = $(".input-number[data-id="+tid+"]").val();
		  var oldtxt = inptxt; 
		  var inptxt = parseInt(inptxt) - 1;
		  var coupon_code = $(".coupon_code[data-id="+tid+"]").val();
		  var color = $(".cart-colortg[data-id="+tid+"]").val();
		  var size = $(".cart-sizetg[data-id="+tid+"]").val();  
		  if (inptxt > max)
          {
              var inptxt = max;
          }
          else if (inptxt < min)
          {
			  var inptxt = min;
          } 
		  $(".input-number[data-id="+tid+"]").val(inptxt);
		  $.ajax({
			url: baseUrl+"/cart-price",
			type: "POST",
			data: {tid:tid,pid:pid,qty:inptxt,coupon_code:coupon_code,color:color,size:size,uid:uid},
			success: function(data){
				if(data != 'error' && data != 'empty' && data != 'invalid_number' && data != 'qty_restricted') {
						$(".shopping-innercart").html(data);
						$('.color-tg').each(function(i, obj) {
							var colortg = $(obj).attr("data-id");
							$(obj).css("background-color",colortg);
						})
					} else if(data == 'error') {
						showAppAlert('Error!!','No such product found.','error');
					} else if(data == 'empty') {
						showAppAlert('Error!!','No such product found in the cart.','error');
					} else if(data == 'qty_restricted') {
						$(".input-number[data-id="+tid+"]").val(oldtxt);
						showAppAlert('Error!!','Invalid quantity entered.','error');
					} else if(data == 'invalid_number') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					}  else if(data == 'invalid_qty') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					}
			}
		  })
	   })
	   
	   $(document).on("click",".next-qbtn",function() {
		  var tid = $(this).attr("data-id");
		  var uid = $(this).attr("data-type"); 
          var max = parseInt($(".input-number[data-id="+tid+"]").attr('max'));
          var min = parseInt($(".input-number[data-id="+tid+"]").attr('min'));
		  var pid = $(this).attr("data-pid");
          var inptxt = $(".input-number[data-id="+tid+"]").val();
		  var oldtxt = inptxt; 
		  var inptxt = parseInt(inptxt) + 1;
		  var coupon_code = $(".coupon_code[data-id="+tid+"]").val();
		  var color = $(".cart-colortg[data-id="+tid+"]").val();
		  var size = $(".cart-sizetg[data-id="+tid+"]").val(); 
		  if (inptxt > max)
          {
              var inptxt = max;
          }
          else if (inptxt < min)
          {
			  var inptxt = min;
          }
		  $(".input-number[data-id="+tid+"]").val(inptxt);
		  $.ajax({
			url: baseUrl+"/cart-price",
			type: "POST",
			data: {tid:tid,pid:pid,qty:inptxt,coupon_code:coupon_code,color:color,size:size,uid:uid},
			success: function(data){
				if(data != 'error' && data != 'empty' && data != 'invalid_number' && data != 'qty_restricted') {
						$(".shopping-innercart").html(data);
						$('.color-tg').each(function(i, obj) {
							var colortg = $(obj).attr("data-id");
							$(obj).css("background-color",colortg);
						})
					} else if(data == 'error') {
						showAppAlert('Error!!','No such product found.','error');
					} else if(data == 'empty') {
						showAppAlert('Error!!','No such product found in the cart.','error');
					} else if(data == 'qty_restricted') {
						$(".input-number[data-id="+tid+"]").val(oldtxt);
						showAppAlert('Error!!','Invalid quantity entered.','error');
					} else if(data == 'invalid_number') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					}  else if(data == 'invalid_qty') {
						showAppAlert('Error!!','Invalid quantity entered.','error');
					}
			}
		  })
        }); 
});

$(document).ready(function(){

$("#credit_name").keydown(function(event){
	var inputValue = event.which;
        // allow letters and whitespaces only.
    if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0) && inputValue != 8 && inputValue != 46 && inputValue != 9) { 
    	event.preventDefault(); 
    }
});

$("#credit_number").keydown(function(event){
	var charCode = event.which;
        // allow letters and whitespaces only.
        /*if (charCode != 219 && charCode != 221 && charCode != 89 && charCode != 37 && charCode != 38 && charCode != 39 && charCode != 40 && charCode != 8 charCode != 9 && charCode != 16 && charCode != 32 && charCode != 46 && charCode != 45 && charCode > 31 && (charCode < 48 || charCode > 57))*/
    if(charCode > 64 && charCode < 91)
	{
		return false;
	} else {
		return true;
	}
});


$("#shipping_firstname").keydown(function(event){
	var inputValue = event.which;
        // allow letters and whitespaces only.
    if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0) && inputValue != 8 && inputValue != 46 && inputValue != 9) { 
    	event.preventDefault(); 
    }
});
	
$("#shipping_lastname").keydown(function(event){
	var inputValue = event.which;
        // allow letters and whitespaces only.
    if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0) && inputValue != 8 && inputValue != 46 && inputValue != 9) { 
    	event.preventDefault(); 
    }
});	
	
$("#shipping_phone").keydown(function(event){
	var charCode = event.which;
        // allow letters and whitespaces only.
        /*if (charCode != 219 && charCode != 221 && charCode != 89 && charCode != 37 && charCode != 38 && charCode != 39 && charCode != 40 && charCode != 8 charCode != 9 && charCode != 16 && charCode != 32 && charCode != 46 && charCode != 45 && charCode > 31 && (charCode < 48 || charCode > 57))*/
    if(charCode > 64 && charCode < 91)
	{
		return false;
	} else {
		return true;
	}
});
})

$(document).on("click",".shipnxt-btn",function() {
	if($("#shipping_form").valid()) {
		 var ship_name = $("#shipping_firstname").val()+' '+$("#shipping_lastname").val();
		 var myString = ship_name.split(" ");
		 if(myString[1] != undefined && myString[1] != '') {
			 var ship_mail = $("#shipping_email").val(); 	
			 var ship_addr = $("#shipping_address").val();
			 var ship_apt = $("#shipping_apartment").val();
			 var ship_code = $("#shipping_postcode").val();
			 var ship_city = $("#shipping_city").val();
			 var ship_state = $("#shipping_state").val();
			 var ship_phone = $("#shipping_phone").val();
			 var ship_country = $("#shipping_country").val();
			 $.ajax({
				url: baseUrl+"/ship-details",
				type: "POST",
				data: {ship_name:ship_name,ship_mail:ship_mail,ship_addr:ship_addr,ship_apt:ship_apt,ship_code:ship_code,ship_city:ship_city,ship_state:ship_state,ship_phone:ship_phone,ship_country:ship_country},
				success: function(data){
					var items = '';
					var items = $.parseJSON(data);
					if(items.response_code == 'error') {
						showAppAlert('Error!!','Please fill the form correctly.','error');
					} else if(items.response_code == 'closed') {
						$("#continueModal").modal("hide");
						showAppAlert('Error!!',items.message,'error');
					} else if(items.response_code == 'fixname') {
						showAppAlert('Error!!','Invalid name entered.','error');
					} else if(items.response_code == 'fixphone') {
						showAppAlert('Error!!','Invalid phone number entered.','error');
					} else if(items.response_code == 'no_shipping') {
						$("#continueModal").modal("hide");
						showAppAlert('Error!!',items.message,'error');
					} else if(items.response_code == 'no_product') {
						$("#continueModal").modal("hide");
						showAppAlert('Error!!',items.message,'error');
					} else {
						$("#continueModal").modal("hide");
						var amt = items.total_charge;
						var charge = items.shipping_charge;
						var prodcharge = items.product_charge;
						if(charge != 0) {
							$(".prod-ratetg").text("$"+prodcharge);
							$(".ship-ratetg").text("$"+charge);
							$(".total-amttg").text("$"+amt);
							//$(".checkout-price").text("$"+amt +" (including shipping charge of $"+charge+")");
						} else {
							$(".prod-ratetg").text("$"+prodcharge);
							$(".ship-ratetg").text("$0");
							$(".total-amttg").text("$"+amt);
							//$(".checkout-price").text("$"+amt );
						}
						$("#checkoutModal").modal("show");
					}
				}
			 })
		} else {
			showAppAlert('Error!!','Please also include Last Name in the Name field.','error');
		} 	
	}
})

$(document).on("click",".guestchk-btn",function() {
  $("#cartqryModal").modal("hide");
  $("#continueModal").modal("show");
})

$(document).on("click",".catmore-btn",function() {
	<?php if(!empty($loggedUser)) { ?>
        $("#continueModal").modal("show");
    <?php } else { ?>
        $("#cartqryModal").modal("show");
    <?php } ?>
	//$(".checkout-price").text($(".subtot-intg").text());
	//$("#checkoutModal").modal("show");
})

$(document).ready(function(e) {
	$('.color-tg').each(function(i, obj) {
		var colortg = $(obj).attr("data-id");
		$(obj).css("background-color",colortg);
	})
})
</script>