<?php use Zend\Db\Sql\Expression; ?>
<?php if(count($this->paginator)>0) { 
					foreach($this->paginator as $product_data_key=>$prodct_data_val){
					$priceqty_data = $this->layout()->AbstractModel->Super_Get(T_PROQTY,"color_productid =:PID","fetch",array('warray'=>array('PID'=>$prodct_data_val["product_id"])));	
					$product_photos = explode(",",$prodct_data_val["product_photos"]); 
					?>
					<div class="item">
						<div class="itmanc-tg" data-href="<?= APPLICATION_URL.'/product/'.slugify($prodct_data_val["product_title"]).'~'.str_replace("=","",base64_encode($prodct_data_val["product_id"])); ?>">
							<div class="card menu-card">
								<?php if($prodct_data_val[T_CLIENT_VAR."client_bestseller"] == '1') { ?>
									<div class="ribbon-pop"><span>Best Seller</span></div>
								<?php } ?>
								<div class="slider-img"><div class="card-img-top">
									<a href="<?= APPLICATION_URL.'/product/'.slugify($prodct_data_val["product_title"]).'~'.str_replace("=","",base64_encode($prodct_data_val["product_id"])); ?>">
									<?php if(!empty($prodct_data_val["product_defaultpic"])) { ?>
									<img class="" src="<?=HTTP_PRODUCT_PIC_PATH?>/thumb/<?= $prodct_data_val["product_defaultpic"]; ?>" alt="Card image cap">
									<?php } else { ?>
									<img class="" src="<?=HTTP_PRODUCT_PIC_PATH?>/thumb/<?= $product_photos[0]; ?>" alt="Card image cap">
									<?php } ?>
									</a>
									<div class="coven-overlay d-none"></div> 
								</div>
								<?php if($prodct_data_val["shipping_free"] == '1' && $prodct_data_val[T_CLIENT_VAR."client_country"] == $loggedUser->{T_CLIENT_VAR."client_country"} && $prodct_data_val["product_isdigital"] != '1') { ?>
									<div class="freeship-holder"><div class="freeship-txt">Free Shipping</div></div>
								<?php } else { ?>
									<div class="freeship-holder">&nbsp;</div>
								<?php } ?>  
							</div>
							<div class="card-body">
								<a href="<?= APPLICATION_URL.'/product/'.slugify($prodct_data_val["product_title"]).'~'.str_replace("=","",base64_encode($prodct_data_val["product_id"])); ?>" class="card-anctg"><h4 class="card-title"><?php echo $prodct_data_val["product_title"]; ?> </h4></a>
								<?php if($prodct_data_val["product_isdigital"] != '1') { ?>
									<p class="price-txt"> <span class="mrp-price"> </span> <span>$<?= $priceqty_data["color_price"]; ?></span> </p>
								<?php } else { ?>
									<p class="price-txt"> <span class="mrp-price"> </span> <span>$<?= $prodct_data_val["product_price"]; ?></span> </p>
								<?php } ?>
								<!-- <a href="<?= APPLICATION_URL.'/product-listing?category='.$prodct_data_val["product_category"]; ?>" class="category-txt"> <?= $prodct_data_val["category_feild"]; ?> </a> -->
								
								<div class="btn-block">
									<a href="<?= APPLICATION_URL.'/product/'.slugify($prodct_data_val["product_title"]).'~'.str_replace("=","",base64_encode($prodct_data_val["product_id"])); ?>" class="btn view-btn"> View Detail </a>
									<a href="<?= APPLICATION_URL.'/product/'.slugify($prodct_data_val["product_title"]).'~'.str_replace("=","",base64_encode($prodct_data_val["product_id"])); ?>#cart" class="btn cart-btn" data-id="<?= str_replace("=","",base64_encode($prodct_data_val["product_id"])); ?>"> Add to cart </a>
								</div>
							</div>
							</div>
						</div>
					</div><?php }  ?>
                <?php echo $this->paginationControl($this->paginator, 'Sliding','auth-acl/paginator.phtml', array('page'=>$page)); ?>
				<? 
} else { ?>
	<p class="col-md-12">No product found.</p>
<?php } ?>
<script type="text/javascript">
	$(document).ready(function(e) {
    $(".star-panel").starRating({
		minRating: 0.5,
		readOnly: true,
		ratedColor: '#f4a925',
  		activeColor: '#f4a925',
		emptyColor: '#bebebe',
		hoverColor: '#f4a925',
  		strokeWidth:0,
  		starSize: 23,
		useGradient: false,
		callback: function(currentRating, $el){
			$(".review_rate").val(currentRating);
    	}
	});
});	
</script>