<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Upload Product</h4>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Upload Product </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Products </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Manage Coupons </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Shipping Rate  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side comman-form">
            <form>
                  <div class="form-group">
                    <label >Store Name</label>
                    <input type="text" class="form-control" value="Store Name" >
                  </div>

                  <div class="form-row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label for="">Category</label>
                          <select class="custom-select form-control" id="">
                            <option selected>Category</option>
                          </select>

                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label for="">Price</label>
                          <input type="text" class="form-control" placeholder="Price" >
                        </div>
                      </div>
                  </div>

                  <div class="form-group">
                    <label >Available Quantity</label>
                    <input type="text" class="form-control" value="Available Quantity" >
                  </div>

                  <div class="form-group">
                    <label >Description</label>
                    <textarea class="form-control" id="" rows="5" placeholder="Description" ></textarea>
                  </div>

                  <div class="">
                    <div class="form-group">
                      <label >Upload Photos</label>
                        <div class="upload-img-box">
                          <div class="upload-img-logo"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                          <a class="btn add-more-btn" href="#"> Choose file to upload </a>
                          <p class="upload-text"> or drag & drop them here </p>
                        </div>
                    </div>

                      <div class="uploaded-images-box">
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                        <div class="uploaded-img"><img src="<?=HTTP_IMG_PATH?>/photo.svg"></div>
                      </div>

                  </div>
                  <!-- upload image box -->
              
                  <div class="border-gradient submit-btn"><button type="button" class="btn view-btn " id="startedbtn"> Submit </button></div>
            </form>


          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
