<div class="login_page profile_page">
  <div class="container">

      <div class="heading-box">
        <h4 class="heading">Wallet</h4>
      </div>

      <div class="login-signup-form">
          <div class="left-side signup-img profile-nav d-none d-lg-block">
            <div class="change-image-user-box">
                <div class="user-image"> <img src="<?=HTTP_IMG_PATH?>/user-img.jpg"> </div>
                <p class="user-name">Jamie Lynn</p>
                <div class="border-gradient change-img-btn"> <a href="#" class="change-btn view-btn btn">Change Image</a> </div>
            </div>

            <div class="side-nav">
              <ul class="side-nav-ul">
                <li class="side-nav-items"> <a href="#" class="side-nav-links active"> Account Settings </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links"> Change Password </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
                <li class="side-nav-items"> <a href="#" class="side-nav-links">  </a> </li>
              </ul>
            </div>
            <!-- change user image -->
          </div>
          <!------------ left side ------------------>
          <div class="right-side wallet-section">
              <div class="row">
                  <div class="col-sm-4">
                      <div class="amount-box"> 
                        <p class="amount">$502.00</p>
                        <p class="amount-txt">Total Earned</p>
                      </div>
                  </div>
                  <!--  -->
                  <div class="col-sm-4">
                      <div class="amount-box"> 
                        <p class="amount">$350.00</p>
                        <p class="amount-txt">Total Withdrawal</p>
                      </div>
                  </div>
                  <!--  -->
                  <div class="col-sm-4">
                      <div class="amount-box"> 
                        <p class="amount">$152.00</p>
                        <p class="amount-txt">Available Balance</p>
                      </div>
                  </div>
                  <!--  -->
              </div>
              <!-- row -->
              <div class="wallet-group">

                 <form class="form-inline">
                    <div class="form-left-side"> 
                      <label for="">Withdrawal</label>
                      <div class="input-group mb-0 form-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text" id="basic-addon1">$</span>
                        </div>
                        <input type="" class="form-control" id="" placeholder="">                      
                      </div>
                      <small> Enter Amount </small>
                      
                    </div>
                    <div class="border-gradient"><button type="button" class="btn view-btn send-btn" id="startedbtn">Submit</button></div>
                  </form>

              </div>

              <div class="table-box">
                  <h2 class="table-heading">Transaction History</h2>

                  <div class="table-responsive">
                    <table class="table">
                      <thead class="table-thead">
                        <tr>
                          <th scope="col">STATUS</th>
                          <th scope="col">Client Name</th>
                          <th scope="col">Product</th>
                          <th scope="col">Transaction Date</th>
                          <th scope="col">Transaction amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th>Credit </th>
                          <td>James Spader</td>
                          <td><u>Product</u></td>
                          <td>11-01-18</td>
                          <td>$300</td>
                        </tr>
                        <tr>
                          <th>Credit </th>
                          <td>James Spader</td>
                          <td><u>Product</u></td>
                          <td>11-01-18</td>
                          <td>$300</td>
                        </tr>
                        <tr>
                          <th>Credit </th>
                          <td> by you </td>
                          <td></td>
                          <td>11-01-18</td>
                          <td>$300</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

              </div>
              <!-- wallet-group -->
          </div>
          <!------------- right side -------------->
      </div>

    <!-- login -->
  </div>
</div>
