<style>
header { background:none;}
</style>

<div class="about_part">
	<div class="top">
    	<div class="top1">
        	<div class="heading">
            	<div class="container">
					<p class="title"><?php echo $this->page_content["page_title_".$_COOKIE['currentLang']];?></p>
                </div>            
            </div>
    	</div>
    </div>
</div>

   
<div class="contact_page">         
 <div class="container">
 	<div class="row contact_part">
 		<div class="col-12 col-xl-8 col-lg-8 col-md-8 col-sm-12 contact_details">
		
			<?php echo $this->page_content["page_content_".$_COOKIE['currentLang']];?>
			<form id="i-recaptcha" action="<?=$this->url('front_contactus')?>" class="profile_form" method="post">
			  <div class="row">
				<div class="col" style="margin-right: 1vw;padding:0">
				  <div class="form-group">
				  <?php echo $this->formElement($this->form->get('user_name'));?>
                  </div>
                 
				</div>
				<div class="col" style="margin-left: 1vw;padding:0">
				  <div class="form-group">
				 <?php echo $this->formElement($this->form->get('user_email'));?>
                 </div>
				</div>
				<div class="col-12" style="padding:0">
				  <div class="form-group"> <?php echo $this->formElement($this->form->get('user_subject'));?></div>
				</div>
				<div class="col-12" style="padding:0">
				   <div class=" form-group"><?php echo $this->formElement($this->form->get('user_message'));?></div>
				</div>
                 <?php echo $this->formElement($this->form->get('post_csrf'));?>
                
                <div class="col-12"  style="padding:0">
					 <button type="button" class="btn" id="startedbtn">Send Message</button>
                </div>
			  </div>
			</form>
			
		</div>
		<div class="col-12 col-xl-4 col-lg-4 col-md-4 col-sm-12 maps">
			<div id="googleMap"  class="google_map" style="width:100%;height:89%;"></div>
		</div>
 		
	</div>
 </div>
</div>	

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD1J9PzpfMoF8cTffw2OA30gx8CpMPa__s"></script>
<script>
var map;
var sch_latitude='<?php echo $this->SITE_CONFIG['site_latitude']?>';
var sch_longitude='<?php echo $this->SITE_CONFIG['site_longitude']?>';
var myCenter=new google.maps.LatLng(sch_latitude,sch_longitude);

function initialize()
{
	var mapProp = {
		  center:myCenter,
		  zoom:9,
			  mapTypeId:google.maps.MapTypeId.ROADMAP,
			  scrollwheel: false,
			  styles: {
 				 saturation:1
				}
			};   
	var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
	var positionLoc = new google.maps.LatLng(sch_latitude,sch_longitude);
	var position = new google.maps.Marker({
				 position:positionLoc,
				icon:'<?php echo HTTP_IMG_PATH?>/maps-and-flags.svg',
		});
		position.setMap(map);
}	

google.maps.event.addDomListener(window, 'load', initialize);

//----

$(document).ready(function(){
  $('#startedbtn').on('click', function(){
    /*$(".login_form").validate().element("#client_email");
    $(".login_form").validate().element("#client_password");

    var client_email = $('#client_email').val();
    var client_password = $('#client_password').val();*/

    // if(client_email!='' && client_password!=''){
        $('#i-recaptcha').submit();
    // }
  });

});
</script>

<script src="https://www.google.com/recaptcha/api.js?render=<?php echo $this->site_configs['recaptcha_sitekey']?>"></script>
<script>
grecaptcha.ready(function() {
    grecaptcha.execute('<?php echo $this->site_configs['recaptcha_sitekey']?>', {action: 'homepage'}).then(function(token) {
      $('#i-recaptcha').prepend('<input type="hidden" name="g-recaptcha-response" value="' + token + '">');
    });
});
</script>